-- 1. Pastikan tabel ada
CREATE TABLE IF NOT EXISTS public.master_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_sku TEXT NOT NULL UNIQUE,
    nama TEXT NOT NULL,
    deskripsi TEXT,
    kategori TEXT DEFAULT 'Lainnya',
    satuan TEXT DEFAULT 'Pcs',
    min_stock NUMERIC DEFAULT 0,
    hpp NUMERIC DEFAULT 0,
    harga_jual NUMERIC DEFAULT 0,
    hpp_updated_at DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Aktifkan RLS
ALTER TABLE public.master_sku ENABLE ROW LEVEL SECURITY;

-- 3. Hapus Policy Lama (jika ada)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.master_sku;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.master_sku;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.master_sku;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON public.master_sku;
DROP POLICY IF EXISTS "Public Access SKU" ON public.master_sku;

-- 4. Buat Policy Baru (Allow All untuk sementara agar tidak error)
CREATE POLICY "Public Access SKU" ON public.master_sku FOR ALL USING (true) WITH CHECK (true);

-- 5. Beri Akses ke Role
GRANT ALL ON public.master_sku TO anon, authenticated, service_role;

-- 6. Refresh Cache (Penting untuk PostgREST)
NOTIFY pgrst, 'reload config';
