/* 
  FILE: supabase_setup.sql
  DESKRIPSI: Script untuk membuat tabel Master Gaji dan mengaktifkan akses aplikasi.
  CARA PAKAI: Copy semua kode ini -> Buka Supabase SQL Editor -> Paste -> Klik Run.
*/

-- 1. Membuat Tabel Master Gaji
CREATE TABLE IF NOT EXISTS master_gaji (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bulan TEXT NOT NULL,              -- Contoh: 'September 2025'
  grade TEXT NOT NULL,              -- Contoh: 'A', 'B', 'Staff'
  gaji_pokok NUMERIC DEFAULT 0,     -- Gaji Pokok Bulanan
  gaji_harian NUMERIC DEFAULT 0,    -- Gaji Per Hari (Gapok / 26)
  gaji_setengah_hari NUMERIC DEFAULT 0,
  gaji_per_jam NUMERIC DEFAULT 0,
  lembur NUMERIC DEFAULT 0,         -- Rate Lembur Per Jam
  uang_makan NUMERIC DEFAULT 0,     -- Tunjangan Makan Bulanan
  uang_kehadiran NUMERIC DEFAULT 0, -- Tunjangan Kehadiran Bulanan
  bonus NUMERIC DEFAULT 0,
  uang_makan_harian NUMERIC DEFAULT 0,
  uang_kehadiran_harian NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Mengaktifkan Fitur Keamanan (Row Level Security)
ALTER TABLE master_gaji ENABLE ROW LEVEL SECURITY;

-- 3. Memberikan Izin Akses Penuh ke Aplikasi
-- (Menghapus policy lama jika ada untuk mencegah error "policy already exists")
DROP POLICY IF EXISTS "Public Access" ON master_gaji;

CREATE POLICY "Public Access" ON master_gaji 
FOR ALL USING (true) 
WITH CHECK (true);

-- 4. Refresh Cache API Supabase (Opsional, agar perubahan langsung terdeteksi)
NOTIFY pgrst, 'reload config';
