-- ============================================================
-- SCRIPT PERBAIKAN DATABASE STOCK OPNAME
-- Silakan Run script ini di Supabase SQL Editor
-- ============================================================

-- 1. Hapus tabel lama jika ada (agar bersih dari error struktur lama)
DROP TABLE IF EXISTS stock_opname_gudang;

-- 2. Pastikan tabel header 'stock_opname' sudah ada
CREATE TABLE IF NOT EXISTS stock_opname (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nomor_so TEXT NOT NULL,
  tanggal DATE DEFAULT CURRENT_DATE,
  lokasi TEXT,
  status TEXT DEFAULT 'Proses',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Buat tabel 'stock_opname_gudang' dengan struktur yang BENAR
CREATE TABLE stock_opname_gudang (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_opname_id BIGINT REFERENCES stock_opname(id) ON DELETE CASCADE,
  sku_id UUID REFERENCES master_sku(id),
  tanggal DATE,
  lokasi TEXT DEFAULT 'Gudang Utama',
  no_karung TEXT DEFAULT '-',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending',
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Aktifkan Keamanan Data (RLS) agar bisa diakses aplikasi
ALTER TABLE stock_opname_gudang ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_opname ENABLE ROW LEVEL SECURITY;

-- 5. Buat Policy agar aplikasi bisa Membaca, Menulis, Mengedit, dan Menghapus
-- Policy untuk stock_opname_gudang
CREATE POLICY "Public Access SO Gudang" ON stock_opname_gudang
FOR ALL USING (true);

-- Policy untuk stock_opname (Header)
CREATE POLICY "Public Access SO Header" ON stock_opname
FOR ALL USING (true);

-- Selesai. Database Anda sekarang sudah siap untuk fitur Stock Opname.
