import React, { useState, useEffect } from 'react';
import { Calendar, Save, Loader2, Filter, CheckCircle2, AlertCircle, Search, Database, Copy, X } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';

export const AdminDailyAttendanceInput: React.FC = () => {
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [selectedMonth, setSelectedMonth] = useState('');
  const [employees, setEmployees] = useState<any[]>([]);
  const [availableMonths, setAvailableMonths] = useState<string[]>([]);
  
  // State Input: Key = Kode Karyawan
  const [inputState, setInputState] = useState<Record<string, { kehadiran: string; jam_lembur: string; lembur_tm: string; keterangan: string }>>({});
  
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [statusMessage, setStatusMessage] = useState<any>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [showSql, setShowSql] = useState(false);

  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });

  // SQL Code for manual copy if needed
  const sqlCode = `
CREATE TABLE IF NOT EXISTS public.presensi_harian_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT, jabatan TEXT, divisi TEXT, perusahaan TEXT, bulan TEXT,
    kehadiran TEXT, 
    jam_lembur NUMERIC DEFAULT 0, 
    lembur_tm NUMERIC DEFAULT 0, -- Kolom Baru
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_presensi_admin_harian UNIQUE (tanggal, kode)
);
ALTER TABLE public.presensi_harian_admin_pabrik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON public.presensi_harian_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.presensi_harian_admin_pabrik TO anon, authenticated, service_role;
  `;

  useEffect(() => {
    const fetchMonths = async () => {
      if (!isSupabaseConfigured()) return;
      const { data } = await supabase.from('data_karyawan_admin_pabrik').select('bulan').order('created_at', { ascending: false });
      if (data) {
        const months = [...new Set(data.map(d => d.bulan))].filter(Boolean);
        setAvailableMonths(months);
        if (months.length > 0 && !selectedMonth) setSelectedMonth(months[0]);
      }
    };
    fetchMonths();
  }, []);

  useEffect(() => {
    if (!selectedMonth) return;
    const fetchEmployees = async () => {
      setIsLoading(true);
      try {
        const { data, error } = await supabase.from('data_karyawan_admin_pabrik').select('*').eq('bulan', selectedMonth).order('nama', { ascending: true });
        if (error) throw error;
        setEmployees(data || []);
        
        const initialInput: any = {};
        data?.forEach(emp => { 
            initialInput[emp.kode] = { kehadiran: '', jam_lembur: '0', lembur_tm: '0', keterangan: '' }; 
        });
        setInputState(initialInput);
        
        checkExistingAttendance(data || []);
      } catch (error: any) { 
        console.error(error);
      } finally { setIsLoading(false); }
    };
    fetchEmployees();
  }, [selectedMonth]);

  const checkExistingAttendance = async (currentEmployees: any[]) => {
    setIsTableMissing(false);
    const { data: existing, error } = await supabase
        .from('presensi_harian_admin_pabrik')
        .select('*')
        .eq('tanggal', selectedDate);
    
    if (error) {
        if (error.code === '42P01' || error.message.includes('does not exist') || error.message.includes('column')) {
            setIsTableMissing(true);
        }
        return;
    }

    if (existing && existing.length > 0) {
      setStatusMessage({ type: 'info', text: `Ditemukan ${existing.length} data tersimpan. Mode Edit.` });
      setInputState(prev => {
        const newState = { ...prev };
        existing.forEach((record: any) => {
          if (newState[record.kode]) {
            newState[record.kode] = { 
                kehadiran: record.kehadiran || '', 
                jam_lembur: (record.jam_lembur || 0).toString(), 
                lembur_tm: (record.lembur_tm || 0).toString(), // Load existing TM
                keterangan: record.keterangan || '' 
            };
          }
        });
        return newState;
      });
    } else {
      setStatusMessage(null);
    }
  };

  useEffect(() => { checkExistingAttendance(employees); }, [selectedDate]);

  const handleInputChange = (kode: string, field: string, value: string) => {
    setInputState(prev => ({ ...prev, [kode]: { ...prev[kode], [field]: value } }));
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const validData = employees.map(emp => {
        const input = inputState[emp.kode];
        // Filter empty rows (skip if all fields are empty/zero)
        if (!input?.kehadiran && (!input?.jam_lembur || input?.jam_lembur == '0') && (!input?.lembur_tm || input?.lembur_tm == '0') && !input?.keterangan) return null;
        
        return {
          tanggal: selectedDate,
          kode: emp.kode,
          nama: emp.nama,
          jabatan: emp.jabatan,
          divisi: emp.divisi,
          bulan: selectedMonth,
          perusahaan: emp.perusahaan,
          kehadiran: input.kehadiran,
          jam_lembur: parseFloat(input.jam_lembur) || 0,
          lembur_tm: parseFloat(input.lembur_tm) || 0, // Save TM
          keterangan: input.keterangan,
          updated_at: new Date().toISOString()
        };
      }).filter(Boolean);

      if (validData.length === 0) { alert("Isi data minimal satu orang."); setIsSaving(false); return; }

      const { error } = await supabase.from('presensi_harian_admin_pabrik').upsert(validData, { onConflict: 'tanggal,kode' });
      if (error) throw error;

      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Presensi admin tersimpan.' });
    } catch (error: any) {
      if (error.message?.includes('column "lembur_tm" of relation "presensi_harian_admin_pabrik" does not exist')) {
          setIsTableMissing(true);
          setShowSql(true);
      } else {
          setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
      }
    } finally {
      setIsSaving(false);
    }
  };

  const filteredEmployees = employees.filter(emp => 
    emp.nama.toLowerCase().includes(searchTerm.toLowerCase()) ||
    emp.kode.toLowerCase().includes(searchTerm.toLowerCase()) ||
    emp.jabatan.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlCode);
    alert("SQL Copied!");
  };

  return (
    <div className="space-y-6 h-full flex flex-col">
      {/* Filter Section */}
      <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm flex flex-col lg:flex-row gap-4 items-end shrink-0">
        <div className="flex-1 w-full grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Tanggal</label>
            <input type="date" value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" />
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Bulan Data</label>
            <select value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none bg-white">
              <option value="" disabled>Pilih Bulan</option>
              {availableMonths.map(m => <option key={m} value={m}>{m}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Cari Karyawan</label>
            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                <input 
                    type="text" 
                    placeholder="Nama / Kode / Jabatan..." 
                    value={searchTerm} 
                    onChange={(e) => setSearchTerm(e.target.value)} 
                    className="w-full pl-9 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none"
                />
            </div>
          </div>
        </div>
        <div className="flex gap-2">
            {isTableMissing && (
                <button onClick={() => setShowSql(true)} className="bg-red-50 text-red-600 border border-red-200 px-4 py-2.5 rounded-lg text-sm font-bold flex items-center gap-2 hover:bg-red-100 transition-all animate-pulse">
                    <Database size={18}/> Fix DB
                </button>
            )}
            <button onClick={handleSave} disabled={isSaving} className="bg-erp-pink hover:bg-pink-600 text-white px-6 py-2.5 rounded-lg text-sm font-bold flex items-center gap-2 shadow-md transition-all disabled:opacity-50">
            {isSaving ? <Loader2 className="animate-spin" size={18}/> : <Save size={18}/>} Simpan
            </button>
        </div>
      </div>

      {statusMessage && (
        <div className="bg-blue-50 text-blue-700 p-3 rounded-lg text-sm flex items-center gap-2 border border-blue-200 shrink-0">
          <AlertCircle size={18}/> {statusMessage.text}
        </div>
      )}

      {/* Scrollable Table Container */}
      <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden flex flex-col h-[600px]">
        <div className="flex-1 overflow-auto custom-scrollbar relative">
            <table className="w-full text-sm text-left whitespace-nowrap relative border-collapse">
            <thead className="bg-gray-100 text-gray-600 font-bold border-b border-gray-200 sticky top-0 z-10 shadow-sm">
                <tr>
                <th className="px-6 py-3">Kode</th>
                <th className="px-6 py-3">Nama</th>
                <th className="px-6 py-3">Jabatan</th>
                <th className="px-6 py-3">Divisi</th>
                <th className="px-6 py-3 text-center w-32">Kehadiran</th>
                <th className="px-6 py-3 text-center w-24">Lembur</th>
                <th className="px-6 py-3 text-center w-24 bg-red-50 text-red-700">Lembur TM</th>
                <th className="px-6 py-3">Keterangan</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
                {isLoading ? (
                    <tr><td colSpan={8} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink"/> Memuat data...</td></tr>
                ) : filteredEmployees.length > 0 ? (
                    filteredEmployees.map(emp => (
                    <tr key={emp.id} className="hover:bg-gray-50 transition-colors">
                        <td className="px-6 py-3 font-mono text-gray-600">{emp.kode}</td>
                        <td className="px-6 py-3 font-medium text-gray-900">{emp.nama}</td>
                        <td className="px-6 py-3 text-gray-600">{emp.jabatan}</td>
                        <td className="px-6 py-3 text-gray-600">{emp.divisi}</td>
                        <td className="px-6 py-3">
                            <input 
                                type="text" 
                                value={inputState[emp.kode]?.kehadiran || ''} 
                                onChange={e => handleInputChange(emp.kode, 'kehadiran', e.target.value)} 
                                className={`w-full px-2 py-1.5 border rounded text-center font-bold uppercase focus:ring-2 focus:ring-erp-pink outline-none ${
                                    ['H','HADIR'].includes((inputState[emp.kode]?.kehadiran || '').toUpperCase()) ? 'bg-green-50 text-green-700 border-green-200' : 
                                    ['S','SAKIT'].includes((inputState[emp.kode]?.kehadiran || '').toUpperCase()) ? 'bg-blue-50 text-blue-700 border-blue-200' :
                                    ['I','IZIN'].includes((inputState[emp.kode]?.kehadiran || '').toUpperCase()) ? 'bg-yellow-50 text-yellow-700 border-yellow-200' :
                                    'bg-white border-gray-300'
                                }`}
                                placeholder="H/S/I/A"
                            />
                        </td>
                        <td className="px-6 py-3">
                            <input 
                                type="number" 
                                value={inputState[emp.kode]?.jam_lembur || ''} 
                                onChange={e => handleInputChange(emp.kode, 'jam_lembur', e.target.value)} 
                                className="w-full px-2 py-1.5 border border-gray-300 rounded text-center focus:ring-2 focus:ring-erp-pink outline-none"
                                placeholder="0"
                            />
                        </td>
                        <td className="px-6 py-3 bg-red-50/20">
                            <input 
                                type="number" 
                                value={inputState[emp.kode]?.lembur_tm || ''} 
                                onChange={e => handleInputChange(emp.kode, 'lembur_tm', e.target.value)} 
                                className="w-full px-2 py-1.5 border border-red-200 rounded text-center focus:ring-2 focus:ring-red-400 outline-none text-red-700 font-medium"
                                placeholder="0"
                            />
                        </td>
                        <td className="px-6 py-3">
                            <input 
                                type="text" 
                                value={inputState[emp.kode]?.keterangan || ''} 
                                onChange={e => handleInputChange(emp.kode, 'keterangan', e.target.value)} 
                                className="w-full px-3 py-1.5 border border-gray-300 rounded text-sm focus:ring-2 focus:ring-erp-pink outline-none"
                                placeholder="Catatan..."
                            />
                        </td>
                    </tr>
                    ))
                ) : (
                    <tr><td colSpan={8} className="p-16 text-center text-gray-400 italic">Tidak ada data karyawan ditemukan.</td></tr>
                )}
            </tbody>
            </table>
        </div>
      </div>

      {showSql && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
                <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-red-50">
                    <h3 className="font-bold text-red-800 flex items-center gap-2"><Database size={20}/> Setup Database</h3>
                    <button onClick={() => setShowSql(false)}><X size={24} className="text-gray-400"/></button>
                </div>
                <div className="p-6">
                    <p className="text-sm text-gray-600 mb-4">Salin kode ini dan jalankan di Supabase SQL Editor:</p>
                    <div className="relative">
                        <textarea readOnly value={sqlCode} className="w-full h-48 p-3 text-xs font-mono bg-gray-50 border rounded-lg focus:ring-2 focus:ring-erp-pink outline-none" onClick={e => e.currentTarget.select()}/>
                        <button onClick={handleCopySQL} className="absolute top-2 right-2 p-2 bg-white rounded shadow-sm border hover:bg-gray-50"><Copy size={16}/></button>
                    </div>
                </div>
            </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
    </div>
  );
};
