import React, { useState, useEffect, useRef, useMemo } from 'react';
import { Search, Plus, Edit2, Trash2, Loader2, RefreshCw, Database, FileSpreadsheet, Upload, Download, AlertCircle } from 'lucide-react';
import { AdminEmployeeModal } from './AdminEmployeeModal';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import * as XLSX from 'xlsx';

export const AdminEmployeeData: React.FC = () => {
  const [employees, setEmployees] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  
  // Selection State
  const [selectedIds, setSelectedIds] = useState<number[]>([]);

  // Modal States
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Feedback Modals
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ isOpen: boolean; onConfirm: () => void; title?: string; message?: string; confirmLabel?: string }>({ isOpen: false, onConfirm: () => {} });

  const fileInputRef = useRef<HTMLInputElement>(null);

  // SQL Fix Code (Robust Version)
  const sqlFixCode = `
-- [FIX] Ensure 'data_karyawan_admin_pabrik' has all required columns
CREATE TABLE IF NOT EXISTS public.data_karyawan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS jenis_kelamin TEXT DEFAULT 'L';
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS jabatan TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS divisi TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS perusahaan TEXT DEFAULT 'CV GARUT';
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS bulan TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS keterangan TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS status_aktif BOOLEAN DEFAULT true;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_kode_bulan_admin') THEN
        ALTER TABLE public.data_karyawan_admin_pabrik 
        ADD CONSTRAINT unique_kode_bulan_admin UNIQUE (kode, bulan);
    END IF;
END $$;

ALTER TABLE public.data_karyawan_admin_pabrik ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Admin Data" ON public.data_karyawan_admin_pabrik;
CREATE POLICY "Public Access Admin Data" ON public.data_karyawan_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.data_karyawan_admin_pabrik TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
  `;

  const fetchData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    setSelectedIds([]); // Reset selection on refresh
    
    if (!isSupabaseConfigured()) {
        setIsLoading(false);
        return;
    }

    try {
        const { data, error } = await supabase
            .from('data_karyawan_admin_pabrik')
            .select('*')
            .order('nama', { ascending: true });

        if (error) {
            if (error.code === '42P01' || error.message.includes('does not exist')) {
                setIsTableMissing(true);
            }
            throw error;
        }
        setEmployees(data || []);
    } catch (error: any) {
        console.error("Fetch error:", error.message);
    } finally {
        setIsLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, []);

  // --- FILTERING ---
  const filteredData = useMemo(() => {
    return employees.filter(item => 
      item.nama.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.kode.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [employees, searchTerm]);

  // --- SELECTION LOGIC ---
  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      setSelectedIds(filteredData.map(item => item.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelectOne = (id: number) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(prev => prev.filter(i => i !== id));
    } else {
      setSelectedIds(prev => [...prev, id]);
    }
  };

  const isAllSelected = filteredData.length > 0 && filteredData.every(item => selectedIds.includes(item.id));

  // --- CRUD HANDLERS ---
  const handleSave = async (formData: any) => {
    setIsSaving(true);
    try {
        if (selectedItem) {
            const { error } = await supabase.from('data_karyawan_admin_pabrik').update(formData).eq('id', selectedItem.id);
            if (error) throw error;
        } else {
            const { error } = await supabase.from('data_karyawan_admin_pabrik').insert([formData]);
            if (error) throw error;
        }
        setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data karyawan admin tersimpan.' });
        fetchData();
        setIsModalOpen(false);
    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
    } finally {
        setIsSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Data',
      message: 'Yakin ingin menghapus data karyawan ini?',
      confirmLabel: 'Hapus',
      onConfirm: async () => {
        const { error } = await supabase.from('data_karyawan_admin_pabrik').delete().eq('id', id);
        if (error) {
            setErrorModal({ isOpen: true, title: 'Gagal Hapus', message: error.message });
        } else {
            fetchData();
        }
        setConfirmModal({ isOpen: false, onConfirm: () => {} });
      }
    });
  };

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Massal',
      message: `Yakin ingin menghapus ${selectedIds.length} data terpilih?`,
      confirmLabel: 'Hapus Semua',
      onConfirm: async () => {
        const { error } = await supabase.from('data_karyawan_admin_pabrik').delete().in('id', selectedIds);
        if (error) {
            setErrorModal({ isOpen: true, title: 'Gagal Hapus Massal', message: error.message });
        } else {
            fetchData();
            setSelectedIds([]);
        }
        setConfirmModal({ isOpen: false, onConfirm: () => {} });
      }
    });
  };

  // --- IMPORT / EXPORT / TEMPLATE FUNCTIONS ---

  const handleDownloadTemplate = () => {
    const template = [
      {
        'Kode': 'ADM-001',
        'Nama': 'Budi Admin',
        'L/P': 'L',
        'Jabatan': 'Manager',
        'Divisi': 'Keuangan',
        'Perusahaan': 'CV GARUT',
        'Bulan': 'Oktober 2025',
        'Keterangan': 'Tetap'
      },
      {
        'Kode': 'ADM-002',
        'Nama': 'Siti Staff',
        'L/P': 'P',
        'Jabatan': 'Staff',
        'Divisi': 'HRD',
        'Perusahaan': 'CV GARUT',
        'Bulan': 'Oktober 2025',
        'Keterangan': 'Kontrak'
      }
    ];
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(template);
    
    // Set column widths
    const wscols = [
        { wch: 15 }, { wch: 25 }, { wch: 5 }, { wch: 15 }, 
        { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 20 }
    ];
    ws['!cols'] = wscols;

    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, "Template_Karyawan_Admin.xlsx");
  };

  const handleExport = () => {
    if (employees.length === 0) {
        setErrorModal({ isOpen: true, title: 'Data Kosong', message: 'Tidak ada data untuk diexport.' });
        return;
    }

    const exportData = employees.map(emp => ({
        'Kode': emp.kode,
        'Nama': emp.nama,
        'L/P': emp.jenis_kelamin,
        'Jabatan': emp.jabatan,
        'Divisi': emp.divisi,
        'Perusahaan': emp.perusahaan,
        'Bulan': emp.bulan,
        'Keterangan': emp.keterangan
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(exportData);
    XLSX.utils.book_append_sheet(wb, ws, "Data Karyawan Admin");
    XLSX.writeFile(wb, `Data_Karyawan_Admin_${new Date().toISOString().slice(0,10)}.xlsx`);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (evt) => {
      const bstr = evt.target?.result;
      const wb = XLSX.read(bstr, { type: 'array' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const jsonData = XLSX.utils.sheet_to_json(ws);

      if (jsonData.length === 0) {
        setErrorModal({ isOpen: true, title: 'File Kosong', message: 'File Excel tidak memiliki data.' });
        return;
      }

      setIsImporting(true);
      try {
        // 1. Fetch existing data to check duplicates
        const { data: existingData } = await supabase.from('data_karyawan_admin_pabrik').select('kode, bulan');
        const existingSet = new Set(existingData?.map((e: any) => `${e.kode.trim().toUpperCase()}-${e.bulan.trim().toUpperCase()}`));

        const itemsToInsert: any[] = [];
        const duplicates: string[] = [];

        jsonData.forEach((row: any) => {
            const kode = (row['Kode'] || '').toString().trim();
            const bulan = (row['Bulan'] || '').toString().trim();
            const nama = (row['Nama'] || '').toString().trim();

            if (kode && bulan && nama) {
                const key = `${kode.toUpperCase()}-${bulan.toUpperCase()}`;
                if (existingSet.has(key)) {
                    duplicates.push(`${kode} (${bulan})`);
                } else {
                    itemsToInsert.push({
                        kode: kode,
                        nama: nama,
                        jenis_kelamin: row['L/P'] || 'L',
                        jabatan: row['Jabatan'] || '',
                        divisi: row['Divisi'] || '',
                        perusahaan: row['Perusahaan'] || 'CV GARUT',
                        bulan: bulan,
                        keterangan: row['Keterangan'] || '',
                        status_aktif: true,
                        updated_at: new Date().toISOString()
                    });
                    // Add to set to prevent internal duplicates in the same file
                    existingSet.add(key);
                }
            }
        });

        if (itemsToInsert.length > 0) {
            const { error } = await supabase.from('data_karyawan_admin_pabrik').insert(itemsToInsert);
            if (error) throw error;
            
            let message = `Berhasil mengimport ${itemsToInsert.length} data karyawan.`;
            if (duplicates.length > 0) {
                message += `\n\n⚠️ ${duplicates.length} data dilewati karena duplikat (Kode & Bulan sama).`;
            }
            setSuccessModal({ isOpen: true, title: 'Import Selesai', message });
            fetchData();
        } else if (duplicates.length > 0) {
            setErrorModal({ isOpen: true, title: 'Gagal Import', message: 'Semua data dalam file sudah ada di database (Duplikat).' });
        } else {
            setErrorModal({ isOpen: true, title: 'Gagal Import', message: 'Tidak ada data valid yang ditemukan dalam file.' });
        }

      } catch (error: any) {
        // DETEKSI ERROR KOLOM HILANG
        if (error.message?.includes('keterangan') || error.message?.includes('schema cache')) {
             setErrorModal({ 
                 isOpen: true, 
                 title: 'Struktur Database Belum Update', 
                 message: 'Kolom "keterangan" tidak ditemukan di database. Silakan klik tombol "Setup Table" (ikon Database merah) di pojok kanan atas untuk mendapatkan kode perbaikan.' 
             });
             setIsTableMissing(true); // Show the fix button
        } else {
             setErrorModal({ isOpen: true, title: 'Error Import', message: error.message });
        }
      } finally {
        setIsImporting(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlFixCode);
    alert("SQL Fix Copied! Please run this in Supabase SQL Editor.");
  };

  return (
    <div className="space-y-6 h-full flex flex-col">
      <input type="file" ref={fileInputRef} onChange={handleImport} className="hidden" accept=".xlsx, .xls" />

      {/* --- TOOLBAR --- */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 shrink-0">
        <div className="relative w-full md:w-72">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
          <input 
            type="text" 
            placeholder="Cari Nama / Kode..." 
            value={searchTerm} 
            onChange={e => setSearchTerm(e.target.value)} 
            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-erp-pink/50 shadow-sm" 
          />
        </div>
        <div className="flex flex-wrap gap-2 w-full md:w-auto justify-end">
          {isTableMissing && (
             <button onClick={handleCopySQL} className="p-2 bg-red-50 text-red-600 border border-red-200 rounded-lg hover:bg-red-100 shadow-sm transition-colors flex items-center gap-2 text-sm font-bold animate-pulse">
                <Database size={16}/> Setup Table (Fix DB)
             </button>
          )}
          
          {selectedIds.length > 0 && (
            <button 
              onClick={handleBulkDelete} 
              className="bg-red-100 text-red-600 px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-medium hover:bg-red-200 transition-colors animate-fadeIn"
            >
              <Trash2 size={16}/> Hapus ({selectedIds.length})
            </button>
          )}
          
          <button onClick={handleDownloadTemplate} className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm flex items-center gap-2 text-sm font-medium">
            <FileSpreadsheet size={16}/> Template
          </button>
          
          <button 
            onClick={() => fileInputRef.current?.click()} 
            disabled={isImporting}
            className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm flex items-center gap-2 text-sm font-medium disabled:opacity-50"
          >
            {isImporting ? <Loader2 className="animate-spin" size={16}/> : <Upload size={16}/>} Import
          </button>
          
          <button onClick={handleExport} className="px-3 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 shadow-sm flex items-center gap-2 text-sm font-medium transition-colors">
            <Download size={16}/> Export
          </button>

          <button onClick={fetchData} className="p-2 bg-white border rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm transition-colors" title="Refresh">
            <RefreshCw size={18}/>
          </button>
          
          <button onClick={() => { setSelectedItem(null); setIsModalOpen(true); }} className="bg-erp-pink text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-medium hover:bg-pink-600 shadow-md transition-colors">
            <Plus size={16}/> Tambah Karyawan
          </button>
        </div>
      </div>

      {/* --- SCROLLABLE TABLE --- */}
      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm flex-1 flex flex-col min-h-0">
        <div className="overflow-auto max-h-[600px] custom-scrollbar relative">
          <table className="w-full text-sm text-left whitespace-nowrap relative border-collapse">
            <thead className="bg-gray-50 text-gray-600 font-bold border-b border-gray-200 sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-4 py-4 w-10 text-center">
                  <input 
                    type="checkbox" 
                    className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                    checked={isAllSelected}
                    onChange={handleSelectAll}
                  />
                </th>
                <th className="px-6 py-4">Kode</th>
                <th className="px-6 py-4">Nama</th>
                <th className="px-6 py-4 text-center">L/P</th>
                <th className="px-6 py-4">Jabatan</th>
                <th className="px-6 py-4">Divisi</th>
                <th className="px-6 py-4">Bulan Data</th>
                <th className="px-6 py-4 text-center">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {isLoading ? (
                <tr><td colSpan={8} className="p-12 text-center"><Loader2 className="animate-spin inline mr-2"/> Memuat...</td></tr>
              ) : filteredData.length > 0 ? (
                filteredData.map((item) => (
                  <tr key={item.id} className={`hover:bg-gray-50 transition-colors ${selectedIds.includes(item.id) ? 'bg-pink-50/30' : ''}`}>
                    <td className="px-4 py-4 text-center">
                      <input 
                        type="checkbox" 
                        className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                        checked={selectedIds.includes(item.id)}
                        onChange={() => handleSelectOne(item.id)}
                      />
                    </td>
                    <td className="px-6 py-4 font-mono text-gray-600">{item.kode}</td>
                    <td className="px-6 py-4 font-medium text-gray-900">{item.nama}</td>
                    <td className="px-6 py-4 text-center">
                      <span className={`px-2 py-1 rounded text-xs font-bold ${item.jenis_kelamin === 'L' ? 'bg-blue-50 text-blue-600' : 'bg-pink-50 text-pink-600'}`}>
                        {item.jenis_kelamin}
                      </span>
                    </td>
                    <td className="px-6 py-4">{item.jabatan}</td>
                    <td className="px-6 py-4 text-gray-600">{item.divisi}</td>
                    <td className="px-6 py-4 text-gray-600">{item.bulan}</td>
                    <td className="px-6 py-4 text-center">
                      <div className="flex justify-center gap-2">
                        <button onClick={() => { setSelectedItem(item); setIsModalOpen(true); }} className="p-1.5 text-blue-600 hover:bg-blue-50 rounded border border-transparent hover:border-blue-100 transition-all"><Edit2 size={16}/></button>
                        <button onClick={() => handleDelete(item.id)} className="p-1.5 text-red-600 hover:bg-red-50 rounded border border-transparent hover:border-red-100 transition-all"><Trash2 size={16}/></button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr><td colSpan={8} className="p-16 text-center text-gray-500 italic">Tidak ada data karyawan.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <AdminEmployeeModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} onSubmit={handleSave} initialData={selectedItem} isLoading={isSaving} />
      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal isOpen={confirmModal.isOpen} onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} onConfirm={confirmModal.onConfirm} title={confirmModal.title || "Hapus Karyawan"} message={confirmModal.message || "Yakin ingin menghapus data ini?"} confirmLabel={confirmModal.confirmLabel || "Hapus"} isDangerous={true} />
    </div>
  );
};
