import React, { useState, useEffect, useRef } from 'react';
import { 
  Search, Edit2, Trash2, Loader2, RefreshCw, 
  ChevronLeft, ChevronRight, Download, Upload, 
  FileSpreadsheet, Filter, X, Plus, Database, Copy, AlertCircle, Calendar, Building2, Wrench
} from 'lucide-react';
import * as XLSX from 'xlsx';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import { AdnanHananAttendanceModal } from './AdnanHananAttendanceModal';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';

export const AdnanHananAttendanceInput: React.FC = () => {
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  
  // Filter State
  const [searchTerm, setSearchTerm] = useState('');
  const [filterMonth, setFilterMonth] = useState('');
  const [filterPeriod, setFilterPeriod] = useState('');
  const [filterCompany, setFilterCompany] = useState(''); 
  const [startDate, setStartDate] = useState(''); 
  const [endDate, setEndDate] = useState(''); 

  // Options State
  const [availableMonths, setAvailableMonths] = useState<string[]>([]);
  const [uniqueCompanies, setUniqueCompanies] = useState<string[]>([]); 
  
  // Pagination
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(100);
  const [totalData, setTotalData] = useState(0);

  // Selection & Actions
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [isImporting, setIsImporting] = useState(false);
  const [importProgress, setImportProgress] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  
  // Batch Delete State
  const [isDeleting, setIsDeleting] = useState(false);
  const [deleteProgress, setDeleteProgress] = useState('');

  // Modals
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [sqlMode, setSqlMode] = useState<'create' | 'fix_trigger'>('create'); // Mode SQL
  
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ 
    isOpen: boolean; 
    onConfirm: () => void; 
    title?: string; 
    message?: string; 
    confirmLabel?: string; 
    isDangerous?: boolean;
    isLoading?: boolean;
  }>({ isOpen: false, onConfirm: () => {}, title: '', message: '' });

  const fileInputRef = useRef<HTMLInputElement>(null);

  // SQL 1: Create Table (Basic)
  const sqlCreateTable = `
CREATE TABLE IF NOT EXISTS public.input_absensi_harian_adnan_hanan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    grade_p1 TEXT,
    grade_p2 TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur NUMERIC DEFAULT 0,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_absensi_adnan_hanan_harian') THEN
        ALTER TABLE public.input_absensi_harian_adnan_hanan 
        ADD CONSTRAINT unique_absensi_adnan_hanan_harian UNIQUE (tanggal, kode);
    END IF;
END $$;

ALTER TABLE public.input_absensi_harian_adnan_hanan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Adnan Hanan Absensi" ON public.input_absensi_harian_adnan_hanan;
CREATE POLICY "Public Access Adnan Hanan Absensi" ON public.input_absensi_harian_adnan_hanan FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.input_absensi_harian_adnan_hanan TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
`;

  // SQL 2: Fix Trigger Duplicate (Advanced)
  const sqlFixTrigger = `
-- FIX: TRIGGER SYNC ABSENSI KE GAJI HARIAN (UPSERT / ANTI-DUPLICATE)
-- Script ini memperbaiki error "duplicate key value violates unique constraint" saat import.

-- 1. Pastikan Tabel Target (Gaji Harian) memiliki Constraint Unik yang Benar
ALTER TABLE public.gaji_harian_pabrik_garut DROP CONSTRAINT IF EXISTS unique_gaji_harian_garut_entry;
ALTER TABLE public.gaji_harian_pabrik_garut DROP CONSTRAINT IF EXISTS unique_gaji_harian_pabrik_garut;

-- Tambahkan constraint unik pada (tanggal, kode) agar ON CONFLICT bekerja
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_gaji_harian_pabrik_garut') THEN
        ALTER TABLE public.gaji_harian_pabrik_garut 
        ADD CONSTRAINT unique_gaji_harian_pabrik_garut UNIQUE (tanggal, kode);
    END IF;
END $$;

-- 2. Buat Fungsi Trigger yang Aman (Menggunakan ON CONFLICT DO UPDATE)
CREATE OR REPLACE FUNCTION public.trigger_sync_absensi_to_gaji_harian()
RETURNS TRIGGER AS $$
DECLARE
    v_grade TEXT;
BEGIN
    -- Tentukan Grade berdasarkan Periode
    IF NEW.periode ILIKE '%Periode 2%' THEN
        v_grade := NEW.grade_p2;
    ELSE
        v_grade := NEW.grade_p1;
    END IF;

    -- Upsert ke tabel Gaji Harian
    INSERT INTO public.gaji_harian_pabrik_garut (
        tanggal, kode, nama, grade, bulan, periode, perusahaan, 
        kehadiran, lembur, keterangan, updated_at
    )
    VALUES (
        NEW.tanggal, NEW.kode, NEW.nama, v_grade, NEW.bulan, NEW.periode, NEW.perusahaan, 
        NEW.kehadiran, NEW.lembur, NEW.keterangan, NOW()
    )
    ON CONFLICT (tanggal, kode) DO UPDATE SET
        kehadiran = EXCLUDED.kehadiran,
        lembur = EXCLUDED.lembur,
        keterangan = EXCLUDED.keterangan,
        -- Update grade/nama juga jika berubah di input
        grade = EXCLUDED.grade, 
        nama = EXCLUDED.nama,
        updated_at = NOW();
        
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Pasang Ulang Trigger
DROP TRIGGER IF EXISTS trg_sync_absensi_gaji ON public.input_absensi_harian_adnan_hanan;
CREATE TRIGGER trg_sync_absensi_gaji
AFTER INSERT OR UPDATE ON public.input_absensi_harian_adnan_hanan
FOR EACH ROW EXECUTE FUNCTION public.trigger_sync_absensi_to_gaji_harian();

NOTIFY pgrst, 'reload config';
`;

  const handleCopySQL = () => {
    const code = sqlMode === 'create' ? sqlCreateTable : sqlFixTrigger;
    navigator.clipboard.writeText(code);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
  };

  // --- FETCH OPTIONS (Months & Companies) ---
  useEffect(() => {
    const fetchOptions = async () => {
      if (!isSupabaseConfigured()) return;
      try {
        let allMonths = new Set<string>();
        let allCompanies = new Set<string>();
        let from = 0;
        const step = 1000;
        let hasMore = true;

        // Loop fetch to bypass 1000 row limit
        while (hasMore) {
            const { data, error } = await supabase
                .from('input_absensi_harian_adnan_hanan')
                .select('bulan, perusahaan')
                .range(from, from + step - 1)
                .order('created_at', { ascending: false });
            
            if (error) throw error;

            if (data && data.length > 0) {
                data.forEach(d => {
                    if (d.bulan) allMonths.add(d.bulan);
                    if (d.perusahaan) allCompanies.add(d.perusahaan);
                });
                
                if (data.length < step) hasMore = false;
                else from += step;
            } else {
                hasMore = false;
            }
        }

        // Process Months
        const monthsArray = Array.from(allMonths);
        const monthMap: Record<string, number> = {
            'januari': 1, 'februari': 2, 'maret': 3, 'april': 4, 'mei': 5, 'juni': 6,
            'juli': 7, 'agustus': 8, 'september': 9, 'oktober': 10, 'november': 11, 'desember': 12
        };

        const sortedMonths = monthsArray.sort((a, b) => {
            const partsA = a.split(' ');
            const partsB = b.split(' ');
            const monthA = partsA[0]?.toLowerCase();
            const monthB = partsB[0]?.toLowerCase();
            const yearA = parseInt(partsA[1]) || 0;
            const yearB = parseInt(partsB[1]) || 0;

            if (yearA !== yearB) return yearB - yearA; 
            return (monthMap[monthB] || 0) - (monthMap[monthA] || 0);
        });

        setAvailableMonths(sortedMonths);
        
        if (sortedMonths.length > 0 && !filterMonth) {
            setFilterMonth(sortedMonths[0]);
        }

        // Process Companies
        const sortedCompanies = Array.from(allCompanies).sort();
        setUniqueCompanies(sortedCompanies);

      } catch (e) {
        console.error("Error fetching options:", e);
      }
    };
    fetchOptions();
  }, []);

  // --- FETCH DATA ---
  const fetchData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    setSelectedIds([]); 
    
    if (!isSupabaseConfigured()) {
        setIsLoading(false);
        return;
    }

    try {
        const from = (page - 1) * pageSize;
        const to = from + pageSize - 1;

        let query = supabase
            .from('input_absensi_harian_adnan_hanan')
            .select('*', { count: 'exact' });

        if (searchTerm) {
            query = query.or(`kode.ilike.%${searchTerm}%,keterangan.ilike.%${searchTerm}%`);
        }
        if (filterMonth) query = query.eq('bulan', filterMonth);
        if (filterPeriod && filterPeriod !== 'Semua') query = query.eq('periode', filterPeriod);
        
        if (filterCompany && filterCompany !== 'Semua') query = query.eq('perusahaan', filterCompany);
        if (startDate) query = query.gte('tanggal', startDate);
        if (endDate) query = query.lte('tanggal', endDate);

        const { data: result, error, count } = await query
            .order('tanggal', { ascending: false })
            .order('kode', { ascending: true })
            .range(from, to);

        if (error) {
            if (error.code === '42P01' || error.code === 'PGRST205' || error.message.includes('does not exist') || error.message.includes('schema cache')) {
                setIsTableMissing(true);
                setSqlMode('create'); // Default to create table mode
                return; 
            }
            throw error;
        }
        setData(result || []);
        setTotalData(count || 0);
    } catch (error: any) {
        if (error.message?.includes('schema cache') || error.message?.includes('does not exist')) {
             setIsTableMissing(true);
             setSqlMode('create');
        } else {
             console.error("Fetch error:", error.message);
        }
    } finally {
        setIsLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, [page, pageSize, searchTerm, filterMonth, filterPeriod, filterCompany, startDate, endDate]);

  // --- HANDLERS ---

  const handleSave = async (formData: any) => {
    setIsSaving(true);
    try {
        const safeLembur = (formData.lembur === '' || formData.lembur === null || isNaN(Number(formData.lembur))) 
            ? 0 
            : Number(formData.lembur);

        const payload = {
            ...formData,
            lembur: safeLembur,
            updated_at: new Date().toISOString()
        };

        if (selectedItem) {
            const { error } = await supabase.from('input_absensi_harian_adnan_hanan').update(payload).eq('id', selectedItem.id);
            if (error) throw error;
        } else {
            const { error } = await supabase.from('input_absensi_harian_adnan_hanan').insert([payload]);
            if (error) throw error;
        }
        setIsModalOpen(false);
        setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data absensi tersimpan.' });
        fetchData();
    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
    } finally {
        setIsSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Data',
      message: 'Yakin ingin menghapus data absensi ini?',
      confirmLabel: 'Hapus',
      isDangerous: true,
      onConfirm: async () => {
        const { error } = await supabase.from('input_absensi_harian_adnan_hanan').delete().eq('id', id);
        if (error) {
            setErrorModal({ isOpen: true, title: 'Gagal Hapus', message: error.message });
        } else {
            fetchData();
            setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data dihapus.' });
        }
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
      }
    });
  };

  // --- BATCH DELETE (OPTIMIZED) ---
  const executeBatchDelete = async (idsToDelete: number[]) => {
    setIsDeleting(true);
    setDeleteProgress('Menyiapkan...');
    
    try {
        const BATCH_SIZE = 50; 
        const total = idsToDelete.length;
        let processed = 0;
        let errorCount = 0;

        for (let i = 0; i < total; i += BATCH_SIZE) {
            const chunk = idsToDelete.slice(i, i + BATCH_SIZE);
            
            const { error } = await supabase
                .from('input_absensi_harian_adnan_hanan')
                .delete()
                .in('id', chunk);
            
            if (error) {
                console.error("Delete chunk error:", error);
                errorCount += chunk.length;
            } else {
                processed += chunk.length;
            }
            
            setDeleteProgress(`Menghapus... ${Math.min(i + BATCH_SIZE, total)}/${total}`);
            await new Promise(resolve => setTimeout(resolve, 50));
        }

        setIsDeleting(false);
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
        
        if (processed > 0) {
            setSuccessModal({ 
                isOpen: true, 
                title: 'Hapus Selesai', 
                message: `Berhasil menghapus ${processed} data.${errorCount > 0 ? ` Gagal: ${errorCount}` : ''}` 
            });
            fetchData();
            setSelectedIds([]);
        } else if (errorCount > 0) {
            setErrorModal({ isOpen: true, title: 'Gagal Hapus', message: 'Terjadi kesalahan saat menghapus data (Timeout/Network).' });
        }

    } catch (error: any) {
        setIsDeleting(false);
        setErrorModal({ isOpen: true, title: 'Error', message: error.message });
    }
  };

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Massal',
      message: `Hapus ${selectedIds.length} data terpilih?\n\nProses ini akan dilakukan bertahap untuk mencegah timeout.`,
      confirmLabel: 'Hapus Semua',
      isDangerous: true,
      isLoading: false,
      onConfirm: () => executeBatchDelete(selectedIds)
    });
  };

  const handleResetFilters = () => {
      setSearchTerm('');
      setFilterMonth('');
      setFilterPeriod('');
      setFilterCompany('');
      setStartDate('');
      setEndDate('');
      setPage(1);
  };

  // --- IMPORT / EXPORT ---

  const handleDownloadTemplate = () => {
    const template = [{ 
      'Tanggal': new Date().toISOString().split('T')[0], 
      'Kode': 'K001', 
      'Grade P1': 'A',
      'Grade P2': 'Senior',
      'Bulan': 'Desember 2025', 
      'Kehadiran': '1', 
      'Lembur': 2, 
      'Periode': 'Periode 1',
      'Perusahaan': 'CV ADNAN',
      'Keterangan': 'Hadir' 
    }];
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(template);
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, "Template_Absensi_AdnanHanan.xlsx");
  };

  const handleExport = async () => {
    setIsLoading(true);
    try {
        let allData: any[] = [];
        let from = 0;
        const step = 1000;
        let hasMore = true;

        while (hasMore) {
            let query = supabase.from('input_absensi_harian_adnan_hanan').select('*');
            if (searchTerm) query = query.or(`kode.ilike.%${searchTerm}%,keterangan.ilike.%${searchTerm}%`);
            if (filterMonth) query = query.eq('bulan', filterMonth);
            if (filterPeriod && filterPeriod !== 'Semua') query = query.eq('periode', filterPeriod);
            if (filterCompany && filterCompany !== 'Semua') query = query.eq('perusahaan', filterCompany);
            if (startDate) query = query.gte('tanggal', startDate);
            if (endDate) query = query.lte('tanggal', endDate);

            const { data: batch, error } = await query.range(from, from + step - 1);
            if (error) throw error;

            if (batch && batch.length > 0) {
                allData = [...allData, ...batch];
                from += step;
                if (batch.length < step) hasMore = false;
            } else {
                hasMore = false;
            }
        }

        if (allData.length === 0) { alert("Tidak ada data."); return; }

        const exportData = allData.map(item => ({
            'Tanggal': item.tanggal,
            'Kode': item.kode,
            'Grade P1': item.grade_p1,
            'Grade P2': item.grade_p2,
            'Bulan': item.bulan, 
            'Kehadiran': item.kehadiran,
            'Lembur': item.lembur,
            'Periode': item.periode,
            'Perusahaan': item.perusahaan,
            'Keterangan': item.keterangan
        }));

        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.json_to_sheet(exportData);
        XLSX.utils.book_append_sheet(wb, ws, "Data Absensi");
        XLSX.writeFile(wb, `Absensi_AdnanHanan_${filterMonth || 'All'}.xlsx`);

    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Export', message: error.message });
    } finally {
        setIsLoading(false);
    }
  };

  // --- HELPER: ROBUST DATE PARSER ---
  const parseDate = (val: any): string | null => {
    if (!val) return null;
    try {
      if (typeof val === 'number') {
        return new Date(Math.round((val - 25569) * 86400 * 1000)).toISOString().split('T')[0];
      }
      if (typeof val === 'string') {
        const clean = val.trim();
        if (/^\d{4}-\d{2}-\d{2}$/.test(clean)) return clean;
        const parts = clean.split(/[\/\-]/);
        if (parts.length === 3) {
           const d = parts[0].padStart(2, '0');
           const m = parts[1].padStart(2, '0');
           let y = parts[2];
           if (y.length === 2) y = '20' + y;
           return `${y}-${m}-${d}`;
        }
      }
      if (val instanceof Date) {
         return val.toISOString().split('T')[0];
      }
    } catch (e) {
      return null;
    }
    return null;
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (evt) => {
      try {
        const bstr = evt.target?.result;
        const wb = XLSX.read(bstr, { type: 'array' });
        const ws = wb.Sheets[wb.SheetNames[0]];
        const rawData = XLSX.utils.sheet_to_json(ws) as any[];

        if (rawData.length === 0) {
           setErrorModal({ isOpen: true, title: 'File Kosong', message: 'File Excel tidak memiliki data.' });
           return;
        }

        setIsImporting(true);
        setImportProgress('Memproses Data...');

        // 1. Parse & Validate
        const parsedItems = rawData.map(row => {
            const dateStr = parseDate(row['Tanggal']);
            const kode = (row['Kode'] || '').toString().trim();

            if (!dateStr || !kode) return null;

            return {
                tanggal: dateStr,
                kode: kode,
                grade_p1: (row['Grade P1'] || '').toString(),
                grade_p2: (row['Grade P2'] || '').toString(),
                bulan: (row['Bulan'] || '').toString().trim(),
                kehadiran: (row['Kehadiran'] || '').toString(),
                lembur: Number(row['Lembur'] || 0),
                periode: (row['Periode'] || 'Periode 1').toString(),
                perusahaan: (row['Perusahaan'] || 'CV ADNAN').toString(),
                keterangan: (row['Keterangan'] || '').toString(),
                updated_at: new Date().toISOString()
            };
        }).filter(item => item !== null);

        if (parsedItems.length === 0) {
            setErrorModal({ isOpen: true, title: 'Gagal', message: 'Tidak ada data valid (Tanggal & Kode wajib).' });
            setIsImporting(false);
            return;
        }

        // 2. Deduplicate (Last write wins - Clean internal duplicates)
        const uniqueMap = new Map();
        parsedItems.forEach(item => {
            const key = `${item!.tanggal}_${item!.kode.toUpperCase()}`;
            uniqueMap.set(key, item);
        });
        const itemsToInsert = Array.from(uniqueMap.values());

        setImportProgress('Menyimpan...');
        
        const BATCH_SIZE = 100;
        for (let i = 0; i < itemsToInsert.length; i += BATCH_SIZE) {
            const batch = itemsToInsert.slice(i, i + BATCH_SIZE);
            const { error } = await supabase.from('input_absensi_harian_adnan_hanan').upsert(batch, { onConflict: 'tanggal,kode' });
            
            if (error) {
                // DETEKSI ERROR DUPLICATE KEY (CONSTRAINT VIOLATION)
                if (error.code === '23505' || error.message.includes('unique constraint') || error.message.includes('duplicate key')) {
                     // TAMPILKAN MODAL FIX DATABASE
                     setSqlMode('fix_trigger');
                     setShowSqlModal(true);
                     throw new Error(`Gagal Import: Duplikasi Data Database.\n\nSistem mendeteksi data ganda tetapi database menolak penimpaan otomatis.\n\nSOLUSI: Silakan klik tombol "Perbaiki Database" di bawah untuk mengaktifkan fitur update otomatis.`);
                }
                throw error;
            }
            setImportProgress(`Menyimpan... ${Math.min(i + BATCH_SIZE, itemsToInsert.length)}/${itemsToInsert.length}`);
        }

        setSuccessModal({ isOpen: true, title: 'Import Selesai', message: `Berhasil mengimport ${itemsToInsert.length} data absensi.` });
        fetchData();

      } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Import', message: error.message });
      } finally {
        setIsImporting(false);
        setImportProgress('');
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) setSelectedIds(data.map(item => item.id));
    else setSelectedIds([]);
  };

  const handleSelectOne = (id: number) => {
    if (selectedIds.includes(id)) setSelectedIds(prev => prev.filter(item => item !== id));
    else setSelectedIds(prev => [...prev, id]);
  };

  const isAllSelected = data.length > 0 && data.every(item => selectedIds.includes(item.id));

  const getKehadiranBadge = (val: string) => {
    const v = val.toString().toLowerCase();
    if (v === '1' || v === 'hadir' || v === 'h') return 'bg-green-100 text-green-700 border-green-200';
    if (v === '0.5' || v === 'setengah') return 'bg-yellow-100 text-yellow-700 border-yellow-200';
    if (['s', 'i', 'a', 'sakit', 'izin', 'alpha'].includes(v)) return 'bg-red-100 text-red-700 border-red-200';
    return 'bg-gray-100 text-gray-600 border-gray-200';
  };

  return (
    <div className="space-y-6 h-full flex flex-col font-sans">
      <input type="file" ref={fileInputRef} onChange={handleImport} className="hidden" accept=".xlsx, .xls" />

      {/* --- TOP TOOLBAR --- */}
      <div className="flex flex-col xl:flex-row justify-between items-start xl:items-center gap-4 shrink-0">
        <div className="relative w-full xl:w-96 group">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 group-focus-within:text-erp-pink transition-colors" size={20} />
          <input 
            type="text" 
            placeholder="Cari kode karyawan atau keterangan..." 
            value={searchTerm} 
            onChange={e => { setSearchTerm(e.target.value); setPage(1); }} 
            className="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl text-sm outline-none focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink transition-all shadow-sm" 
          />
        </div>

        <div className="flex flex-wrap gap-2 w-full xl:w-auto items-center justify-end">
          {/* TOMBOL FIX DATABASE (Manual Trigger) */}
          <button 
            onClick={() => { setSqlMode('fix_trigger'); setShowSqlModal(true); }} 
            className="p-2.5 bg-red-50 text-red-600 border border-red-200 rounded-xl hover:bg-red-100 shadow-sm transition-colors flex items-center gap-2 text-sm font-bold"
            title="Perbaiki Database jika terjadi error duplikasi"
          >
            <Wrench size={18}/> Perbaiki Database
          </button>

          {isTableMissing && (
             <button onClick={() => { setSqlMode('create'); setShowSqlModal(true); }} className="p-2.5 bg-yellow-50 text-yellow-600 border border-yellow-200 rounded-xl hover:bg-yellow-100 shadow-sm transition-colors flex items-center gap-2 text-sm font-bold animate-pulse">
                <Database size={18}/> Setup Table
             </button>
          )}

          {selectedIds.length > 0 && (
            <button 
              onClick={handleBulkDelete} 
              disabled={isDeleting}
              className="px-4 py-2.5 bg-red-50 text-red-600 border border-red-100 rounded-xl text-sm font-medium flex items-center gap-2 hover:bg-red-100 transition-all animate-fadeIn disabled:opacity-50"
            >
              {isDeleting ? <Loader2 className="animate-spin" size={18}/> : <Trash2 size={18}/>} 
              Hapus ({selectedIds.length})
            </button>
          )}

          <button onClick={handleDownloadTemplate} className="px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-gray-600 text-sm font-medium flex items-center gap-2 hover:bg-gray-50 hover:border-gray-300 transition-all shadow-sm">
            <FileSpreadsheet size={18}/> Template
          </button>
          
          <button 
            onClick={() => fileInputRef.current?.click()} 
            disabled={isImporting}
            className="px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-gray-600 text-sm font-medium flex items-center gap-2 hover:bg-gray-50 hover:border-gray-300 transition-all shadow-sm disabled:opacity-50 disabled:cursor-not-allowed min-w-[100px] justify-center"
          >
            {isImporting ? <Loader2 className="animate-spin" size={18}/> : <Upload size={18}/>} 
            {isImporting ? importProgress : 'Import'}
          </button>

          <button onClick={handleExport} className="px-4 py-2.5 bg-green-600 text-white rounded-xl hover:bg-green-700 text-sm font-medium flex items-center gap-2 shadow-sm shadow-green-200 transition-all">
            <Download size={18}/> Export
          </button>

          <button onClick={() => fetchData()} className="p-2.5 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 text-gray-600 shadow-sm transition-all" title="Refresh Data">
            <RefreshCw size={20}/>
          </button>

          <button onClick={() => { setSelectedItem(null); setIsModalOpen(true); }} className="bg-erp-pink text-white px-5 py-2.5 rounded-xl flex items-center gap-2 hover:bg-pink-600 text-sm font-medium shadow-md shadow-pink-200 transition-all">
            <Plus size={20}/> Tambah
          </button>
        </div>
      </div>

      {/* --- FILTER SECTION --- */}
      <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm grid grid-cols-1 md:grid-cols-12 gap-4 items-end">
        <div className="col-span-1 md:col-span-12 flex items-center gap-2 text-sm font-bold text-erp-pink mb-1">
          <Filter size={18}/> Filter Data Lanjutan
        </div>
        
        <div className="col-span-1 md:col-span-3">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Rentang Tanggal</label>
          <div className="flex items-center gap-2 bg-gray-50 p-1 rounded-xl border border-gray-200">
            <div className="relative flex-1">
              <Calendar size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
              <input 
                type="date" 
                value={startDate} 
                onChange={(e) => setStartDate(e.target.value)} 
                className="w-full pl-9 pr-2 py-2 bg-transparent text-sm focus:outline-none text-gray-700"
              />
            </div>
            <span className="text-gray-400">-</span>
            <div className="relative flex-1">
              <Calendar size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
              <input 
                type="date" 
                value={endDate} 
                onChange={(e) => setEndDate(e.target.value)} 
                className="w-full pl-9 pr-2 py-2 bg-transparent text-sm focus:outline-none text-gray-700"
              />
            </div>
          </div>
        </div>

        <div className="col-span-1 md:col-span-2">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Bulan</label>
          <select 
            value={filterMonth} 
            onChange={(e) => setFilterMonth(e.target.value)} 
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
          >
            <option value="">Semua Bulan</option>
            {availableMonths.map(m => (
                <option key={m} value={m}>{m}</option>
            ))}
          </select>
        </div>

        <div className="col-span-1 md:col-span-2">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Periode</label>
          <select 
            value={filterPeriod} 
            onChange={(e) => setFilterPeriod(e.target.value)} 
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
          >
            <option value="">Semua Periode</option>
            <option value="Periode 1">Periode 1</option>
            <option value="Periode 2">Periode 2</option>
          </select>
        </div>

        <div className="col-span-1 md:col-span-3">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Perusahaan</label>
          <div className="relative">
            <Building2 size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <select 
              value={filterCompany} 
              onChange={(e) => setFilterCompany(e.target.value)} 
              className="w-full pl-9 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
            >
              <option value="">Semua Perusahaan</option>
              {uniqueCompanies.map(c => (
                  <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="col-span-1 md:col-span-2">
          <button 
            onClick={handleResetFilters} 
            className="w-full px-4 py-2.5 bg-gray-100 text-gray-600 rounded-xl text-sm font-medium hover:bg-gray-200 hover:text-gray-800 flex items-center justify-center gap-2 transition-colors"
          >
            <X size={18} /> Reset Filter
          </button>
        </div>
      </div>

      {/* --- DATA TABLE --- */}
      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm flex-1 flex flex-col min-h-0">
        <div className="overflow-auto max-h-[600px] custom-scrollbar relative">
          <table className="w-full text-sm text-left whitespace-nowrap relative border-collapse">
            <thead className="bg-gray-100 text-gray-600 font-bold sticky top-0 z-10 shadow-sm uppercase text-xs tracking-wider">
              <tr>
                <th className="px-4 py-3 w-12 text-center">No</th>
                <th className="px-4 py-3 w-10 text-center">
                  <input 
                    type="checkbox" 
                    className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                    checked={isAllSelected}
                    onChange={handleSelectAll}
                  />
                </th>
                <th className="px-6 py-4">Tanggal</th>
                <th className="px-6 py-4">Kode</th>
                <th className="px-6 py-4 text-center">Grade P1</th>
                <th className="px-6 py-4 text-center">Grade P2</th>
                <th className="px-6 py-4 text-center">Bulan</th>
                <th className="px-6 py-4 text-center">Kehadiran</th>
                <th className="px-6 py-4 text-center">Lembur</th>
                <th className="px-6 py-4 text-center">Periode</th>
                <th className="px-6 py-4 text-center">Perusahaan</th>
                <th className="px-6 py-4">Keterangan</th>
                <th className="px-6 py-4 text-center">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {isLoading ? (
                <tr><td colSpan={13} className="p-16 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2" size={32}/> Memuat data...</td></tr>
              ) : data.length > 0 ? (
                data.map((item, idx) => (
                  <tr key={item.id} className={`hover:bg-gray-50 transition-colors group ${selectedIds.includes(item.id) ? 'bg-pink-50/40' : ''}`}>
                    <td className="px-4 py-4 text-center text-gray-500">{idx + 1 + ((page - 1) * pageSize)}</td>
                    <td className="px-4 py-4 text-center">
                      <input 
                        type="checkbox" 
                        className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                        checked={selectedIds.includes(item.id)}
                        onChange={() => handleSelectOne(item.id)}
                      />
                    </td>
                    <td className="px-6 py-4 text-gray-700 font-medium">{item.tanggal}</td>
                    <td className="px-6 py-4 font-mono text-gray-600 bg-gray-50/50 rounded px-2 w-fit">{item.kode}</td>
                    <td className="px-6 py-4 text-center">
                        <span className={`min-w-[24px] px-1 py-0.5 rounded text-[10px] font-bold border flex items-center justify-center ${item.grade_p1 ? 'bg-blue-50 text-blue-700 border-blue-100' : 'bg-gray-50 text-gray-400 border-gray-100 opacity-60'}`}>
                          {item.grade_p1 || '-'}
                        </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                        <span className={`min-w-[24px] px-1 py-0.5 rounded text-[10px] font-bold border flex items-center justify-center ${item.grade_p2 ? 'bg-purple-50 text-purple-700 border-purple-100' : 'bg-gray-50 text-gray-400 border-gray-100 opacity-60'}`}>
                          {item.grade_p2 || '-'}
                        </span>
                    </td>
                    <td className="px-6 py-4 text-center text-gray-600">{item.bulan}</td>
                    <td className="px-6 py-4 text-center">
                      <span className={`px-3 py-1 rounded-full text-xs font-bold border ${getKehadiranBadge(item.kehadiran)}`}>
                        {item.kehadiran}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      {item.lembur && item.lembur !== '0' && item.lembur !== '-' ? (
                        <span className="bg-orange-50 text-orange-700 border border-orange-200 px-2 py-1 rounded text-xs font-bold">
                          {item.lembur}
                        </span>
                      ) : (
                        <span className="text-gray-400">-</span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-center text-gray-600">{item.periode}</td>
                    <td className="px-6 py-4 text-center text-gray-600">{item.perusahaan}</td>
                    <td className="px-6 py-4 text-gray-500 text-sm italic truncate max-w-[150px]">{item.keterangan}</td>
                    <td className="px-6 py-4 text-center">
                      <div className="flex justify-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button onClick={() => { setSelectedItem(item); setIsModalOpen(true); }} className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg border border-transparent hover:border-blue-100 transition-all" title="Edit">
                          <Edit2 size={16}/>
                        </button>
                        <button onClick={() => handleDelete(item.id)} className="p-2 text-red-600 hover:bg-red-50 rounded-lg border border-transparent hover:border-red-100 transition-all" title="Hapus">
                          <Trash2 size={16}/>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={13} className="p-16 text-center text-gray-400 bg-gray-50/30">
                    <div className="flex flex-col items-center justify-center gap-3">
                      <AlertCircle size={48} className="text-gray-200"/>
                      <p>Tidak ada data presensi ditemukan.</p>
                      <button onClick={() => setIsModalOpen(true)} className="text-erp-pink hover:underline text-sm font-medium">Tambah Data Baru</button>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        
        {/* --- PAGINATION --- */}
        <div className="p-4 border-t border-gray-200 bg-gray-50 flex flex-col sm:flex-row justify-between items-center gap-4 text-sm text-gray-600">
          <div className="flex items-center gap-2">
            <span>Menampilkan</span>
            <select
              value={pageSize}
              onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}
              className="border border-gray-300 rounded-lg py-1.5 px-2 bg-white focus:ring-2 focus:ring-erp-pink/50 outline-none cursor-pointer text-xs font-medium"
            >
              <option value="100">100</option>
              <option value="200">200</option>
              <option value="500">500</option>
              <option value="1000">1000</option>
            </select>
            <span>dari <b>{totalData.toLocaleString()}</b> data</span>
          </div>
          
          <div className="flex items-center gap-2">
            <button 
              onClick={() => setPage(prev => Math.max(prev - 1, 1))}
              disabled={page === 1 || isLoading}
              className="p-2 border border-gray-300 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors bg-white shadow-sm"
            >
              <ChevronLeft size={16} />
            </button>
            <span className="font-medium px-2">
              Halaman {page} / {Math.ceil(totalData / pageSize) || 1}
            </span>
            <button 
              onClick={() => setPage(prev => Math.min(prev + 1, Math.ceil(totalData / pageSize)))}
              disabled={page >= Math.ceil(totalData / pageSize) || isLoading}
              className="p-2 border border-gray-300 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors bg-white shadow-sm"
            >
              <ChevronRight size={16} />
            </button>
          </div>
        </div>
      </div>

      <AdnanHananAttendanceModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} onSubmit={handleSave} initialData={selectedItem} isLoading={false} />
      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      
      {/* CONFIRMATION MODAL */}
      <ConfirmationModal 
        isOpen={confirmModal.isOpen} 
        onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} 
        onConfirm={confirmModal.onConfirm} 
        title={confirmModal.title} 
        message={confirmModal.message} 
        confirmLabel={confirmModal.confirmLabel} 
        isDangerous={confirmModal.isDangerous !== undefined ? confirmModal.isDangerous : true}
        isLoading={confirmModal.isLoading} 
      />

      {/* SQL FIX MODAL */}
      {showSqlModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-blue-50">
              <h3 className="font-bold text-lg text-blue-800 flex items-center gap-2">
                <Database size={20}/> {sqlMode === 'create' ? 'Setup Database' : 'Perbaiki Database (Fix Trigger)'}
              </h3>
              <button onClick={() => setShowSqlModal(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-gray-600 text-sm mb-4">
                {sqlMode === 'create' 
                  ? 'Tabel database belum ditemukan. Silakan jalankan kode ini untuk membuat tabel.' 
                  : 'Terdeteksi masalah duplikasi data. Silakan jalankan kode ini untuk memperbaiki Trigger agar mendukung update otomatis (Upsert).'}
              </p>
              
              <div className="relative">
                <textarea 
                  className="w-full h-64 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-erp-pink outline-none"
                  readOnly
                  value={sqlMode === 'create' ? sqlCreateTable : sqlFixTrigger}
                  onClick={(e) => e.currentTarget.select()}
                />
                <button 
                  onClick={handleCopySQL}
                  className="absolute top-2 right-2 p-2 bg-white rounded-md shadow-sm border border-gray-200 hover:bg-gray-50 text-gray-600"
                  title="Salin Kode"
                >
                  <Copy size={16}/>
                </button>
              </div>

              <div className="mt-4 flex justify-end gap-3">
                <button 
                    onClick={() => setShowSqlModal(false)} 
                    className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm font-medium"
                >
                    Tutup
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
