import React, { useState, useEffect, useMemo } from 'react';
import { 
  Search, Loader2, RefreshCw, Download, Filter, X, Calendar, 
  Database, FileText, Calculator, Copy, Building2, Wallet, Users, Layers
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import * as XLSX from 'xlsx';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';

export const DailyRecap: React.FC = () => {
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [filterMonth, setFilterMonth] = useState('');
  const [filterPeriod, setFilterPeriod] = useState('Semua Periode');
  const [filterCompany, setFilterCompany] = useState('Semua Perusahaan');
  const [filterDivision, setFilterDivision] = useState('Semua Divisi');
  
  // Options
  const [uniqueMonths, setUniqueMonths] = useState<string[]>([]);
  const [uniqueCompanies, setUniqueCompanies] = useState<string[]>([]);
  const [uniqueDivisions, setUniqueDivisions] = useState<string[]>([]);

  // Pagination
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(100);
  const [totalData, setTotalData] = useState(0);

  // Grand Total State
  const [grandTotal, setGrandTotal] = useState(0);
  const [isCalculatingTotal, setIsCalculatingTotal] = useState(false);

  // Modals
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ isOpen: boolean; onConfirm: () => void; title: string; message: string; confirmLabel?: string }>({ isOpen: false, onConfirm: () => {}, title: '', message: '' });

  const formatRupiah = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(value);

  // SQL Setup Code
  const sqlSetupCode = `
-- 1. Tabel Rekap Gaji Harian (Gabungan)
CREATE TABLE IF NOT EXISTS public.rekap_gaji_harian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    grade TEXT,
    divisi TEXT,
    bulan TEXT,
    perusahaan TEXT,
    periode TEXT,
    keterangan TEXT,
    keluar_masuk TEXT,
    
    -- Komponen Gaji
    gaji_pokok NUMERIC DEFAULT 0,
    gaji_lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    uang_bonus NUMERIC DEFAULT 0,
    total_gaji NUMERIC DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_rekap_gaji_harian UNIQUE (tanggal, kode, periode, perusahaan)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_rekap_gaji_harian_bulan ON public.rekap_gaji_harian(bulan);
CREATE INDEX IF NOT EXISTS idx_rekap_gaji_harian_tanggal ON public.rekap_gaji_harian(tanggal);

-- RLS
ALTER TABLE public.rekap_gaji_harian ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Rekap" ON public.rekap_gaji_harian;
CREATE POLICY "Public Access Rekap" ON public.rekap_gaji_harian FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.rekap_gaji_harian TO anon, authenticated, service_role;

-- 2. Fungsi Generate Rekap (Mengambil dari 2 Sumber Read-Only)
CREATE OR REPLACE FUNCTION generate_rekap_gaji_harian(p_bulan TEXT)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_count_harian INT := 0;
    v_count_borongan INT := 0;
BEGIN
    -- Hapus data lama untuk bulan ini (agar bersih/replace)
    DELETE FROM public.rekap_gaji_harian WHERE bulan = p_bulan;

    -- A. Insert dari Gaji Harian Pabrik (Adnan & Hanan)
    INSERT INTO public.rekap_gaji_harian (
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        gaji_pokok, gaji_lembur, uang_makan, uang_kehadiran, uang_bonus, total_gaji
    )
    SELECT 
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        COALESCE(gaji_pokok, 0), 
        COALESCE(gaji_lembur, 0), 
        COALESCE(uang_makan, 0), 
        COALESCE(uang_kehadiran, 0), 
        COALESCE(uang_bonus, 0),
        COALESCE(gaji, 0) -- Total Gaji Harian
    FROM public.gaji_harian_pabrik_garut
    WHERE bulan = p_bulan;
    
    GET DIAGNOSTICS v_count_harian = ROW_COUNT;

    -- B. Insert dari Gaji Harian Borongan
    INSERT INTO public.rekap_gaji_harian (
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        gaji_pokok, gaji_lembur, uang_makan, uang_kehadiran, uang_bonus, total_gaji
    )
    SELECT 
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        COALESCE(gaji, 0), -- Gaji Borongan masuk ke Gaji Pokok di rekap
        0, -- Lembur 0
        0, -- Makan 0
        0, -- Hadir 0
        COALESCE(bonus, 0), -- Bonus Borongan
        (COALESCE(gaji, 0) + COALESCE(bonus, 0)) -- Total = Gaji + Bonus
    FROM public.gaji_harian_borongan_pabrik_garut
    WHERE bulan = p_bulan;

    GET DIAGNOSTICS v_count_borongan = ROW_COUNT;

    RETURN 'Rekap Berhasil. Harian: ' || v_count_harian || ', Borongan: ' || v_count_borongan;
END;
$$;

GRANT EXECUTE ON FUNCTION generate_rekap_gaji_harian(text) TO authenticated, service_role;
NOTIFY pgrst, 'reload config';
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlSetupCode);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
  };

  // --- FETCH OPTIONS ---
  useEffect(() => {
    const fetchOptions = async () => {
      if (!isSupabaseConfigured()) return;
      
      try {
        // 1. Ambil bulan dari tabel Rekap
        const { data: recapData } = await supabase
          .from('rekap_gaji_harian')
          .select('bulan, perusahaan, divisi');
        
        // 2. Ambil bulan dari tabel Sumber Gaji
        const { data: sourceHarian } = await supabase
          .from('gaji_harian_pabrik_garut')
          .select('bulan, perusahaan, divisi');
          
        const { data: sourceBorongan } = await supabase
          .from('gaji_harian_borongan_pabrik_garut')
          .select('bulan, perusahaan, divisi');

        // 3. NEW: Ambil bulan dari tabel Presensi (agar bulan muncul sebelum generate)
        const { data: presensiHarian } = await supabase
          .from('presensi_harian_pabrik_garut')
          .select('bulan, perusahaan');

        const { data: presensiBorongan } = await supabase
          .from('presensi_harian_borongan_pabrik_garut')
          .select('bulan, perusahaan');

        // Gabungkan semua bulan unik
        const allMonths = new Set<string>();
        const allCompanies = new Set<string>();
        const allDivisions = new Set<string>();
        
        const processData = (data: any[]) => {
            data?.forEach(d => {
                if (d.bulan) allMonths.add(d.bulan);
                if (d.perusahaan) allCompanies.add(d.perusahaan);
                if (d.divisi) allDivisions.add(d.divisi);
            });
        };

        processData(recapData || []);
        processData(sourceHarian || []);
        processData(sourceBorongan || []);
        processData(presensiHarian || []);
        processData(presensiBorongan || []);

        // Sort Bulan (Case Insensitive & Robust)
        const monthMap: Record<string, number> = {
            'januari': 1, 'februari': 2, 'maret': 3, 'april': 4, 'mei': 5, 'juni': 6,
            'juli': 7, 'agustus': 8, 'september': 9, 'oktober': 10, 'november': 11, 'desember': 12
        };

        const sortedMonths = Array.from(allMonths).sort((a, b) => {
            const partsA = a.trim().split(' ');
            const partsB = b.trim().split(' ');
            
            if (partsA.length < 2 || partsB.length < 2) return a.localeCompare(b);

            const yearA = parseInt(partsA[1]) || 0;
            const yearB = parseInt(partsB[1]) || 0;
            
            if (yearA !== yearB) return yearB - yearA; // Descending Year
            
            const monthNameA = partsA[0].toLowerCase();
            const monthNameB = partsB[0].toLowerCase();
            const valA = monthMap[monthNameA] || 0;
            const valB = monthMap[monthNameB] || 0;
            return valB - valA; // Descending Month
        });

        setUniqueMonths(sortedMonths);

        // Set Companies
        const sortedCompanies = Array.from(allCompanies).sort();
        setUniqueCompanies(sortedCompanies);

        // Set Divisions
        const sortedDivisions = Array.from(allDivisions).sort();
        setUniqueDivisions(sortedDivisions);

      } catch (e) {
        console.error("Error fetching options:", e);
      }
    };
    fetchOptions();
  }, []);

  // --- FETCH DATA (PAGINATED) ---
  const fetchData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    
    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      const from = (page - 1) * pageSize;
      const to = from + pageSize - 1;

      let query = supabase
        .from('rekap_gaji_harian')
        .select('*', { count: 'exact' });

      if (searchTerm) {
        query = query.or(`kode.ilike.%${searchTerm}%,nama.ilike.%${searchTerm}%`);
      }
      if (filterMonth) query = query.eq('bulan', filterMonth);
      if (filterPeriod && filterPeriod !== 'Semua Periode') query = query.eq('periode', filterPeriod);
      if (filterCompany && filterCompany !== 'Semua Perusahaan') query = query.eq('perusahaan', filterCompany);
      if (filterDivision && filterDivision !== 'Semua Divisi') query = query.eq('divisi', filterDivision);

      const { data: result, error, count } = await query
        .order('tanggal', { ascending: false })
        .order('nama', { ascending: true })
        .range(from, to);

      if (error) {
        if (error.code === '42P01' || error.code === 'PGRST205' || error.message.includes('does not exist')) {
          setIsTableMissing(true);
        } else {
          throw error;
        }
      } else {
        setData(result || []);
        setTotalData(count || 0);
      }
    } catch (error: any) {
      console.error("Fetch error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [page, pageSize, searchTerm, filterMonth, filterPeriod, filterCompany, filterDivision]);

  // --- FETCH GRAND TOTAL (ALL DATA) ---
  useEffect(() => {
    const fetchGrandTotal = async () => {
        if (!isSupabaseConfigured()) return;
        setIsCalculatingTotal(true);
        
        try {
            let totalSum = 0;
            let from = 0;
            const step = 1000;
            let hasMore = true;

            while (hasMore) {
                let query = supabase
                    .from('rekap_gaji_harian')
                    .select('total_gaji');

                if (searchTerm) {
                    query = query.or(`kode.ilike.%${searchTerm}%,nama.ilike.%${searchTerm}%`);
                }
                if (filterMonth) query = query.eq('bulan', filterMonth);
                if (filterPeriod && filterPeriod !== 'Semua Periode') query = query.eq('periode', filterPeriod);
                if (filterCompany && filterCompany !== 'Semua Perusahaan') query = query.eq('perusahaan', filterCompany);
                if (filterDivision && filterDivision !== 'Semua Divisi') query = query.eq('divisi', filterDivision);

                const { data: batch, error } = await query.range(from, from + step - 1);
                
                if (error) throw error;

                if (batch && batch.length > 0) {
                    const batchSum = batch.reduce((sum, item) => sum + (Number(item.total_gaji) || 0), 0);
                    totalSum += batchSum;
                    
                    if (batch.length < step) hasMore = false;
                    else from += step;
                } else {
                    hasMore = false;
                }
            }
            setGrandTotal(totalSum);
        } catch (error) {
            console.error("Error calculating grand total:", error);
        } finally {
            setIsCalculatingTotal(false);
        }
    };

    // Debounce total calculation
    const timer = setTimeout(() => {
        fetchGrandTotal();
    }, 500);
    return () => clearTimeout(timer);

  }, [searchTerm, filterMonth, filterPeriod, filterCompany, filterDivision]);

  // --- GENERATE RECAP ---
  const handleGenerate = () => {
    if (!filterMonth) {
        alert("Silakan pilih bulan terlebih dahulu.");
        return;
    }

    setConfirmModal({
        isOpen: true,
        title: 'Generate Rekap Gaji?',
        message: `Sistem akan mengambil data terbaru dari Gaji Harian & Borongan untuk bulan **${filterMonth}** dan menggabungkannya ke tabel rekap.\n\nData lama di tabel rekap untuk bulan ini akan ditimpa.`,
        confirmLabel: 'Ya, Generate',
        onConfirm: executeGenerate
    });
  };

  const executeGenerate = async () => {
    setConfirmModal({ ...confirmModal, isOpen: false });
    setIsGenerating(true);
    
    try {
        const { data: msg, error } = await supabase.rpc('generate_rekap_gaji_harian', { p_bulan: filterMonth });
        
        if (error) {
            if (error.message.includes('function') || error.code === '42883') {
                setShowSqlModal(true);
                throw new Error("Fungsi database belum dibuat. Silakan setup database.");
            }
            throw error;
        }

        setSuccessModal({ isOpen: true, title: 'Berhasil', message: msg || 'Rekap gaji berhasil dibuat.' });
        fetchData();
    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Generate', message: error.message });
    } finally {
        setIsGenerating(false);
    }
  };

  // --- EXPORT ---
  const handleExport = async () => {
    setIsLoading(true);
    try {
        let allData: any[] = [];
        let from = 0;
        const step = 1000;
        let hasMore = true;

        while (hasMore) {
            let query = supabase.from('rekap_gaji_harian').select('*');
            
            if (searchTerm) query = query.or(`kode.ilike.%${searchTerm}%,nama.ilike.%${searchTerm}%`);
            if (filterMonth) query = query.eq('bulan', filterMonth);
            if (filterPeriod && filterPeriod !== 'Semua Periode') query = query.eq('periode', filterPeriod);
            if (filterCompany && filterCompany !== 'Semua Perusahaan') query = query.eq('perusahaan', filterCompany);
            if (filterDivision && filterDivision !== 'Semua Divisi') query = query.eq('divisi', filterDivision);

            // FIX: Added deterministic sorting to prevent duplicates/missing rows in pagination
            const { data: batch, error } = await query
                .order('tanggal', { ascending: false })
                .order('nama', { ascending: true })
                .order('id', { ascending: true })
                .range(from, from + step - 1);
            
            if (error) throw error;

            if (batch && batch.length > 0) {
                allData = [...allData, ...batch];
                if (batch.length < step) hasMore = false;
                else from += step;
            } else {
                hasMore = false;
            }
        }

        if (allData.length === 0) {
            alert("Tidak ada data untuk diexport.");
            return;
        }
        
        const exportData = allData.map(item => ({
            'Tanggal': item.tanggal,
            'Bulan': item.bulan,
            'Kode': item.kode,
            'Nama': item.nama,
            'Perusahaan': item.perusahaan,
            'Divisi': item.divisi,
            'Grade': item.grade,
            'Periode': item.periode,
            'Gaji Pokok': item.gaji_pokok,
            'Lembur': item.gaji_lembur,
            'Uang Makan': item.uang_makan,
            'Uang Hadir': item.uang_kehadiran,
            'Bonus': item.uang_bonus,
            'Total Gaji': item.total_gaji,
            'Keterangan': item.keterangan
        }));

        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.json_to_sheet(exportData);
        XLSX.utils.book_append_sheet(wb, ws, "Rekap Gaji");
        XLSX.writeFile(wb, `Rekap_Gaji_Harian_${filterMonth || 'All'}.xlsx`);
    } catch (error: any) {
        alert(`Gagal Export: ${error.message}`);
    } finally {
        setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6 h-full flex flex-col font-sans">
      {/* --- HEADER & TOOLBAR --- */}
      <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 mb-4">
            <div>
                <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
                    <FileText className="text-erp-pink"/> Rekap Gaji Harian (Gabungan)
                </h3>
                <p className="text-xs text-gray-500">Laporan dan rekapitulasi pembayaran gaji harian.</p>
            </div>
            <div className="flex gap-2">
                {isTableMissing && (
                    <button onClick={() => setShowSqlModal(true)} className="px-3 py-2 bg-red-50 text-red-600 border border-red-200 rounded-lg text-sm font-bold flex items-center gap-2 animate-pulse">
                        <Database size={16}/> Setup DB
                    </button>
                )}
                
                <button 
                    onClick={handleGenerate} 
                    disabled={isGenerating || !filterMonth}
                    className="px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 shadow-sm flex items-center gap-2 text-sm font-medium transition-colors disabled:opacity-50"
                >
                    {isGenerating ? <Loader2 className="animate-spin" size={16}/> : <Calculator size={16}/>}
                    Generate Rekap
                </button>

                <button onClick={handleExport} className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-green-700 shadow-sm transition-colors">
                    <Download size={16}/> Export Excel
                </button>
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                <input 
                    type="text" 
                    placeholder="Cari Nama / Kode..." 
                    value={searchTerm} 
                    onChange={e => setSearchTerm(e.target.value)} 
                    className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-erp-pink" 
                />
            </div>
            
            <select value={filterMonth} onChange={e => setFilterMonth(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="">Semua Bulan</option>
                {uniqueMonths.map(m => <option key={m} value={m}>{m}</option>)}
            </select>

            <select value={filterPeriod} onChange={e => setFilterPeriod(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="Semua Periode">Semua Periode</option>
                <option value="Periode 1">Periode 1</option>
                <option value="Periode 2">Periode 2</option>
            </select>

            <select value={filterCompany} onChange={e => setFilterCompany(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="Semua Perusahaan">Semua Perusahaan</option>
                {uniqueCompanies.map(c => <option key={c} value={c}>{c}</option>)}
            </select>

            <select value={filterDivision} onChange={e => setFilterDivision(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="Semua Divisi">Semua Divisi</option>
                {uniqueDivisions.map(d => <option key={d} value={d}>{d}</option>)}
            </select>
        </div>
      </div>

      {/* --- SUMMARY --- */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-blue-50 border border-blue-200 p-4 rounded-xl shadow-sm">
             <p className="text-xs text-blue-600 font-bold uppercase">Total Data</p>
             <p className="text-2xl font-bold text-blue-800">{totalData} Baris</p>
          </div>
          <div className="bg-green-50 border border-green-200 p-4 rounded-xl shadow-sm">
             <p className="text-xs text-green-600 font-bold uppercase">Grand Total</p>
             <div className="text-2xl font-bold text-green-800">
                {isCalculatingTotal ? <Loader2 className="animate-spin" size={24}/> : formatRupiah(grandTotal)}
             </div>
          </div>
      </div>

      {/* --- TABLE --- */}
      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm flex-1 flex flex-col min-h-0">
        <div className="overflow-auto max-h-[600px] custom-scrollbar relative">
          <table className="w-full text-xs text-left whitespace-nowrap relative border-collapse">
            <thead className="bg-gray-100 text-gray-600 font-bold sticky top-0 z-10 shadow-sm uppercase text-[10px] tracking-wider">
              <tr>
                <th className="px-4 py-3 text-center w-10">No</th>
                <th className="px-4 py-3">Tanggal</th>
                <th className="px-4 py-3">Bulan</th>
                <th className="px-4 py-3">Kode</th>
                <th className="px-4 py-3">Divisi</th>
                <th className="px-4 py-3">Perusahaan</th>
                <th className="px-4 py-3 text-center">Grade</th>
                <th className="px-4 py-3 text-right bg-blue-50 text-blue-800">Gaji Pokok</th>
                <th className="px-4 py-3 text-right bg-orange-50 text-orange-800">Lembur</th>
                <th className="px-4 py-3 text-right bg-green-50 text-green-800">Makan</th>
                <th className="px-4 py-3 text-right bg-green-50 text-green-800">Hadir</th>
                <th className="px-4 py-3 text-right bg-purple-50 text-purple-800">Bonus</th>
                <th className="px-4 py-3 text-right bg-gray-200 text-gray-900 font-bold border-l border-gray-300">Total</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {isLoading ? (
                <tr><td colSpan={13} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat data...</td></tr>
              ) : isTableMissing ? (
                <tr><td colSpan={13} className="p-12 text-center text-red-500">Tabel rekap belum dibuat. Klik "Setup DB".</td></tr>
              ) : data.length > 0 ? (
                data.map((item, idx) => (
                  <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-4 py-2 text-center text-gray-500">{idx + 1 + ((page - 1) * pageSize)}</td>
                    <td className="px-4 py-2 text-gray-700">{item.tanggal}</td>
                    <td className="px-4 py-2 text-gray-700">{item.bulan}</td>
                    <td className="px-4 py-2 font-mono text-gray-600">{item.kode}</td>
                    <td className="px-4 py-2 font-medium text-gray-900">{item.divisi || '-'}</td>
                    <td className="px-4 py-2 text-gray-600 text-[10px]">{item.perusahaan}</td>
                    <td className="px-4 py-2 text-center text-blue-600 font-bold">{item.grade || '-'}</td>
                    
                    <td className="px-4 py-2 text-right bg-blue-50/30">{formatRupiah(item.gaji_pokok)}</td>
                    <td className="px-4 py-2 text-right bg-orange-50/30">{formatRupiah(item.gaji_lembur)}</td>
                    <td className="px-4 py-2 text-right bg-green-50/30">{formatRupiah(item.uang_makan)}</td>
                    <td className="px-4 py-2 text-right bg-green-50/30">{formatRupiah(item.uang_kehadiran)}</td>
                    <td className="px-4 py-2 text-right bg-purple-50/30">{formatRupiah(item.uang_bonus)}</td>
                    <td className="px-4 py-2 text-right font-bold bg-gray-100/50 border-l border-gray-100">{formatRupiah(item.total_gaji)}</td>
                  </tr>
                ))
              ) : (
                <tr><td colSpan={13} className="p-16 text-center text-gray-400 italic">Tidak ada data rekap. Klik "Generate Rekap" untuk membuat laporan.</td></tr>
              )}
            </tbody>
          </table>
        </div>
        
        {/* Pagination */}
        <div className="p-4 border-t border-gray-200 bg-gray-50 flex justify-between items-center text-xs text-gray-500">
            <span>Total Data: {totalData}</span>
            <div className="flex gap-2">
                <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="px-3 py-1 bg-white border rounded hover:bg-gray-100 disabled:opacity-50">Prev</button>
                <span className="px-2 py-1">Page {page}</span>
                <button onClick={() => setPage(p => p + 1)} disabled={data.length < pageSize} className="px-3 py-1 bg-white border rounded hover:bg-gray-100 disabled:opacity-50">Next</button>
            </div>
        </div>
      </div>

      {/* SQL Modal */}
      {showSqlModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-blue-50">
              <h3 className="font-bold text-lg text-blue-800 flex items-center gap-2">
                <Database size={20}/> Setup Database Rekap
              </h3>
              <button onClick={() => setShowSqlModal(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-gray-600 text-sm mb-4">
                Tabel atau fungsi rekap belum ditemukan. Salin kode SQL di bawah ini dan jalankan di <b>Supabase SQL Editor</b>.
              </p>
              <div className="relative">
                <textarea 
                  className="w-full h-64 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-erp-pink outline-none"
                  readOnly
                  value={sqlSetupCode}
                  onClick={(e) => e.currentTarget.select()}
                />
                <button 
                  onClick={handleCopySQL}
                  className="absolute top-2 right-2 p-2 bg-white rounded-md shadow-sm border border-gray-200 hover:bg-gray-50 text-gray-600"
                  title="Salin Kode"
                >
                  <Copy size={16}/>
                </button>
              </div>
              <div className="mt-4 flex justify-end gap-3">
                <button onClick={() => setShowSqlModal(false)} className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm font-medium">Tutup</button>
              </div>
            </div>
          </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal isOpen={confirmModal.isOpen} onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} onConfirm={confirmModal.onConfirm} title={confirmModal.title} message={confirmModal.message} confirmLabel={confirmModal.confirmLabel} />
    </div>
  );
};
