import React, { useState, useEffect, useRef, useMemo } from 'react';
import { Search, Plus, Edit2, Trash2, Loader2, Database, Copy, RefreshCw, Filter, X, Download, Upload, FileSpreadsheet } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import { MasterSalaryModal } from './MasterSalaryModal';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';
import * as XLSX from 'xlsx';

export const MasterSalary: React.FC = () => {
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  
  // --- FILTER STATE ---
  const [searchTerm, setSearchTerm] = useState('');
  const [filterMonth, setFilterMonth] = useState('');
  const [filterGrade, setFilterGrade] = useState('');

  // --- SELECTION STATE ---
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isSaving, setIsSaving] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ isOpen: boolean; title: string; message: string; onConfirm: () => void; isDangerous?: boolean }>({ isOpen: false, title: '', message: '', onConfirm: () => {} });

  const formatRupiah = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(value);

  // Updated SQL Fix Code to include CREATE TABLE for robustness
  const sqlFixCode = `
-- 1. Ensure the table exists first (Robust Fix)
CREATE TABLE IF NOT EXISTS public.master_gaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    grade TEXT,
    gaji_pokok NUMERIC DEFAULT 0,
    gaji_harian NUMERIC DEFAULT 0,
    gaji_setengah_hari NUMERIC DEFAULT 0,
    gaji_per_jam NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_makan_harian NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    uang_kehadiran_harian NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure columns exist (Double check for existing tables)
ALTER TABLE public.master_gaji ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.master_gaji ADD COLUMN IF NOT EXISTS bonus NUMERIC DEFAULT 0;

-- 3. Enable RLS and Policies
ALTER TABLE public.master_gaji ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "Public Access Gaji" ON public.master_gaji;
    CREATE POLICY "Public Access Gaji" ON public.master_gaji FOR ALL USING (true) WITH CHECK (true);
END $$;

GRANT ALL ON public.master_gaji TO anon, authenticated, service_role;

-- 4. Refresh the schema cache
NOTIFY pgrst, 'reload config';
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlFixCode);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
  };

  const fetchData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    setSelectedIds([]); // Reset selection saat refresh
    
    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      const { data: result, error } = await supabase.from('master_gaji').select('*').order('id', { ascending: false });
      if (error) {
        if (error.code === '42P01' || error.message.includes('does not exist')) {
          setIsTableMissing(true);
        }
        setData([]);
      } else {
        setData(result || []);
      }
    } catch (error) {
      console.warn("Unexpected error (Silent):", error);
      setData([]);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, []);

  // --- UNIQUE VALUES FOR FILTERS ---
  const uniqueMonths = useMemo(() => {
    const months = data.map(item => item.bulan).filter(Boolean);
    return [...new Set(months)].sort();
  }, [data]);

  const uniqueGrades = useMemo(() => {
    const grades = data.map(item => item.grade).filter(Boolean);
    return [...new Set(grades)].sort();
  }, [data]);

  // --- FILTERING LOGIC ---
  const filteredData = useMemo(() => {
    return data.filter(item => {
      const matchesSearch = (item.bulan || '').toLowerCase().includes(searchTerm.toLowerCase()) || 
                            (item.grade || '').toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesMonth = filterMonth === '' || item.bulan === filterMonth;
      const matchesGrade = filterGrade === '' || item.grade === filterGrade;

      return matchesSearch && matchesMonth && matchesGrade;
    });
  }, [data, searchTerm, filterMonth, filterGrade]);

  const handleResetFilter = () => {
    setSearchTerm('');
    setFilterMonth('');
    setFilterGrade('');
  };

  // --- SELECTION LOGIC ---
  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      setSelectedIds(filteredData.map(item => item.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelectOne = (id: number) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(prev => prev.filter(item => item !== id));
    } else {
      setSelectedIds(prev => [...prev, id]);
    }
  };

  const isAllSelected = filteredData.length > 0 && selectedIds.length === filteredData.length;
  const isIndeterminate = selectedIds.length > 0 && selectedIds.length < filteredData.length;

  // --- CRUD HANDLERS ---
  const handleSave = async (formData: any) => {
    setIsSaving(true);
    try {
      if (selectedItem) {
        await supabase.from('master_gaji').update(formData).eq('id', selectedItem.id);
      } else {
        await supabase.from('master_gaji').insert([formData]);
      }
      setIsModalOpen(false);
      fetchData();
      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data tersimpan.' });
    } catch (error: any) {
      setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Data',
      message: 'Yakin ingin menghapus data ini?',
      isDangerous: true,
      onConfirm: async () => {
        await supabase.from('master_gaji').delete().eq('id', id);
        fetchData();
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
      }
    });
  };

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Massal',
      message: `Hapus ${selectedIds.length} data terpilih?`,
      isDangerous: true,
      onConfirm: async () => {
        await supabase.from('master_gaji').delete().in('id', selectedIds);
        fetchData();
        setSelectedIds([]);
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
      }
    });
  };

  // --- IMPORT / EXPORT / TEMPLATE ---

  const handleDownloadTemplate = () => {
    const templateData = [
      { 
        'Bulan': 'Oktober 2025', 
        'Grade': 'A', 
        'Gapok 1 Bulan': 5000000, 
        'Lembur': 25000, 
        'Uang Makan': 500000, 
        'Uang Kehadiran': 300000, 
        'Bonus': 1000000 
      },
      { 
        'Bulan': 'Oktober 2025', 
        'Grade': 'B', 
        'Gapok 1 Bulan': 4000000, 
        'Lembur': 20000, 
        'Uang Makan': 400000, 
        'Uang Kehadiran': 250000, 
        'Bonus': 500000 
      }
    ];
    const ws = XLSX.utils.json_to_sheet(templateData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, "Template_Master_Gaji.xlsx");
  };

  const handleExport = () => {
    if (filteredData.length === 0) {
      alert("Tidak ada data untuk diexport.");
      return;
    }
    
    const exportData = filteredData.map(item => ({
      'Bulan': item.bulan,
      'Grade': item.grade,
      'Gapok (Bulan)': item.gaji_pokok,
      'Gapok (Hari)': item.gaji_harian,
      'Gapok (Jam)': item.gaji_per_jam,
      'Lembur': item.lembur,
      'Uang Makan (Bulan)': item.uang_makan,
      'Uang Makan (Hari)': item.uang_makan_harian,
      'Uang Kehadiran (Bulan)': item.uang_kehadiran,
      'Uang Kehadiran (Hari)': item.uang_kehadiran_harian,
      'Bonus': item.bonus
    }));

    const ws = XLSX.utils.json_to_sheet(exportData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Master Gaji");
    XLSX.writeFile(wb, `Master_Gaji_${new Date().toISOString().slice(0, 10)}.xlsx`);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (evt) => {
      const bstr = evt.target?.result;
      const wb = XLSX.read(bstr, { type: 'array' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const jsonData = XLSX.utils.sheet_to_json(ws);

      if (jsonData.length === 0) {
        setErrorModal({ isOpen: true, title: 'File Kosong', message: 'File Excel tidak memiliki data.' });
        return;
      }

      setIsLoading(true);
      try {
        const processedData = jsonData.map((row: any) => {
          const gapok = Number(row['Gapok 1 Bulan'] || row['Gaji Pokok'] || 0);
          const makan = Number(row['Uang Makan'] || 0);
          const hadir = Number(row['Uang Kehadiran'] || 0);

          // Hitung Otomatis
          const gapok26 = Math.round(gapok / 26);
          
          return {
            bulan: row['Bulan'],
            grade: row['Grade'],
            gaji_pokok: gapok,
            gaji_harian: gapok26,
            gaji_setengah_hari: Math.round(gapok26 / 2),
            gaji_per_jam: Math.round(gapok26 / 8),
            lembur: Number(row['Lembur'] || 0),
            uang_makan: makan,
            uang_makan_harian: Math.round(makan / 26),
            uang_kehadiran: hadir,
            uang_kehadiran_harian: Math.round(hadir / 26),
            bonus: Number(row['Bonus'] || 0),
            updated_at: new Date().toISOString()
          };
        });

        const { error } = await supabase.from('master_gaji').insert(processedData);
        
        if (error) throw error;

        setSuccessModal({ 
          isOpen: true, 
          title: 'Import Berhasil', 
          message: `Berhasil mengimport ${processedData.length} data gaji.` 
        });
        fetchData();
      } catch (error: any) {
        // CATCH ERROR CODE 42P01 (Table undefined) OR Missing Columns
        if (error.code === '42P01' || error.message?.includes('does not exist') || error.message?.includes('updated_at') || error.message?.includes('schema cache')) {
            setIsTableMissing(true); // Ini akan memunculkan tombol "Salin Kode SQL"
            setErrorModal({ 
                isOpen: true, 
                title: 'Struktur Database Belum Update', 
                message: 'Tabel "master_gaji" belum ada atau strukturnya tidak sesuai. Silakan klik tombol "Salin Kode SQL" yang muncul di layar dan jalankan di Supabase.' 
            });
        } else {
            setErrorModal({ isOpen: true, title: 'Gagal Import', message: error.message });
        }
      } finally {
        setIsLoading(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  return (
    <div className="space-y-6 h-full flex flex-col">
      <input type="file" ref={fileInputRef} onChange={handleImport} className="hidden" accept=".xlsx, .xls" />

      {/* --- TOOLBAR --- */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 shrink-0">
        <div className="relative w-full md:w-72">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
          <input 
            type="text" 
            placeholder="Cari..." 
            value={searchTerm} 
            onChange={e => setSearchTerm(e.target.value)} 
            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-erp-pink/50 shadow-sm" 
          />
        </div>
        <div className="flex flex-wrap gap-2 w-full md:w-auto justify-end">
          {selectedIds.length > 0 && (
            <button 
              onClick={handleBulkDelete} 
              className="bg-red-100 text-red-600 px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-medium hover:bg-red-200 transition-colors animate-fadeIn"
            >
              <Trash2 size={16}/> Hapus ({selectedIds.length})
            </button>
          )}
          
          <button onClick={handleDownloadTemplate} className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm flex items-center gap-2 text-sm font-medium">
            <FileSpreadsheet size={16}/> Template
          </button>
          <button onClick={() => fileInputRef.current?.click()} className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm flex items-center gap-2 text-sm font-medium">
            <Upload size={16}/> Import
          </button>
          <button onClick={handleExport} className="px-3 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 shadow-sm flex items-center gap-2 text-sm font-medium transition-colors">
            <Download size={16}/> Export
          </button>

          <button onClick={fetchData} className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm" title="Refresh">
            <RefreshCw size={16}/>
          </button>
          <button onClick={() => { setSelectedItem(null); setIsModalOpen(true); }} className="bg-erp-pink text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-medium hover:bg-pink-600 shadow-md shadow-pink-200 transition-colors">
            <Plus size={16}/> Tambah
          </button>
        </div>
      </div>

      {/* --- FILTER SECTION --- */}
      <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm grid grid-cols-1 md:grid-cols-12 gap-4 items-end">
        <div className="col-span-1 md:col-span-12 flex items-center gap-2 text-sm font-bold text-erp-pink mb-1">
          <Filter size={18}/> Filter Data
        </div>
        
        <div className="col-span-1 md:col-span-4">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Bulan</label>
          <select 
            value={filterMonth} 
            onChange={(e) => setFilterMonth(e.target.value)} 
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
          >
            <option value="">Semua Bulan</option>
            {uniqueMonths.map(m => (
              <option key={m} value={m}>{m}</option>
            ))}
          </select>
        </div>

        <div className="col-span-1 md:col-span-4">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Grade</label>
          <select 
            value={filterGrade} 
            onChange={(e) => setFilterGrade(e.target.value)} 
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
          >
            <option value="">Semua Grade</option>
            {uniqueGrades.map(g => (
              <option key={g} value={g}>{g}</option>
            ))}
          </select>
        </div>

        <div className="col-span-1 md:col-span-4">
          <button 
            onClick={handleResetFilter} 
            className="w-full px-4 py-2.5 bg-gray-100 text-gray-600 rounded-xl text-sm font-medium hover:bg-gray-200 hover:text-gray-800 flex items-center justify-center gap-2 transition-colors"
          >
            <X size={18} /> Reset Filter
          </button>
        </div>
      </div>

      {/* --- TABLE SECTION --- */}
      {isTableMissing ? (
        <div className="flex-1 flex flex-col items-center justify-center bg-red-50 border border-red-200 rounded-xl p-8 text-center">
          <Database size={48} className="text-red-400 mb-4" />
          <h3 className="text-xl font-bold text-red-800 mb-2">Tabel Belum Siap / Kolom Hilang</h3>
          <p className="text-red-600 mb-4 text-sm">Struktur tabel <code>master_gaji</code> tidak sesuai (mungkin kolom <code>updated_at</code> hilang atau tabel belum dibuat).</p>
          <button onClick={handleCopySQL} className="bg-red-600 text-white px-6 py-3 rounded-lg font-medium flex items-center gap-2 hover:bg-red-700 transition-colors shadow-lg">
            <Copy size={18} /> Salin Kode SQL Perbaikan
          </button>
        </div>
      ) : (
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm flex-1 flex flex-col min-h-0">
          <div className="overflow-auto max-h-[600px] custom-scrollbar relative">
            <table className="w-full text-sm text-left whitespace-nowrap relative border-collapse">
              <thead className="bg-gray-50 text-gray-600 font-medium border-b border-gray-200 sticky top-0 z-10 shadow-sm">
                <tr>
                  <th className="px-4 py-4 w-10 text-center">
                    <input 
                      type="checkbox" 
                      className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                      checked={isAllSelected}
                      ref={input => { if (input) input.indeterminate = isIndeterminate; }}
                      onChange={handleSelectAll}
                    />
                  </th>
                  <th className="px-6 py-4">Bulan</th>
                  <th className="px-6 py-4">Grade</th>
                  
                  {/* GAPOK GROUP */}
                  <th className="px-6 py-4">Gapok</th>
                  <th className="px-6 py-4 bg-blue-50/30 text-blue-800 border-l border-blue-100">Per Hari</th>
                  <th className="px-6 py-4 bg-blue-50/30 text-blue-800">Per Jam</th>
                  
                  <th className="px-6 py-4">Lembur</th>
                  
                  {/* UANG MAKAN GROUP */}
                  <th className="px-6 py-4">Uang Makan</th>
                  <th className="px-6 py-4 bg-orange-50/30 text-orange-800 border-l border-orange-100">Per Hari</th>
                  
                  {/* UANG KEHADIRAN GROUP */}
                  <th className="px-6 py-4">Uang Kehadiran</th>
                  <th className="px-6 py-4 bg-green-50/30 text-green-800 border-l border-green-100">Per Hari</th>
                  
                  <th className="px-6 py-4 font-bold text-gray-700">Bonus</th>
                  <th className="px-6 py-4 text-center">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {isLoading ? (
                  <tr><td colSpan={13} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat...</td></tr>
                ) : filteredData.length > 0 ? (
                  filteredData.map((item) => (
                    <tr key={item.id} className={`hover:bg-gray-50 transition-colors ${selectedIds.includes(item.id) ? 'bg-pink-50/30' : ''}`}>
                      <td className="px-4 py-4 text-center">
                        <input 
                          type="checkbox" 
                          className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                          checked={selectedIds.includes(item.id)}
                          onChange={() => handleSelectOne(item.id)}
                        />
                      </td>
                      <td className="px-6 py-4">{item.bulan}</td>
                      <td className="px-6 py-4 font-bold text-gray-800">{item.grade}</td>
                      
                      {/* GAPOK DATA */}
                      <td className="px-6 py-4">{formatRupiah(item.gaji_pokok)}</td>
                      <td className="px-6 py-4 bg-blue-50/30 border-l border-blue-50 text-gray-600">{formatRupiah(item.gaji_harian)}</td>
                      <td className="px-6 py-4 bg-blue-50/30 text-gray-600">{formatRupiah(item.gaji_per_jam)}</td>
                      
                      <td className="px-6 py-4">{formatRupiah(item.lembur)}</td>
                      
                      {/* MAKAN DATA */}
                      <td className="px-6 py-4">{formatRupiah(item.uang_makan)}</td>
                      <td className="px-6 py-4 bg-orange-50/30 border-l border-orange-50 text-gray-600">{formatRupiah(item.uang_makan_harian)}</td>
                      
                      {/* KEHADIRAN DATA */}
                      <td className="px-6 py-4">{formatRupiah(item.uang_kehadiran)}</td>
                      <td className="px-6 py-4 bg-green-50/30 border-l border-green-50 text-gray-600">{formatRupiah(item.uang_kehadiran_harian)}</td>
                      
                      <td className="px-6 py-4 font-medium text-green-600">{formatRupiah(item.bonus)}</td>
                      
                      <td className="px-6 py-4 text-center">
                        <div className="flex justify-center gap-2">
                          <button onClick={() => { setSelectedItem(item); setIsModalOpen(true); }} className="p-1.5 text-blue-600 hover:bg-blue-50 rounded border border-transparent hover:border-blue-100 transition-all"><Edit2 size={16}/></button>
                          <button onClick={() => handleDelete(item.id)} className="p-1.5 text-red-600 hover:bg-red-50 rounded border border-transparent hover:border-red-100 transition-all"><Trash2 size={16}/></button>
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr><td colSpan={13} className="p-12 text-center text-gray-500 italic">Tidak ada data gaji yang cocok dengan filter.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <MasterSalaryModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} onSubmit={handleSave} initialData={selectedItem} isLoading={isSaving} />
      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal isOpen={confirmModal.isOpen} onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} onConfirm={confirmModal.onConfirm} title={confirmModal.title} message={confirmModal.message} isDangerous={confirmModal.isDangerous} />
    </div>
  );
};
