import React, { useState, useEffect, useMemo } from 'react';
import { 
  Calendar, Save, Loader2, Filter, Search, CheckCircle2, AlertCircle, Database, Copy, X, RefreshCw, RotateCcw, Trash2
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';

interface StaffAttendanceInputState {
  [key: string]: {
    kehadiran: string;
    lembur: string;
    keterangan: string;
  };
}

export const StaffDailyAttendanceInput: React.FC = () => {
  // Filters
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [selectedMonth, setSelectedMonth] = useState('');
  
  // Data
  const [employees, setEmployees] = useState<any[]>([]);
  const [availableMonths, setAvailableMonths] = useState<string[]>([]);
  const [inputState, setInputState] = useState<StaffAttendanceInputState>({});
  
  // UI State
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusMessage, setStatusMessage] = useState<{type: 'success'|'error'|'info', text: string} | null>(null);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [showSql, setShowSql] = useState(false); // State for SQL Fallback Modal
  const [showResetSql, setShowResetSql] = useState(false); // State for DROP TABLE SQL

  // Modals
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });

  // SQL Setup - UPDATED FOR UPSERT SUPPORT & MISSING COLUMNS (DIRECT ALTER TABLE)
  const sqlSetupCode = `
-- [FIX V7] FORCE UPDATE SCHEMA STRUCTURE (ADD DIVISI)
-- Jalankan script ini di Supabase SQL Editor untuk memperbaiki error "Column not found"

-- 1. Buat tabel dasar jika belum ada
CREATE TABLE IF NOT EXISTS public.presensi_harian_staff_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tambahkan kolom wajib secara EKSPLISIT (Tanpa DO Block agar lebih reliable)
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS nama TEXT;
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS grade TEXT;
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS bulan TEXT;
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS perusahaan TEXT;
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS divisi TEXT; -- ADDED DIVISI
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS kehadiran TEXT;
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS lembur TEXT;
ALTER TABLE public.presensi_harian_staff_pabrik ADD COLUMN IF NOT EXISTS keterangan TEXT;

-- 3. Constraint Unik (WAJIB UNTUK UPSERT)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_staff_harian') THEN
        ALTER TABLE public.presensi_harian_staff_pabrik 
        ADD CONSTRAINT unique_staff_harian UNIQUE (tanggal, kode);
    END IF;
END $$;

-- 4. Security Policies
ALTER TABLE public.presensi_harian_staff_pabrik ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "Public Access Staff Presensi" ON public.presensi_harian_staff_pabrik;
    CREATE POLICY "Public Access Staff Presensi" ON public.presensi_harian_staff_pabrik FOR ALL USING (true) WITH CHECK (true);
END $$;

GRANT ALL ON public.presensi_harian_staff_pabrik TO anon, authenticated, service_role;

-- 5. Refresh Cache
NOTIFY pgrst, 'reload config';
  `;

  const sqlResetCode = `
-- [DANGER] RESET TABLE SCRIPT
-- Gunakan ini jika script update biasa tidak berhasil
DROP TABLE IF EXISTS public.presensi_harian_staff_pabrik CASCADE;

CREATE TABLE public.presensi_harian_staff_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    grade TEXT,
    bulan TEXT,
    perusahaan TEXT,
    divisi TEXT,
    kehadiran TEXT,
    lembur TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_staff_harian UNIQUE (tanggal, kode)
);

ALTER TABLE public.presensi_harian_staff_pabrik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Staff Presensi" ON public.presensi_harian_staff_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.presensi_harian_staff_pabrik TO anon, authenticated, service_role;
NOTIFY pgrst, 'reload config';
  `;

  const handleCopySQL = async (code: string) => {
    try {
      await navigator.clipboard.writeText(code);
      setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan di SQL Editor Supabase.' });
    } catch (err) {
      // Fallback if clipboard fails
      setShowSql(true);
    }
  };

  // 1. Fetch Available Months
  useEffect(() => {
    const fetchMonths = async () => {
      const { data } = await supabase
        .from('data_karyawan_staff_pabrik')
        .select('bulan')
        .order('created_at', { ascending: false });
      
      if (data) {
        const months = [...new Set(data.map(d => d.bulan))].filter(Boolean);
        setAvailableMonths(months);
        if (months.length > 0 && !selectedMonth) {
          const currentMonthName = new Date().toLocaleString('id-ID', { month: 'long', year: 'numeric' });
          const match = months.find(m => m.toLowerCase() === currentMonthName.toLowerCase());
          setSelectedMonth(match || months[0]);
        }
      }
    };
    fetchMonths();
  }, []);

  // 2. Fetch Employees
  useEffect(() => {
    if (!selectedMonth) return;

    const fetchEmployees = async () => {
      setIsLoading(true);
      try {
        const { data, error } = await supabase
          .from('data_karyawan_staff_pabrik')
          .select('*')
          .eq('bulan', selectedMonth)
          .order('nama', { ascending: true });

        if (error) throw error;

        setEmployees(data || []);
        
        // Initialize input state
        const initialInput: StaffAttendanceInputState = {};
        data?.forEach(emp => {
          initialInput[emp.kode] = { kehadiran: '', lembur: '0', keterangan: '' };
        });
        setInputState(initialInput);
        
        checkExistingAttendance(data || []);

      } catch (error: any) {
        console.error("Error fetching employees:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchEmployees();
  }, [selectedMonth]);

  // 3. Check Existing Data
  const checkExistingAttendance = async (currentEmployees: any[]) => {
    // Reset status missing dulu
    setIsTableMissing(false);

    // [CRITICAL FIX] Cek SEMUA kolom yang akan disimpan. 
    // Jika salah satu kolom ini hilang di DB, query ini akan error dan trigger isTableMissing = true.
    const { data: existing, error } = await supabase
      .from('presensi_harian_staff_pabrik')
      .select('kode, nama, grade, bulan, perusahaan, divisi, kehadiran, lembur, keterangan') 
      .eq('tanggal', selectedDate);

    if (error) {
        // Jika error kolom tidak ditemukan atau tabel tidak ada
        if (error.code === '42P01' || error.message.includes('does not exist') || error.message.includes('column')) {
            setIsTableMissing(true);
        }
        return;
    }

    if (existing && existing.length > 0 && currentEmployees.length > 0) {
      setStatusMessage({ type: 'info', text: `Ditemukan ${existing.length} data tersimpan untuk tanggal ini. Mode Edit.` });
      setInputState(prev => {
        const newState = { ...prev };
        existing.forEach((record: any) => {
          if (newState.hasOwnProperty(record.kode)) {
            newState[record.kode] = {
                kehadiran: record.kehadiran || '',
                lembur: record.lembur || '0',
                keterangan: record.keterangan || ''
            };
          }
        });
        return newState;
      });
    } else {
      setStatusMessage(null);
    }
  };

  useEffect(() => {
    checkExistingAttendance(employees);
    if (employees.length > 0) {
        const resetState: StaffAttendanceInputState = {};
        employees.forEach(emp => resetState[emp.kode] = { kehadiran: '', lembur: '0', keterangan: '' });
        setInputState(resetState);
    }
  }, [selectedDate]);

  const handleInputChange = (kode: string, field: 'kehadiran' | 'lembur' | 'keterangan', value: string) => {
    setInputState(prev => ({
        ...prev,
        [kode]: {
            ...prev[kode],
            [field]: value
        }
    }));
  };

  const handleSave = async () => {
    if (!selectedDate || !selectedMonth) {
      alert("Mohon pilih Tanggal dan Bulan.");
      return;
    }

    setIsSaving(true);
    try {
      const validData = employees.map(emp => {
        const input = inputState[emp.kode];
        const kehadiran = input?.kehadiran?.trim();
        const lembur = input?.lembur?.trim();
        
        // Skip if empty
        if (!kehadiran && (!lembur || lembur === '0')) return null;

        return {
          tanggal: selectedDate,
          kode: emp.kode,
          nama: emp.nama,
          grade: emp.grade,
          bulan: selectedMonth,
          perusahaan: emp.perusahaan,
          divisi: emp.divisi, // INCLUDE DIVISI
          kehadiran: kehadiran,
          lembur: lembur,
          keterangan: input.keterangan || '',
          updated_at: new Date().toISOString()
        };
      }).filter(Boolean);

      if (validData.length === 0) {
        alert("Tidak ada data kehadiran yang diisi.");
        setIsSaving(false);
        return;
      }

      // MENGGUNAKAN UPSERT (Lebih Aman daripada Delete -> Insert)
      // Memerlukan constraint unik pada (tanggal, kode)
      const { error } = await supabase
        .from('presensi_harian_staff_pabrik')
        .upsert(validData, { onConflict: 'tanggal,kode' });

      if (error) throw error;

      setSuccessModal({ isOpen: true, title: 'Berhasil', message: `${validData.length} data presensi staff tersimpan.` });
      setStatusMessage({ type: 'success', text: 'Data berhasil disimpan.' });

    } catch (error: any) {
      console.error("Save Error:", error);
      
      // Deteksi error spesifik
      if (error.message?.includes('column') || error.message?.includes('keterangan') || error.message?.includes('schema cache')) {
          setIsTableMissing(true);
          setShowSql(true); // Auto show SQL modal
      } else if (error.message?.includes('unique constraint') || error.message?.includes('on conflict')) {
          setErrorModal({ 
            isOpen: true, 
            title: 'Gagal Menyimpan', 
            message: 'Terjadi konflik data. Mohon klik tombol "Fix Table" (jika muncul) lalu jalankan SQL untuk memperbaiki constraint tabel.' 
          });
          setIsTableMissing(true); // Show fix button
      } else {
          setErrorModal({ isOpen: true, title: 'Gagal Menyimpan', message: error.message });
      }
    } finally {
      setIsSaving(false);
    }
  };

  const filteredEmployees = useMemo(() => {
    return employees.filter(e => 
      e.nama.toLowerCase().includes(searchTerm.toLowerCase()) ||
      e.kode.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [employees, searchTerm]);

  return (
    <div className="space-y-6">
      {/* --- FILTERS HEADER --- */}
      <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
        <div className="flex flex-col lg:flex-row gap-4 items-end">
          <div className="flex-1 w-full grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Tanggal Presensi</label>
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <input 
                  type="date" 
                  value={selectedDate}
                  onChange={(e) => setSelectedDate(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none"
                />
              </div>
            </div>
            
            <div>
              <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Bulan Data Staff</label>
              <div className="relative">
                <Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <select 
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none bg-white cursor-pointer"
                >
                  <option value="" disabled>Pilih Bulan</option>
                  {availableMonths.map(m => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          <div className="w-full lg:w-auto flex gap-2">
             {/* CHECK DB & FIX TABLE BUTTONS */}
             {isTableMissing && (
               <>
                 <button 
                    onClick={() => checkExistingAttendance(employees)}
                    className="px-4 py-2.5 rounded-lg text-sm font-bold flex items-center gap-2 bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 transition-colors"
                    title="Cek Ulang Database"
                 >
                    <RefreshCw size={18}/> Sudah Fix? Refresh
                 </button>
                 <button 
                    onClick={() => setShowSql(true)}
                    className="px-4 py-2.5 rounded-lg text-sm font-bold flex items-center gap-2 bg-red-50 text-red-600 border border-red-200 hover:bg-red-100 animate-pulse transition-colors"
                    title="Setup Database Table"
                 >
                    <Database size={18}/> Fix Table
                 </button>
               </>
             )}

             <button 
               onClick={handleSave}
               disabled={isSaving || employees.length === 0}
               className="flex-1 bg-erp-pink hover:bg-pink-600 text-white px-6 py-2.5 rounded-lg text-sm font-bold flex items-center justify-center gap-2 shadow-md shadow-pink-200 transition-all disabled:opacity-50"
             >
               {isSaving ? <Loader2 className="animate-spin" size={18}/> : <Save size={18}/>}
               Simpan Presensi
             </button>
          </div>
        </div>

        {/* Status Message */}
        {statusMessage && (
          <div className={`mt-4 p-3 rounded-lg text-sm flex items-center gap-2 ${
            statusMessage.type === 'success' ? 'bg-green-50 text-green-700 border border-green-200' :
            statusMessage.type === 'error' ? 'bg-red-50 text-red-700 border border-red-200' :
            'bg-blue-50 text-blue-700 border border-blue-200'
          }`}>
            {statusMessage.type === 'success' ? <CheckCircle2 size={18}/> : <AlertCircle size={18}/>}
            {statusMessage.text}
          </div>
        )}
      </div>

      {/* --- TABLE SECTION --- */}
      <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden flex flex-col h-[600px]">
        <div className="p-4 border-b border-gray-200 bg-gray-50 flex flex-col sm:flex-row justify-between items-center gap-4 shrink-0">
          <div className="relative w-full sm:w-72">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
            <input 
              type="text" 
              placeholder="Cari Nama / Kode..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-erp-pink"
            />
          </div>
          <div className="text-xs text-gray-500">
            Total Staff: <b>{employees.length}</b>
          </div>
        </div>

        <div className="flex-1 overflow-auto custom-scrollbar relative">
          <table className="w-full text-sm text-left whitespace-nowrap">
            <thead className="bg-gray-100 text-gray-600 font-bold sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-4 py-3 w-12 text-center">No</th>
                <th className="px-4 py-3">Kode</th>
                <th className="px-4 py-3">Nama Karyawan</th>
                <th className="px-4 py-3">Divisi</th>
                <th className="px-4 py-3 text-center">Grade</th>
                <th className="px-4 py-3">Perusahaan</th>
                <th className="px-4 py-3 w-32 text-center">Kehadiran</th>
                <th className="px-4 py-3 w-24 text-center">Lembur</th>
                <th className="px-4 py-3">Keterangan</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {isLoading ? (
                <tr><td colSpan={9} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat data...</td></tr>
              ) : filteredEmployees.length > 0 ? (
                filteredEmployees.map((emp, idx) => {
                  const input = inputState[emp.kode] || { kehadiran: '', lembur: '0', keterangan: '' };
                  const val = input.kehadiran;
                  const lembur = input.lembur;
                  const ket = input.keterangan;

                  return (
                    <tr key={emp.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-2 text-center text-gray-500">{idx + 1}</td>
                      <td className="px-4 py-2 font-mono text-gray-600">{emp.kode}</td>
                      <td className="px-4 py-2 font-medium text-gray-900">{emp.nama}</td>
                      <td className="px-4 py-2 text-gray-600">{emp.divisi}</td>
                      <td className="px-4 py-2 text-center">
                        <span className="font-bold text-blue-600">{emp.grade || '-'}</span>
                      </td>
                      <td className="px-4 py-2 text-gray-600 text-xs">{emp.perusahaan}</td>
                      
                      <td className="px-4 py-2">
                        <input 
                          type="text"
                          value={val}
                          onChange={(e) => handleInputChange(emp.kode, 'kehadiran', e.target.value)}
                          className={`w-full px-3 py-1.5 border rounded text-center font-bold focus:ring-2 focus:ring-erp-pink outline-none ${
                            val === '1' || val.toLowerCase() === 'hadir' ? 'bg-green-50 text-green-700 border-green-200' : 
                            val.toUpperCase() === 'M' ? 'bg-red-50 text-red-700 border-red-200' :
                            'bg-white border-gray-300'
                          }`}
                          placeholder="1 / M / S"
                        />
                      </td>
                      <td className="px-4 py-2">
                        <input 
                          type="text"
                          value={lembur}
                          onChange={(e) => handleInputChange(emp.kode, 'lembur', e.target.value)}
                          className="w-full px-2 py-1.5 border border-gray-300 rounded text-center focus:ring-2 focus:ring-erp-pink outline-none"
                          placeholder="0"
                        />
                      </td>
                      <td className="px-4 py-2">
                        <input 
                          type="text"
                          value={ket}
                          onChange={(e) => handleInputChange(emp.kode, 'keterangan', e.target.value)}
                          className="w-full px-3 py-1.5 border border-gray-300 rounded text-sm focus:ring-2 focus:ring-erp-pink outline-none text-gray-600"
                          placeholder="Catatan..."
                        />
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan={9} className="p-16 text-center text-gray-400 italic">
                    {employees.length === 0 ? 'Tidak ada karyawan staff ditemukan di bulan ini.' : 'Data tidak ditemukan.'}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* SQL Manual Copy Modal */}
      {showSql && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-red-50">
              <h3 className="font-bold text-lg text-red-800 flex items-center gap-2">
                <AlertCircle size={20}/> Database Belum Update
              </h3>
              <button onClick={() => setShowSql(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-gray-600 text-sm mb-4">
                Struktur tabel di database perlu diperbarui agar fitur simpan berfungsi.
                Silakan salin kode SQL di bawah ini dan jalankan di <b>Supabase SQL Editor</b>.
              </p>
              
              <div className="relative">
                <textarea 
                  className="w-full h-48 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-erp-pink outline-none"
                  readOnly
                  value={showResetSql ? sqlResetCode : sqlSetupCode}
                  onClick={(e) => e.currentTarget.select()}
                />
                <button 
                  onClick={() => handleCopySQL(showResetSql ? sqlResetCode : sqlSetupCode)}
                  className="absolute top-2 right-2 p-2 bg-white rounded-md shadow-sm border border-gray-200 hover:bg-gray-50 text-gray-600"
                  title="Salin Kode"
                >
                  <Copy size={16}/>
                </button>
              </div>

              <div className="mt-4 flex flex-col sm:flex-row justify-between items-center gap-3">
                <button 
                    onClick={() => setShowResetSql(!showResetSql)}
                    className="text-xs text-red-600 hover:underline font-medium flex items-center gap-1"
                >
                    <Trash2 size={12}/> {showResetSql ? 'Tampilkan SQL Update Biasa' : 'Tabel Masih Error? Tampilkan SQL Reset (Hapus Data)'}
                </button>

                <div className="flex gap-2">
                    <button 
                        onClick={() => window.location.reload()} 
                        className="bg-white border border-gray-300 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors flex items-center gap-2"
                    >
                        <RotateCcw size={16}/> Reload Halaman
                    </button>
                    <button 
                        onClick={() => setShowSql(false)} 
                        className="bg-red-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-red-700 transition-colors"
                    >
                        Tutup
                    </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
    </div>
  );
};
