import React, { useState, useEffect, useMemo, useRef } from 'react';
import { 
  Plus, Search, Edit2, Trash2, Loader2, Database, RefreshCw, 
  Copy, FileSpreadsheet, Upload, AlertCircle, CheckCircle2, 
  Download, Filter, X, AlertTriangle 
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';
import { StaffEmployeeModal } from './StaffEmployeeModal';
import * as XLSX from 'xlsx';

export const StaffEmployeeData: React.FC = () => {
  const [employees, setEmployees] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [showSql, setShowSql] = useState(false);
  
  // --- FILTER STATE ---
  const [searchTerm, setSearchTerm] = useState('');
  const [filterMonth, setFilterMonth] = useState('');
  const [filterDivisi, setFilterDivisi] = useState('');
  
  // Selection State
  const [selectedIds, setSelectedIds] = useState<number[]>([]);

  // Modal States
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState<any>(null);
  const [isSaving, setIsSaving] = useState(false);
  
  // Feedback Modals
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ 
    isOpen: boolean; 
    onConfirm: () => void;
    title?: string;
    message?: string;
    confirmLabel?: string;
  }>({ isOpen: false, onConfirm: () => {} });

  const fileInputRef = useRef<HTMLInputElement>(null);

  // SQL Setup Code
  const sqlFixCode = `
CREATE TABLE IF NOT EXISTS public.data_karyawan_staff_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L',
    grade TEXT,
    divisi TEXT,
    perusahaan TEXT,
    bulan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Constraint agar tidak double input kode di bulan yang sama
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_kode_bulan_staff') THEN
        ALTER TABLE public.data_karyawan_staff_pabrik 
        ADD CONSTRAINT unique_kode_bulan_staff UNIQUE (kode, bulan);
    END IF;
END $$;

ALTER TABLE public.data_karyawan_staff_pabrik ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Staff Data" ON public.data_karyawan_staff_pabrik;
CREATE POLICY "Public Access Staff Data" ON public.data_karyawan_staff_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.data_karyawan_staff_pabrik TO anon, authenticated, service_role;
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlFixCode)
      .then(() => {
        setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
      })
      .catch(() => {
        setShowSql(true);
      });
  };

  const fetchData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    setSelectedIds([]); 

    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      const { data: result, error } = await supabase
        .from('data_karyawan_staff_pabrik')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        if (error.code === '42P01' || error.code === 'PGRST205') {
          setIsTableMissing(true);
        } else {
          throw error;
        }
      } else {
        setEmployees(result || []);
      }
    } catch (error: any) {
      console.error("Error fetching data:", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  // Unique Values for Filters
  const uniqueMonths = useMemo(() => [...new Set(employees.map(e => e.bulan))].sort(), [employees]);
  const uniqueDivisions = useMemo(() => [...new Set(employees.map(e => e.divisi))].sort(), [employees]);

  // Filter Logic
  const filteredData = useMemo(() => {
    return employees.filter(item => {
      const matchSearch = (item.kode || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
                          (item.nama || '').toLowerCase().includes(searchTerm.toLowerCase());
      const matchMonth = filterMonth ? item.bulan === filterMonth : true;
      const matchDivisi = filterDivisi ? item.divisi === filterDivisi : true;
      
      return matchSearch && matchMonth && matchDivisi;
    });
  }, [employees, searchTerm, filterMonth, filterDivisi]);

  // --- DEFINED HANDLER (FIX) ---
  const handleResetFilter = () => {
    setSearchTerm('');
    setFilterMonth('');
    setFilterDivisi('');
  };

  // Selection Logic
  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      setSelectedIds(filteredData.map(item => item.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelectOne = (id: number) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(prev => prev.filter(i => i !== id));
    } else {
      setSelectedIds(prev => [...prev, id]);
    }
  };

  const isAllSelected = filteredData.length > 0 && selectedIds.length === filteredData.length;
  const isIndeterminate = selectedIds.length > 0 && selectedIds.length < filteredData.length;

  // CRUD Handlers
  const handleSave = async (formData: any) => {
    setIsSaving(true);
    try {
      const payload = {
        ...formData,
        updated_at: new Date().toISOString()
      };

      if (selectedItem) {
        const { error } = await supabase
          .from('data_karyawan_staff_pabrik')
          .update(payload)
          .eq('id', selectedItem.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('data_karyawan_staff_pabrik')
          .insert([payload]);
        if (error) {
            if (error.code === '23505') {
                throw new Error(`Kode "${formData.kode}" sudah ada untuk bulan "${formData.bulan}".`);
            }
            throw error;
        }
      }
      setIsModalOpen(false);
      fetchData();
      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data karyawan staff tersimpan.' });
    } catch (error: any) {
      setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Data',
      message: 'Yakin ingin menghapus data karyawan ini?',
      confirmLabel: 'Hapus',
      onConfirm: async () => {
        const { error } = await supabase.from('data_karyawan_staff_pabrik').delete().eq('id', id);
        if (error) {
          setErrorModal({ isOpen: true, title: 'Gagal Hapus', message: error.message });
        } else {
          fetchData();
        }
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
      }
    });
  };

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;

    setConfirmModal({
      isOpen: true,
      title: 'Hapus Massal',
      message: `Yakin ingin menghapus ${selectedIds.length} data terpilih?`,
      confirmLabel: 'Hapus Semua',
      onConfirm: async () => {
        const { error } = await supabase.from('data_karyawan_staff_pabrik').delete().in('id', selectedIds);
        if (error) {
          setErrorModal({ isOpen: true, title: 'Gagal Hapus Massal', message: error.message });
        } else {
          fetchData();
          setSelectedIds([]);
        }
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
      }
    });
  };

  const openModal = (employee?: any) => {
    if (employee) {
      setSelectedItem(employee);
    } else {
      setSelectedItem(null);
    }
    setIsModalOpen(true);
  };

  // Import / Export
  const handleDownloadTemplate = () => {
    const templateData = [
      { 'Kode': 'STF-001', 'Nama': 'Budi Santoso', 'P/L': 'L', 'Grade': 'Senior', 'Divisi': 'HRD', 'Perusahaan': 'CV ADNAN', 'Bulan': 'Oktober 2025' }
    ];
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(templateData);
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, "Template_Data_Staff.xlsx");
  };

  const handleExport = () => {
    if (filteredData.length === 0) {
      alert("Tidak ada data untuk diexport.");
      return;
    }
    const exportData = filteredData.map(item => ({
      'Kode': item.kode,
      'Nama': item.nama,
      'P/L': item.jenis_kelamin,
      'Grade': item.grade,
      'Divisi': item.divisi,
      'Perusahaan': item.perusahaan,
      'Bulan': item.bulan
    }));
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(exportData);
    XLSX.utils.book_append_sheet(wb, ws, "Data Staff");
    XLSX.writeFile(wb, `Data_Staff_${new Date().toISOString().slice(0,10)}.xlsx`);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (evt) => {
      const bstr = evt.target?.result;
      const wb = XLSX.read(bstr, { type: 'array' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const jsonData = XLSX.utils.sheet_to_json(ws);

      if (jsonData.length === 0) {
        setErrorModal({ isOpen: true, title: 'File Kosong', message: 'File Excel tidak memiliki data.' });
        return;
      }

      setIsLoading(true);
      try {
        // 1. Fetch ALL Existing Data for Duplicate Check (Looping to bypass 1000 row limit)
        let allExistingData: any[] = [];
        let from = 0;
        const step = 1000;
        let hasMore = true;

        while (hasMore) {
            const { data: batch, error } = await supabase
                .from('data_karyawan_staff_pabrik')
                .select('kode, bulan')
                .range(from, from + step - 1);
            
            if (error) throw error;
            
            if (batch && batch.length > 0) {
                allExistingData = [...allExistingData, ...batch];
                if (batch.length < step) hasMore = false;
                else from += step;
            } else {
                hasMore = false;
            }
        }
        
        const existingSet = new Set(allExistingData.map((e: any) => `${e.kode.trim().toUpperCase()}-${e.bulan.trim().toUpperCase()}`));

        const itemsToInsert: any[] = [];
        const duplicates: string[] = [];
        const internalDuplicates: string[] = [];
        const processedKeys = new Set();

        jsonData.forEach((row: any) => {
            const kode = (row['Kode'] || '').toString().trim();
            const bulan = (row['Bulan'] || '').toString().trim();
            
            if (kode && bulan) {
                const key = `${kode.toUpperCase()}-${bulan.toUpperCase()}`;
                
                // Check against database
                if (existingSet.has(key)) {
                    duplicates.push(`${kode} (${bulan})`);
                } 
                // Check against itself (internal duplicates in excel)
                else if (processedKeys.has(key)) {
                    internalDuplicates.push(`${kode} (${bulan})`);
                } 
                else {
                    processedKeys.add(key);
                    itemsToInsert.push({
                      kode: kode,
                      nama: (row['Nama'] || '').toString(),
                      jenis_kelamin: (row['P/L'] || 'L').toString(),
                      grade: (row['Grade'] || '').toString(),
                      divisi: (row['Divisi'] || '').toString(),
                      perusahaan: (row['Perusahaan'] || '').toString(),
                      bulan: bulan,
                      updated_at: new Date().toISOString()
                    });
                }
            }
        });

        // 2. Validate Duplicates
        if (duplicates.length > 0 || internalDuplicates.length > 0) {
             let msg = 'Import Dibatalkan.\n\n';
             if (duplicates.length > 0) {
                 msg += `❌ Ditemukan ${duplicates.length} data yang SUDAH ADA di database:\n${duplicates.slice(0, 5).join(', ')}${duplicates.length > 5 ? '...' : ''}\n\n`;
             }
             if (internalDuplicates.length > 0) {
                 msg += `❌ Ditemukan ${internalDuplicates.length} duplikasi di dalam file Excel:\n${internalDuplicates.slice(0, 5).join(', ')}${internalDuplicates.length > 5 ? '...' : ''}\n\n`;
             }
             msg += 'Mohon hapus data ganda tersebut sebelum import.';
             
             setErrorModal({ isOpen: true, title: 'Data Duplikat Terdeteksi', message: msg });
             setIsLoading(false);
             if (fileInputRef.current) fileInputRef.current.value = '';
             return;
        }

        if (itemsToInsert.length === 0) {
             setErrorModal({ isOpen: true, title: 'Data Kosong', message: 'Tidak ada data valid untuk diimport.' });
             setIsLoading(false);
             return;
        }

        // 3. Insert Valid Data
        const { error } = await supabase.from('data_karyawan_staff_pabrik').insert(itemsToInsert);
        if (error) throw error;

        setSuccessModal({ isOpen: true, title: 'Import Berhasil', message: `Berhasil mengimport ${itemsToInsert.length} data staff.` });
        fetchData();
      } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Import', message: error.message });
      } finally {
        setIsLoading(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  return (
    <div className="space-y-6 h-full flex flex-col font-sans">
      <input type="file" ref={fileInputRef} onChange={handleImport} className="hidden" accept=".xlsx, .xls" />
      
      {/* Toolbar */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 shrink-0">
        <div className="relative w-full md:w-72">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
          <input 
            type="text" 
            placeholder="Cari Nama / Kode..." 
            value={searchTerm} 
            onChange={e => setSearchTerm(e.target.value)} 
            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-erp-pink/50" 
          />
        </div>
        <div className="flex flex-wrap gap-2 w-full md:w-auto items-center justify-end">
          {selectedIds.length > 0 && (
            <button onClick={handleBulkDelete} className="px-4 py-2 bg-red-100 text-red-600 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-red-200 transition-colors animate-fadeIn">
              <Trash2 size={16}/> Hapus ({selectedIds.length})
            </button>
          )}
          <button onClick={handleDownloadTemplate} className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm flex items-center gap-2 text-sm font-medium">
            <FileSpreadsheet size={16}/> Template
          </button>
          <button onClick={() => fileInputRef.current?.click()} className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm flex items-center gap-2 text-sm font-medium">
            <Upload size={16}/> Import
          </button>
          <button onClick={handleExport} className="px-3 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 shadow-sm flex items-center gap-2 text-sm font-medium transition-colors">
            <Download size={16}/> Export
          </button>
          <button onClick={fetchData} className="p-2 bg-white border rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm" title="Refresh">
            <RefreshCw size={18}/>
          </button>
          <button onClick={() => openModal()} className="bg-erp-pink text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-pink-600 shadow-md transition-colors">
            <Plus size={18}/> Tambah
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm grid grid-cols-1 md:grid-cols-12 gap-4 items-end">
        <div className="col-span-1 md:col-span-12 flex items-center gap-2 text-sm font-bold text-erp-pink mb-1">
          <Filter size={18}/> Filter Data
        </div>
        
        <div className="col-span-1 md:col-span-4">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Bulan</label>
          <select 
            value={filterMonth} 
            onChange={(e) => setFilterMonth(e.target.value)} 
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
          >
            <option value="">Semua Bulan</option>
            {uniqueMonths.map(m => (
              <option key={m} value={m}>{m}</option>
            ))}
          </select>
        </div>

        <div className="col-span-1 md:col-span-4">
          <label className="block text-xs font-medium text-gray-500 mb-1.5 ml-1">Divisi</label>
          <select 
            value={filterDivisi} 
            onChange={(e) => setFilterDivisi(e.target.value)} 
            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-erp-pink/30 focus:border-erp-pink outline-none cursor-pointer"
          >
            <option value="">Semua Divisi</option>
            {uniqueDivisions.map(d => (
              <option key={d} value={d}>{d}</option>
            ))}
          </select>
        </div>

        <div className="col-span-1 md:col-span-4">
          <button 
            onClick={handleResetFilter} 
            className="w-full px-4 py-2.5 bg-gray-100 text-gray-600 rounded-xl text-sm font-medium hover:bg-gray-200 hover:text-gray-800 flex items-center justify-center gap-2 transition-colors"
          >
            <X size={18} /> Reset Filter
          </button>
        </div>
      </div>

      {isTableMissing ? (
        <div className="bg-white border border-red-200 rounded-xl p-8 text-center shadow-sm animate-fadeIn">
          <div className="bg-red-50 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
            <Database className="text-red-500" size={32} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 mb-2">Database Belum Siap</h3>
          <p className="text-gray-500 mb-6">Tabel <code>data_karyawan_staff_pabrik</code> belum ditemukan.</p>
          {showSql ? (
            <div className="mt-4 max-w-2xl mx-auto text-left">
              <p className="text-sm text-gray-600 mb-2 font-medium">Gagal menyalin otomatis. Silakan salin manual kode di bawah:</p>
              <textarea 
                className="w-full h-64 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 outline-none"
                readOnly
                value={sqlFixCode}
                onClick={(e) => e.currentTarget.select()}
              />
            </div>
          ) : (
            <button onClick={handleCopySQL} className="bg-red-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 mx-auto hover:bg-red-700 shadow-lg transition-colors">
              <Copy size={18}/> Salin Kode SQL
            </button>
          )}
        </div>
      ) : (
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm flex-1">
          <div className="overflow-auto max-h-[600px] custom-scrollbar relative">
            <table className="w-full text-sm text-left whitespace-nowrap">
              <thead className="bg-gray-50 text-gray-600 font-bold border-b border-gray-200 sticky top-0 z-10">
                <tr>
                  <th className="px-4 py-4 w-10 text-center">
                    <input 
                      type="checkbox" 
                      className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                      checked={isAllSelected}
                      ref={input => { if (input) input.indeterminate = isIndeterminate; }}
                      onChange={handleSelectAll}
                    />
                  </th>
                  <th className="px-6 py-4">Kode</th>
                  <th className="px-6 py-4">Nama</th>
                  <th className="px-6 py-4 text-center">P/L</th>
                  <th className="px-6 py-4 text-center">Grade</th>
                  <th className="px-6 py-4">Divisi</th>
                  <th className="px-6 py-4">Perusahaan</th>
                  <th className="px-6 py-4">Bulan</th>
                  <th className="px-6 py-4 text-center">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {isLoading ? (
                  <tr><td colSpan={9} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat data...</td></tr>
                ) : filteredData.length > 0 ? (
                  filteredData.map((item) => (
                    <tr key={item.id} className={`hover:bg-gray-50 transition-colors ${selectedIds.includes(item.id) ? 'bg-pink-50/30' : ''}`}>
                      <td className="px-4 py-4 text-center">
                        <input 
                          type="checkbox" 
                          className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                          checked={selectedIds.includes(item.id)}
                          onChange={() => handleSelectOne(item.id)}
                        />
                      </td>
                      <td className="px-6 py-3 font-mono text-gray-600 bg-gray-50/50 rounded w-fit px-2">{item.kode}</td>
                      <td className="px-6 py-3 font-medium text-gray-900">{item.nama}</td>
                      <td className="px-6 py-3 text-center">
                        <span className={`px-2 py-1 rounded text-xs font-bold ${item.jenis_kelamin === 'L' ? 'bg-blue-50 text-blue-600' : 'bg-pink-50 text-pink-600'}`}>
                          {item.jenis_kelamin}
                        </span>
                      </td>
                      <td className="px-6 py-3 text-center">{item.grade}</td>
                      <td className="px-6 py-3 text-gray-600">{item.divisi}</td>
                      <td className="px-6 py-3 text-gray-600">{item.perusahaan}</td>
                      <td className="px-6 py-3 text-gray-600">{item.bulan}</td>
                      <td className="px-6 py-3 text-center">
                        <div className="flex justify-center gap-2">
                          <button onClick={() => openModal(item)} className="p-1.5 text-blue-600 hover:bg-blue-50 rounded transition-colors"><Edit2 size={16}/></button>
                          <button onClick={() => handleDelete(item.id)} className="p-1.5 text-red-600 hover:bg-red-50 rounded transition-colors"><Trash2 size={16}/></button>
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr><td colSpan={9} className="p-16 text-center text-gray-400 italic">Tidak ada data staff.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <StaffEmployeeModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} onSubmit={handleSave} initialData={selectedItem} isLoading={isSaving} />
      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal isOpen={confirmModal.isOpen} onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} onConfirm={confirmModal.onConfirm} title={confirmModal.title || "Hapus Data"} message={confirmModal.message || "Yakin ingin menghapus data ini?"} confirmLabel={confirmModal.confirmLabel || "Hapus"} isDangerous={true} />
    </div>
  );
};
