import React, { useState, useEffect, useMemo } from 'react';
import { 
  Calendar, Save, Loader2, Filter, Search, CheckCircle2, AlertCircle, Database, Copy
} from 'lucide-react';
import { supabase } from '../../../lib/supabase';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';

export const WholesaleBoronganInput: React.FC = () => {
  // Filters
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [selectedMonth, setSelectedMonth] = useState('');
  const [selectedPeriod, setSelectedPeriod] = useState('Periode 1');
  
  // Data
  const [employees, setEmployees] = useState<any[]>([]);
  const [availableMonths, setAvailableMonths] = useState<string[]>([]);
  
  // State Input: Key = Kode Karyawan, Value = { kehadiran, keterangan }
  const [inputState, setInputState] = useState<Record<string, { kehadiran: string; keterangan: string }>>({}); 
  
  // UI State
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusMessage, setStatusMessage] = useState<{type: 'success'|'error'|'info', text: string} | null>(null);
  const [isTableMissing, setIsTableMissing] = useState(false);

  // Modals
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });

  // SQL Setup
  const sqlSetupCode = `
CREATE TABLE IF NOT EXISTS public.presensi_harian_borongan_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    grade TEXT,
    bulan TEXT,
    perusahaan TEXT,
    periode TEXT,
    kehadiran TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tambahkan kolom keterangan jika belum ada
ALTER TABLE public.presensi_harian_borongan_pabrik_garut ADD COLUMN IF NOT EXISTS keterangan TEXT;

-- Constraint agar tidak double input di tanggal & kode yang sama
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_borongan_garut_harian') THEN
        ALTER TABLE public.presensi_harian_borongan_pabrik_garut 
        ADD CONSTRAINT unique_borongan_garut_harian UNIQUE (tanggal, kode);
    END IF;
END $$;

-- Security
ALTER TABLE public.presensi_harian_borongan_pabrik_garut ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access" ON public.presensi_harian_borongan_pabrik_garut;
CREATE POLICY "Public Access" ON public.presensi_harian_borongan_pabrik_garut FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.presensi_harian_borongan_pabrik_garut TO anon, authenticated, service_role;

-- Refresh Schema Cache
NOTIFY pgrst, 'reload config';
  `;

  const handleCopySQL = async () => {
    try {
      await navigator.clipboard.writeText(sqlSetupCode);
      setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan di SQL Editor Supabase untuk update tabel.' });
    } catch (err) {
      // Fallback: Try legacy execCommand if Clipboard API fails
      try {
        const textArea = document.createElement("textarea");
        textArea.value = sqlSetupCode;
        textArea.style.position = "fixed"; // Avoid scrolling
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        
        const successful = document.execCommand('copy');
        document.body.removeChild(textArea);
        
        if (successful) {
          setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan di SQL Editor Supabase untuk update tabel.' });
          return;
        }
        throw new Error('Copy failed');
      } catch (fallbackErr) {
        console.error("SQL Setup Code:", sqlSetupCode);
        setErrorModal({ 
          isOpen: true, 
          title: 'Gagal Menyalin', 
          message: 'Browser memblokir akses clipboard. Kode SQL telah dicetak ke Console (F12) agar Anda dapat menyalinnya manual.' 
        });
      }
    }
  };

  // 1. Fetch Available Months
  useEffect(() => {
    const fetchMonths = async () => {
      const { data } = await supabase
        .from('data_karyawan_pabrik_garut')
        .select('bulan')
        .order('created_at', { ascending: false });
      
      if (data) {
        const months = [...new Set(data.map(d => d.bulan))].filter(Boolean);
        setAvailableMonths(months);
        if (months.length > 0 && !selectedMonth) {
          const currentMonthName = new Date().toLocaleString('id-ID', { month: 'long', year: 'numeric' });
          const match = months.find(m => m.toLowerCase() === currentMonthName.toLowerCase());
          setSelectedMonth(match || months[0]);
        }
      }
    };
    fetchMonths();
  }, []);

  // 2. Fetch Employees (Filter Borongan)
  useEffect(() => {
    if (!selectedMonth) return;

    const fetchEmployees = async () => {
      setIsLoading(true);
      try {
        const { data, error } = await supabase
          .from('data_karyawan_pabrik_garut')
          .select('*')
          .eq('bulan', selectedMonth)
          .eq('status_aktif', true)
          .order('nama', { ascending: true });

        if (error) throw error;

        // FILTER: Hanya ambil yang mengandung "BORONGAN"
        const filteredData = (data || []).filter(emp => {
            const p = (emp.perusahaan || '').toUpperCase();
            const d = (emp.divisi || '').toUpperCase();
            const b = (emp.bagian || '').toUpperCase();
            return p.includes('BORONGAN') || d.includes('BORONGAN') || b.includes('BORONGAN');
        });

        setEmployees(filteredData);
        
        // Initialize input state
        const initialInput: Record<string, { kehadiran: string; keterangan: string }> = {};
        filteredData.forEach(emp => {
          initialInput[emp.kode] = { kehadiran: '', keterangan: '' };
        });
        setInputState(initialInput);
        
        checkExistingAttendance(filteredData);

      } catch (error: any) {
        console.error("Error fetching employees:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchEmployees();
  }, [selectedMonth]);

  // 3. Check Existing Data
  const checkExistingAttendance = async (currentEmployees: any[]) => {
    // Cek tabel meskipun karyawan kosong, untuk mendeteksi error 42P01
    setIsTableMissing(false);

    const { data: existing, error } = await supabase
      .from('presensi_harian_borongan_pabrik_garut')
      .select('kode, kehadiran, keterangan')
      .eq('tanggal', selectedDate);

    if (error) {
        if (error.code === '42P01' || error.message.includes('does not exist')) {
            setIsTableMissing(true);
        }
        return;
    }

    if (existing && existing.length > 0 && currentEmployees.length > 0) {
      setStatusMessage({ type: 'info', text: `Ditemukan ${existing.length} data tersimpan untuk tanggal ini.` });
      setInputState(prev => {
        const newState = { ...prev };
        existing.forEach((record: any) => {
          if (newState.hasOwnProperty(record.kode)) {
            newState[record.kode] = {
                kehadiran: record.kehadiran || '',
                keterangan: record.keterangan || ''
            };
          }
        });
        return newState;
      });
    } else {
      setStatusMessage(null);
    }
  };

  useEffect(() => {
    // Selalu cek database saat tanggal berubah (bahkan jika karyawan 0, untuk cek tabel ada/tidak)
    checkExistingAttendance(employees);
    
    if (employees.length > 0) {
        // Reset input visual jika ada karyawan
        const resetState: Record<string, { kehadiran: string; keterangan: string }> = {};
        employees.forEach(emp => resetState[emp.kode] = { kehadiran: '', keterangan: '' });
        setInputState(resetState);
    }
  }, [selectedDate]);

  const handleInputChange = (kode: string, field: 'kehadiran' | 'keterangan', value: string) => {
    setInputState(prev => ({
        ...prev,
        [kode]: {
            ...prev[kode],
            [field]: value
        }
    }));
  };

  const handleSave = async () => {
    if (!selectedDate || !selectedMonth) {
      alert("Mohon pilih Tanggal dan Bulan.");
      return;
    }

    setIsSaving(true);
    try {
      const validData = employees.map(emp => {
        const input = inputState[emp.kode];
        const kehadiran = input?.kehadiran?.trim();
        
        if (!kehadiran) return null;

        // Tentukan Grade berdasarkan Periode
        const grade = selectedPeriod === 'Periode 1' ? emp.grade_p1 : emp.grade_p2;

        return {
          tanggal: selectedDate,
          kode: emp.kode,
          nama: emp.nama,
          grade: grade,
          bulan: selectedMonth,
          perusahaan: 'BORONGAN', // FORCE BORONGAN
          periode: selectedPeriod,
          kehadiran: kehadiran,
          keterangan: input.keterangan || '' // Simpan keterangan
        };
      }).filter(Boolean);

      if (validData.length === 0) {
        alert("Tidak ada data kehadiran yang diisi.");
        setIsSaving(false);
        return;
      }

      // 1. Hapus data lama di tanggal ini (untuk update)
      const codes = validData.map((d: any) => d.kode);
      await supabase
        .from('presensi_harian_borongan_pabrik_garut')
        .delete()
        .eq('tanggal', selectedDate)
        .in('kode', codes);

      // 2. Insert baru
      const { error } = await supabase
        .from('presensi_harian_borongan_pabrik_garut')
        .insert(validData);

      if (error) throw error;

      setSuccessModal({ isOpen: true, title: 'Berhasil', message: `${validData.length} data borongan tersimpan.` });
      setStatusMessage({ type: 'success', text: 'Data berhasil disimpan.' });

    } catch (error: any) {
      setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  const filteredEmployees = useMemo(() => {
    return employees.filter(e => 
      e.nama.toLowerCase().includes(searchTerm.toLowerCase()) ||
      e.kode.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [employees, searchTerm]);

  return (
    <div className="space-y-6">
      {/* --- FILTERS HEADER --- */}
      <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
        <div className="flex flex-col lg:flex-row gap-4 items-end">
          <div className="flex-1 w-full grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Tanggal Presensi</label>
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <input 
                  type="date" 
                  value={selectedDate}
                  onChange={(e) => setSelectedDate(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none"
                />
              </div>
            </div>
            
            <div>
              <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Bulan Data Karyawan</label>
              <div className="relative">
                <Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <select 
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none bg-white cursor-pointer"
                >
                  <option value="" disabled>Pilih Bulan</option>
                  {availableMonths.map(m => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Periode Gaji</label>
              <select 
                value={selectedPeriod}
                onChange={(e) => setSelectedPeriod(e.target.value)}
                className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none bg-white cursor-pointer"
              >
                <option value="Periode 1">Periode 1</option>
                <option value="Periode 2">Periode 2</option>
              </select>
            </div>
          </div>

          <div className="w-full lg:w-auto flex gap-2">
             {/* TOMBOL SETUP DB HANYA MUNCUL JIKA ERROR */}
             {isTableMissing && (
                 <button 
                    onClick={handleCopySQL}
                    className="px-4 py-2.5 rounded-lg text-sm font-bold flex items-center gap-2 transition-colors bg-red-50 text-red-600 border border-red-200 animate-pulse"
                    title="Setup Database Table"
                 >
                    <Database size={18}/> Fix Table
                 </button>
             )}

             <button 
               onClick={handleSave}
               disabled={isSaving || employees.length === 0}
               className="flex-1 bg-erp-pink hover:bg-pink-600 text-white px-6 py-2.5 rounded-lg text-sm font-bold flex items-center justify-center gap-2 shadow-md shadow-pink-200 transition-all disabled:opacity-50"
             >
               {isSaving ? <Loader2 className="animate-spin" size={18}/> : <Save size={18}/>}
               Simpan Presensi
             </button>
          </div>
        </div>

        {/* Status Message */}
        {statusMessage && (
          <div className={`mt-4 p-3 rounded-lg text-sm flex items-center gap-2 ${
            statusMessage.type === 'success' ? 'bg-green-50 text-green-700 border border-green-200' :
            statusMessage.type === 'error' ? 'bg-red-50 text-red-700 border border-red-200' :
            'bg-blue-50 text-blue-700 border border-blue-200'
          }`}>
            {statusMessage.type === 'success' ? <CheckCircle2 size={18}/> : <AlertCircle size={18}/>}
            {statusMessage.text}
          </div>
        )}
      </div>

      {/* --- TABLE SECTION (FIXED HEIGHT SCROLL) --- */}
      <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden flex flex-col h-[600px]">
        <div className="p-4 border-b border-gray-200 bg-gray-50 flex flex-col sm:flex-row justify-between items-center gap-4 shrink-0">
          <div className="relative w-full sm:w-72">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
            <input 
              type="text" 
              placeholder="Cari Nama / Kode..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-erp-pink"
            />
          </div>
          <div className="text-xs text-gray-500">
            Total Karyawan Borongan: <b>{employees.length}</b>
          </div>
        </div>

        <div className="flex-1 overflow-auto custom-scrollbar relative">
          <table className="w-full text-sm text-left whitespace-nowrap">
            <thead className="bg-gray-100 text-gray-600 font-bold sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-4 py-3 w-12 text-center">No</th>
                <th className="px-4 py-3">Kode</th>
                <th className="px-4 py-3">Nama Karyawan</th>
                <th className="px-4 py-3">Divisi</th>
                <th className="px-4 py-3">Bagian</th>
                <th className="px-4 py-3 text-center">Grade ({selectedPeriod === 'Periode 1' ? 'P1' : 'P2'})</th>
                <th className="px-4 py-3">Perusahaan</th>
                <th className="px-4 py-3 w-40 text-center">Kehadiran</th>
                <th className="px-4 py-3">Keterangan</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {isLoading ? (
                <tr><td colSpan={9} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat data...</td></tr>
              ) : filteredEmployees.length > 0 ? (
                filteredEmployees.map((emp, idx) => {
                  const displayGrade = selectedPeriod === 'Periode 1' ? emp.grade_p1 : emp.grade_p2;
                  const input = inputState[emp.kode] || { kehadiran: '', keterangan: '' };
                  const val = input.kehadiran;
                  const ket = input.keterangan;

                  return (
                    <tr key={emp.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-2 text-center text-gray-500">{idx + 1}</td>
                      <td className="px-4 py-2 font-mono text-gray-600">{emp.kode}</td>
                      <td className="px-4 py-2 font-medium text-gray-900">{emp.nama}</td>
                      <td className="px-4 py-2 text-gray-600">{emp.divisi}</td>
                      <td className="px-4 py-2 text-gray-500 text-xs">{emp.bagian}</td>
                      <td className="px-4 py-2 text-center">
                        <span className="font-bold text-blue-600">{displayGrade || '-'}</span>
                      </td>
                      <td className="px-4 py-2 text-gray-600 text-xs">BORONGAN</td>
                      
                      <td className="px-4 py-2">
                        <input 
                          type="text"
                          value={val}
                          onChange={(e) => handleInputChange(emp.kode, 'kehadiran', e.target.value)}
                          className={`w-full px-3 py-1.5 border rounded text-center font-bold focus:ring-2 focus:ring-erp-pink outline-none ${
                            val === '1' || val.toLowerCase() === 'hadir' ? 'bg-green-50 text-green-700 border-green-200' : 
                            val.toUpperCase() === 'M' ? 'bg-red-50 text-red-700 border-red-200' :
                            'bg-white border-gray-300'
                          }`}
                          placeholder="1 / M / S"
                        />
                      </td>
                      <td className="px-4 py-2">
                        <input 
                          type="text"
                          value={ket}
                          onChange={(e) => handleInputChange(emp.kode, 'keterangan', e.target.value)}
                          className="w-full px-3 py-1.5 border border-gray-300 rounded text-sm focus:ring-2 focus:ring-erp-pink outline-none text-gray-600"
                          placeholder="Catatan..."
                        />
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan={9} className="p-16 text-center text-gray-400 italic">
                    {employees.length === 0 ? 'Tidak ada karyawan Borongan ditemukan di bulan ini.' : 'Data tidak ditemukan.'}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
    </div>
  );
};
