import React, { useState, useEffect, useMemo } from 'react';
import { 
  Search, Filter, Download, Loader2, RefreshCw, 
  Wallet, FileText, Database, CheckCircle2, UserCheck, X, Wrench, Copy,
  Coins, Calculator, ArrowRightLeft
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import * as XLSX from 'xlsx';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { WholesaleRecapDetailModal } from './WholesaleRecapDetailModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';

interface WholesaleRecapProps {
  isGarut?: boolean;
}

export const WholesaleRecap: React.FC<WholesaleRecapProps> = ({ isGarut = false }) => {
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  // Filters
  const [selectedMonth, setSelectedMonth] = useState('');
  const [selectedPeriod, setSelectedPeriod] = useState('Semua Periode');
  const [selectedCompany, setSelectedCompany] = useState('Semua Perusahaan');
  const [selectedDivision, setSelectedDivision] = useState('Semua Divisi');
  const [searchTerm, setSearchTerm] = useState('');
  // Dropdown Options
  const [uniqueMonths, setUniqueMonths] = useState<string[]>([]);
  const [uniqueCompanies, setUniqueCompanies] = useState<string[]>([]);
  const [uniqueDivisions, setUniqueDivisions] = useState<string[]>([]);
  
  // Detail Modal State
  const [detailModalOpen, setDetailModalOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<any>(null);
  const [employeeDailyData, setEmployeeDailyData] = useState<any[]>([]);

  // Bonus Distribution State
  const [isBonusModalOpen, setIsBonusModalOpen] = useState(false);
  const [targetBonusTotal, setTargetBonusTotal] = useState<string>('0');
  const [isDistributing, setIsDistributing] = useState(false);

  // Tables
  const boronganTable = isGarut ? 'data_gaji_borongan_pabrik_garut' : 'gaji_borongan';
  const employeeTable = isGarut ? 'data_karyawan_pabrik_garut' : 'data_karyawan_pabrik'; 
  // Attendance Table for Month Discovery
  const attendanceTable = isGarut ? 'presensi_harian_borongan_pabrik_garut' : 'input_absensi_harian_borongan';

  // Modals
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ isOpen: boolean; onConfirm: () => void; title: string; message: string; confirmLabel?: string }>({ isOpen: false, onConfirm: () => {}, title: '', message: '' });

  const formatRupiah = (value: number) => new Intl.NumberFormat('id-ID', { 
    style: 'currency', 
    currency: 'IDR', 
    minimumFractionDigits: 0,
    maximumFractionDigits: 0 
  }).format(value);

  // SQL Setup Code
  const sqlSetupCode = `
-- 1. Tabel Rekap Gaji Harian (Gabungan)
CREATE TABLE IF NOT EXISTS public.rekap_gaji_harian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    grade TEXT,
    divisi TEXT,
    bulan TEXT,
    perusahaan TEXT,
    periode TEXT,
    keterangan TEXT,
    keluar_masuk TEXT,
    gaji_pokok NUMERIC DEFAULT 0,
    gaji_lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    uang_bonus NUMERIC DEFAULT 0,
    total_gaji NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_rekap_gaji_harian UNIQUE (tanggal, kode, periode, perusahaan)
);

-- 2. Fungsi Generate Rekap
CREATE OR REPLACE FUNCTION generate_rekap_gaji_harian(p_bulan TEXT)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_count_harian INT := 0;
    v_count_borongan INT := 0;
BEGIN
    DELETE FROM public.rekap_gaji_harian WHERE bulan = p_bulan;

    -- A. Insert dari Gaji Harian Pabrik
    INSERT INTO public.rekap_gaji_harian (
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        gaji_pokok, gaji_lembur, uang_makan, uang_kehadiran, uang_bonus, total_gaji
    )
    SELECT 
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        COALESCE(gaji_pokok, 0), COALESCE(gaji_lembur, 0), COALESCE(uang_makan, 0), 
        COALESCE(uang_kehadiran, 0), COALESCE(uang_bonus, 0), COALESCE(gaji, 0)
    FROM public.gaji_harian_pabrik_garut
    WHERE bulan = p_bulan;
    GET DIAGNOSTICS v_count_harian = ROW_COUNT;

    -- B. Insert dari Gaji Harian Borongan
    INSERT INTO public.rekap_gaji_harian (
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        gaji_pokok, gaji_lembur, uang_makan, uang_kehadiran, uang_bonus, total_gaji
    )
    SELECT 
        tanggal, kode, nama, grade, divisi, bulan, perusahaan, periode, keterangan, keluar_masuk,
        COALESCE(gaji, 0), 0, 0, 0, COALESCE(bonus, 0), (COALESCE(gaji, 0) + COALESCE(bonus, 0))
    FROM public.gaji_harian_borongan_pabrik_garut
    WHERE bulan = p_bulan;
    GET DIAGNOSTICS v_count_borongan = ROW_COUNT;

    RETURN 'Rekap Berhasil. Harian: ' || v_count_harian || ', Borongan: ' || v_count_borongan;
END;
$$;

-- 3. Fungsi Distribusi Bonus Borongan
CREATE OR REPLACE FUNCTION distribute_bonus_borongan_garut(p_bulan TEXT, p_total_bonus NUMERIC)
RETURNS text AS $$
DECLARE
    v_total_hadir NUMERIC;
    v_updated INT;
BEGIN
    -- Hitung Total Kehadiran (H) di bulan tersebut
    SELECT SUM(
        CASE 
            WHEN kehadiran IN ('H', '1', 'Hadir', 'Full') THEN 1
            WHEN kehadiran IN ('0.5', 'Setengah') THEN 0.5
            ELSE 0 
        END
    ) INTO v_total_hadir
    FROM data_gaji_borongan_pabrik_garut
    WHERE bulan = p_bulan;

    IF v_total_hadir IS NULL OR v_total_hadir <= 0 THEN
        RETURN 'Gagal: Tidak ada kehadiran (H) di bulan ini.';
    END IF;

    -- Update Bonus per Karyawan (Proporsional)
    UPDATE data_gaji_borongan_pabrik_garut
    SET bonus = ROUND(
        (p_total_bonus / v_total_hadir) * 
        CASE 
            WHEN kehadiran IN ('H', '1', 'Hadir', 'Full') THEN 1
            WHEN kehadiran IN ('0.5', 'Setengah') THEN 0.5
            ELSE 0 
        END
    )
    WHERE bulan = p_bulan;

    GET DIAGNOSTICS v_updated = ROW_COUNT;
    RETURN 'Berhasil mendistribusikan Rp ' || p_total_bonus || ' ke ' || v_updated || ' data presensi.';
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION generate_rekap_gaji_harian(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION distribute_bonus_borongan_garut(text, numeric) TO authenticated, service_role;
NOTIFY pgrst, 'reload config';
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlSetupCode);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
  };

  // --- 1. FETCH OPTIONS (ON MOUNT) ---
  useEffect(() => {
    const fetchOptions = async () => {
      if (!isSupabaseConfigured()) return;
      try {
        const { data: salaryData } = await supabase.from(boronganTable).select('bulan, perusahaan');
        const { data: attendanceData } = await supabase.from(attendanceTable).select('bulan, perusahaan');
        const { data: empData } = await supabase.from(employeeTable).select('divisi');

        const allMonths = new Set<string>();
        const allCompanies = new Set<string>();
        const allDivisions = new Set<string>();

        const processData = (sourceData: any[]) => {
            if (sourceData) {
                sourceData.forEach(d => {
                    if (d.bulan) allMonths.add(d.bulan.trim());
                    if (d.perusahaan) allCompanies.add(d.perusahaan.trim());
                    if (d.divisi) allDivisions.add(d.divisi);
                });
            }
        };

        processData(salaryData || []);
        processData(attendanceData || []);

        const monthMap: Record<string, number> = {
            'januari': 0, 'februari': 1, 'maret': 2, 'april': 3, 'mei': 4, 'juni': 5,
            'juli': 6, 'agustus': 7, 'september': 8, 'oktober': 9, 'november': 10, 'desember': 11
        };

        const sortedMonths = Array.from(allMonths).sort((a, b) => {
            const partsA = a.split(' ');
            const partsB = b.split(' ');
            const yearA = parseInt(partsA[1]) || 0;
            const yearB = parseInt(partsB[1]) || 0;
            if (yearA !== yearB) return yearB - yearA;
            return (monthMap[partsB[0]?.toLowerCase()] || 0) - (monthMap[partsA[0]?.toLowerCase()] || 0);
        });

        setUniqueMonths(sortedMonths);
        setUniqueCompanies(Array.from(allCompanies).sort());
        
        if (sortedMonths.length > 0 && !selectedMonth) {
            setSelectedMonth(sortedMonths[0]);
        }

        if (empData) {
            const divisions = [...new Set(empData.map(d => d.divisi ? d.divisi.trim() : '').filter(Boolean))].sort();
            setUniqueDivisions(divisions);
        }

      } catch (e) {
        console.error("Error fetching options:", e);
      }
    };
    fetchOptions();
  }, [isGarut, boronganTable, employeeTable, attendanceTable]);

  // --- AUTO SET DEFAULT BONUS FOR NOVEMBER ---
  useEffect(() => {
    if (selectedMonth && selectedMonth.toLowerCase().includes('november')) {
        setTargetBonusTotal('575000');
    } else {
        setTargetBonusTotal('0');
    }
  }, [selectedMonth]);

  // --- 2. FETCH & AGGREGATE DATA ---
  const fetchData = async () => {
    setIsLoading(true);
    try {
      let dailyData: any[] = [];
      let from = 0;
      const step = 1000;
      let hasMore = true;

      while (hasMore) {
        let query = supabase.from(boronganTable).select('*');
        if (selectedMonth) query = query.ilike('bulan', selectedMonth.trim());
        const { data: batch, error } = await query.range(from, from + step - 1);
        
        if (error) throw error;

        if (batch && batch.length > 0) {
            dailyData = [...dailyData, ...batch];
            if (batch.length < step) hasMore = false;
            else from += step;
        } else {
            hasMore = false;
        }
      }

      let queryEmp = supabase.from(employeeTable).select('kode, divisi, bulan');
      if (selectedMonth) queryEmp = queryEmp.ilike('bulan', selectedMonth.trim());
      const { data: empData } = await queryEmp;
      
      const empMap = new Map();
      empData?.forEach((e: any) => {
          empMap.set(`${e.kode}-${e.bulan}`, e.divisi);
      });

      const aggregation: Record<string, any> = {};
      
      if (dailyData && dailyData.length > 0) {
          dailyData.forEach((item: any) => {
            if (selectedPeriod !== 'Semua Periode' && item.periode !== selectedPeriod) return;
            
            if (selectedCompany !== 'Semua Perusahaan') {
                const itemPT = (item.perusahaan || '').toUpperCase();
                const filterPT = selectedCompany.toUpperCase();
                if (!itemPT.includes(filterPT) && itemPT !== filterPT) return;
            }

            const key = `${item.kode}-${item.periode}-${item.bulan}`;
            const resolvedDivisi = item.divisi || empMap.get(`${item.kode}-${item.bulan}`) || '-';
            
            if (selectedDivision !== 'Semua Divisi' && resolvedDivisi !== selectedDivision) return;

            if (!aggregation[key]) {
                aggregation[key] = {
                    kode: item.kode,
                    nama: item.nama,
                    perusahaan: item.perusahaan,
                    divisi: resolvedDivisi,
                    grade: item.grade,
                    bulan: item.bulan,
                    periode: item.periode,
                    total_gaji: 0,
                    total_bonus: 0,
                    total_redistribusi: 0,
                    total_h: 0
                };
            }

            // FIX: Pisahkan Bonus dan Redistribusi
            aggregation[key].total_gaji += Number(item.gaji || 0);
            aggregation[key].total_bonus += Number(item.bonus || 0); // HANYA Bonus Manual/Distributed
            
            // Redistribusi (Sisa Potongan) dianggap sebagai tambahan Gaji/Upah
            const redist = Number(item.bonus_redistribusi || 0);
            aggregation[key].total_redistribusi += redist;
            
            const k = (item.kehadiran || '').toString().toUpperCase().trim();
            if (['H', '1', 'HADIR', 'FULL'].includes(k)) {
                aggregation[key].total_h += 1;
            } else if (['0.5', 'SETENGAH'].includes(k)) {
                aggregation[key].total_h += 0.5;
            }
          });
      }

      const aggregatedList = Object.values(aggregation).map(item => ({
          ...item,
          // Total Terima = Gaji + Bonus + Redistribusi
          total_terima: item.total_gaji + item.total_bonus + item.total_redistribusi,
          // Display Gaji = Gaji + Redistribusi (agar Bonus tetap bersih)
          display_upah: item.total_gaji + item.total_redistribusi
      })).sort((a, b) => a.nama.localeCompare(b.nama));

      setData(aggregatedList);

    } catch (err: any) {
      console.error("Error fetching recap:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [selectedMonth, selectedPeriod, selectedCompany, selectedDivision]);

  const filteredData = useMemo(() => {
    return data.filter(item => 
        item.nama.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.kode.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [data, searchTerm]);

  const totals = useMemo(() => {
      return filteredData.reduce((acc, curr) => ({
          gaji: acc.gaji + curr.display_upah, // Use display_upah (includes redistribusi)
          bonus: acc.bonus + curr.total_bonus,
          terima: acc.terima + curr.total_terima
      }), { gaji: 0, bonus: 0, terima: 0 });
  }, [filteredData]);

  // --- BONUS DISTRIBUTION HANDLER ---
  const handleDistributeBonus = async () => {
    if (!selectedMonth) return;
    setIsDistributing(true);
    try {
        const cleanTotal = Number(targetBonusTotal.replace(/[^0-9]/g, ''));
        const { data: msg, error } = await supabase.rpc('distribute_bonus_borongan_garut', { 
            p_bulan: selectedMonth, 
            p_total_bonus: cleanTotal 
        });
        
        if (error) {
            if (error.message.includes('function') || error.code === '42883') {
                setShowSqlModal(true);
                throw new Error("Fungsi distribusi belum dibuat. Silakan setup database.");
            }
            throw error;
        }

        setSuccessModal({ isOpen: true, title: 'Distribusi Berhasil', message: msg || 'Bonus telah didistribusikan.' });
        setIsBonusModalOpen(false);
        
        // Auto regenerate recap to reflect changes
        await executeGenerate();

    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Distribusi', message: error.message });
    } finally {
        setIsDistributing(false);
    }
  };

  // --- GENERATE RECAP ---
  const handleGenerate = () => {
    if (!selectedMonth) {
        alert("Silakan pilih bulan terlebih dahulu.");
        return;
    }

    setConfirmModal({
        isOpen: true,
        title: 'Generate Rekap Gaji?',
        message: `Sistem akan mengambil data terbaru dari Gaji Harian & Borongan untuk bulan **${selectedMonth}** dan menggabungkannya ke tabel rekap.\n\nData lama di tabel rekap untuk bulan ini akan ditimpa.`,
        confirmLabel: 'Ya, Generate',
        onConfirm: executeGenerate
    });
  };

  const executeGenerate = async () => {
    setConfirmModal({ ...confirmModal, isOpen: false });
    setIsGenerating(true);
    
    try {
        const { data: msg, error } = await supabase.rpc('generate_rekap_gaji_harian', { p_bulan: selectedMonth });
        
        if (error) throw error;

        setSuccessModal({ isOpen: true, title: 'Berhasil', message: msg || 'Rekap gaji berhasil dibuat.' });
        fetchData();
    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Generate', message: error.message });
    } finally {
        setIsGenerating(false);
    }
  };

  const handleExport = () => {
    if (data.length === 0) return;
    const exportData = filteredData.map((item, idx) => ({
        'No': idx + 1,
        'Bulan': item.bulan,
        'Periode': item.periode,
        'Perusahaan': item.perusahaan,
        'Kode': item.kode,
        'Nama': item.nama,
        'Divisi': item.divisi,
        'Grade': item.grade,
        'Total Hadir (H)': item.total_h,
        'Upah Borongan': item.display_upah,
        'Bonus': item.total_bonus,
        'Total Diterima': item.total_terima
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(exportData);
    const wscols = Object.keys(exportData[0]).map(k => ({ wch: k.length + 5 }));
    ws['!cols'] = wscols;
    XLSX.utils.book_append_sheet(wb, ws, "Rekap Borongan");
    XLSX.writeFile(wb, `Rekap_Gaji_Borongan_${selectedMonth || 'Semua_Bulan'}.xlsx`);
  };

  const handleNameClick = async (item: any) => {
    setSelectedEmployee(item);
    try {
        const { data: daily, error } = await supabase
            .from(boronganTable)
            .select('*')
            .eq('kode', item.kode)
            .eq('bulan', item.bulan)
            .eq('periode', item.periode)
            .order('tanggal', { ascending: true });
        
        if (error) throw error;
        setEmployeeDailyData(daily || []);
        setDetailModalOpen(true);
    } catch (err) {
        console.error("Error fetching details", err);
        alert("Gagal memuat rincian data.");
    }
  };

  return (
    <div className="space-y-6 h-full flex flex-col font-sans">
      {/* --- HEADER & TOOLBAR --- */}
      <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
        <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 mb-4">
            <div>
                <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
                    <FileText className="text-erp-pink"/> Rekap Gaji Borongan
                </h3>
                <p className="text-xs text-gray-500">Rekapitulasi total gaji borongan per karyawan</p>
            </div>
            <div className="flex gap-2">
                {/* NEW: Button Distribusi Bonus */}
                <button 
                    onClick={() => setIsBonusModalOpen(true)} 
                    disabled={!selectedMonth}
                    className="px-4 py-2 bg-purple-50 text-purple-700 border border-purple-200 rounded-lg hover:bg-purple-100 shadow-sm flex items-center gap-2 text-sm font-medium transition-colors disabled:opacity-50"
                >
                    <Coins size={16}/> Distribusi Bonus
                </button>

                <button 
                    onClick={handleGenerate} 
                    disabled={isGenerating || !selectedMonth}
                    className="px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 shadow-sm flex items-center gap-2 text-sm font-medium transition-colors disabled:opacity-50"
                >
                    {isGenerating ? <Loader2 className="animate-spin" size={16}/> : <Calculator size={16}/>}
                    Generate Rekap
                </button>

                <button 
                    onClick={() => fetchData()} 
                    disabled={isLoading}
                    className="px-3 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm transition-colors flex items-center gap-2 text-sm font-medium" 
                >
                    {isLoading ? <Loader2 className="animate-spin" size={16}/> : <RefreshCw size={16}/>} Refresh
                </button>
                <button onClick={handleExport} className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-green-700 shadow-sm transition-colors">
                    <Download size={16}/> Export Excel
                </button>
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                <input 
                    type="text" 
                    placeholder="Cari Nama / Kode..." 
                    value={searchTerm} 
                    onChange={e => setSearchTerm(e.target.value)} 
                    className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-erp-pink" 
                />
            </div>
            
            <select value={selectedMonth} onChange={e => setSelectedMonth(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="">Semua Bulan</option>
                {uniqueMonths.map(m => <option key={m} value={m}>{m}</option>)}
            </select>

            <select value={selectedPeriod} onChange={e => setSelectedPeriod(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="Semua Periode">Semua Periode</option>
                <option value="Periode 1">Periode 1</option>
                <option value="Periode 2">Periode 2</option>
            </select>

            <select value={selectedCompany} onChange={e => setSelectedCompany(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="Semua Perusahaan">Semua Perusahaan</option>
                {uniqueCompanies.map(c => <option key={c} value={c}>{c}</option>)}
            </select>

            <select value={selectedDivision} onChange={e => setSelectedDivision(e.target.value)} className="px-3 py-2 border border-gray-200 rounded-lg text-sm outline-none cursor-pointer bg-white">
                <option value="Semua Divisi">Semua Divisi</option>
                {uniqueDivisions.map(d => <option key={d} value={d}>{d}</option>)}
            </select>
        </div>
      </div>

      {/* --- SUMMARY CARDS --- */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="bg-white p-4 rounded-xl border border-blue-100 shadow-sm">
              <p className="text-xs text-gray-500 uppercase font-bold">Total Karyawan</p>
              <p className="text-2xl font-bold text-blue-600">{filteredData.length}</p>
          </div>
          <div className="bg-white p-4 rounded-xl border border-green-100 shadow-sm">
              <p className="text-xs text-gray-500 uppercase font-bold">Total Upah</p>
              <p className="text-2xl font-bold text-green-600">{formatRupiah(totals.gaji)}</p>
          </div>
          <div className="bg-white p-4 rounded-xl border border-purple-100 shadow-sm">
              <p className="text-xs text-gray-500 uppercase font-bold">Total Bonus</p>
              <p className="text-2xl font-bold text-purple-600">{formatRupiah(totals.bonus)}</p>
          </div>
          <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm bg-gray-50">
              <p className="text-xs text-gray-500 uppercase font-bold">Total Dibayarkan</p>
              <p className="text-2xl font-bold text-gray-800">{formatRupiah(totals.terima)}</p>
          </div>
      </div>

      {/* --- TABLE --- */}
      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm flex-1 flex flex-col min-h-0">
        <div className="overflow-auto max-h-[600px] custom-scrollbar relative">
          <table className="w-full text-xs text-left whitespace-nowrap relative border-collapse">
            <thead className="bg-gray-100 text-gray-600 font-bold sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100 w-10 text-center">No</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100">Bulan</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100">Periode</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100">Kode</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100 min-w-[150px]">Nama Karyawan</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100">Perusahaan</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100">Divisi</th>
                <th className="px-4 py-3 border-r border-gray-200 bg-gray-100 text-center">Hadir (H)</th>
                <th className="px-4 py-3 text-right bg-green-50 border-r border-green-100 text-green-800">Upah Borongan</th>
                <th className="px-4 py-3 text-right bg-green-50 border-r border-green-100 text-green-800">Bonus</th>
                <th className="px-4 py-3 text-right bg-gray-100 font-bold text-gray-900 border-l border-gray-200">Total Diterima</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {isLoading ? (
                <tr><td colSpan={11} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat data...</td></tr>
              ) : filteredData.length > 0 ? (
                filteredData.map((item, idx) => (
                  <tr key={`${item.kode}-${item.periode}-${item.bulan}-${idx}`} className="hover:bg-gray-50 transition-colors">
                    <td className="px-4 py-2 border-r border-gray-100 text-center text-gray-500">{idx + 1}</td>
                    <td className="px-4 py-2 border-r border-gray-100 text-gray-600">{item.bulan}</td>
                    <td className="px-4 py-2 border-r border-gray-100 text-gray-600">{item.periode}</td>
                    <td className="px-4 py-2 border-r border-gray-100 font-mono text-gray-500">{item.kode}</td>
                    <td 
                        className="px-4 py-2 border-r border-gray-100 font-bold text-blue-600 cursor-pointer hover:underline hover:text-blue-800"
                        onClick={() => handleNameClick(item)}
                    >
                        {item.nama}
                    </td>
                    <td className="px-4 py-2 border-r border-gray-100 text-gray-600">{item.perusahaan}</td>
                    <td className="px-4 py-2 border-r border-gray-100 text-gray-600">{item.divisi}</td>
                    <td className="px-4 py-2 border-r border-gray-100 text-center text-gray-600">
                        <span className="flex items-center justify-center gap-1">
                            <UserCheck size={12} className="text-blue-500"/> {item.total_h}
                        </span>
                    </td>
                    <td className="px-4 py-2 text-right border-r border-green-50 bg-green-50/10 font-medium">{formatRupiah(item.display_upah)}</td>
                    <td className="px-4 py-2 text-right border-r border-green-50 bg-green-50/10">{formatRupiah(item.total_bonus)}</td>
                    <td className="px-4 py-2 text-right font-bold text-gray-900 bg-gray-50/50 border-l border-gray-200">{formatRupiah(item.total_terima)}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={11} className="p-16 text-center text-gray-400 italic">
                    <div className="flex flex-col items-center gap-2">
                        <Database size={32} className="text-gray-300"/>
                        <p>{selectedMonth ? 'Tidak ada data rekap untuk filter ini.' : 'Pilih bulan untuk melihat data.'}</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* DETAIL MODAL */}
      <WholesaleRecapDetailModal 
        isOpen={detailModalOpen}
        onClose={() => setDetailModalOpen(false)}
        employee={selectedEmployee}
        dailyData={employeeDailyData}
      />

      {/* BONUS DISTRIBUTION MODAL */}
      {isBonusModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-purple-50">
              <h3 className="font-bold text-lg text-purple-800 flex items-center gap-2">
                <Coins size={20}/> Distribusi Bonus Manual
              </h3>
              <button onClick={() => setIsBonusModalOpen(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-sm text-gray-600 mb-4">
                Masukkan total bonus yang ingin dibagikan untuk bulan <b>{selectedMonth}</b>. 
                Sistem akan membaginya secara proporsional berdasarkan kehadiran.
              </p>
              
              <div className="mb-4">
                <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Total Bonus (Rp)</label>
                <input 
                    type="number" 
                    value={targetBonusTotal} 
                    onChange={(e) => setTargetBonusTotal(e.target.value)} 
                    className="w-full px-4 py-3 border border-gray-300 rounded-xl text-lg font-bold text-gray-800 focus:ring-2 focus:ring-purple-500 outline-none"
                />
                <p className="text-xs text-gray-400 mt-1">Contoh: 575000</p>
              </div>

              <div className="flex justify-end gap-3">
                <button 
                    onClick={() => setIsBonusModalOpen(false)} 
                    className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm font-medium"
                >
                    Batal
                </button>
                <button 
                    onClick={handleDistributeBonus} 
                    disabled={isDistributing}
                    className="bg-purple-600 text-white px-6 py-2 rounded-lg text-sm font-bold flex items-center gap-2 hover:bg-purple-700 shadow-md transition-all disabled:opacity-70"
                >
                    {isDistributing ? <Loader2 className="animate-spin" size={16}/> : <CheckCircle2 size={16}/>}
                    Proses Distribusi
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SQL FIX MODAL */}
      {showSqlModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-blue-50">
              <h3 className="font-bold text-lg text-blue-800 flex items-center gap-2">
                <Database size={20}/> Setup Database Function
              </h3>
              <button onClick={() => setShowSqlModal(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-gray-600 text-sm mb-4">
                Fungsi database belum lengkap. Salin kode SQL di bawah ini dan jalankan di <b>Supabase SQL Editor</b>.
              </p>
              
              <div className="relative">
                <textarea 
                  className="w-full h-64 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-erp-pink outline-none"
                  readOnly
                  value={sqlSetupCode}
                  onClick={(e) => e.currentTarget.select()}
                />
                <button 
                  onClick={handleCopySQL}
                  className="absolute top-2 right-2 p-2 bg-white rounded-md shadow-sm border border-gray-200 hover:bg-gray-50 text-gray-600"
                  title="Salin Kode"
                >
                  <Copy size={16}/>
                </button>
              </div>

              <div className="mt-4 flex justify-end gap-3">
                <button 
                    onClick={() => setShowSqlModal(false)} 
                    className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm font-medium"
                >
                    Tutup
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal 
        isOpen={confirmModal.isOpen} 
        onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} 
        onConfirm={confirmModal.onConfirm} 
        title={confirmModal.title} 
        message={confirmModal.message} 
        confirmLabel={confirmModal.confirmLabel}
        isDangerous={false}
      />
    </div>
  );
};
