import React, { useState, useEffect, useRef, useMemo } from 'react';
import { 
  Save, Search, Filter, Download, Upload, FileSpreadsheet, 
  Loader2, RefreshCw, Trash2, Edit2, Calendar, Database,
  Plus, X, PenTool, Users, Building2, Layers, Tag, AlertCircle, Copy,
  Wrench, LayoutList, CheckSquare, ChevronLeft, ChevronRight
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import * as XLSX from 'xlsx';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';
import { ConfirmationModal } from '../../Warehouse/ConfirmationModal';

export const ProductionInput: React.FC = () => {
  // --- TAB STATE ---
  const [activeTab, setActiveTab] = useState<'maintenance' | 'produksi'>('maintenance');
  const topRef = useRef<HTMLDivElement>(null); // Ref for scrolling

  // --- SHARED STATE ---
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [useMockData, setUseMockData] = useState(false);
  const [showSqlModal, setShowSqlModal] = useState(false);
  
  // Pagination State
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(50);
  const [totalData, setTotalData] = useState(0);
  const [totalQty, setTotalQty] = useState(0); // NEW: Total Qty State

  // Selection State
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [isDeleting, setIsDeleting] = useState(false);
  
  // Import State
  const [isImporting, setIsImporting] = useState(false);
  const [importProgress, setImportProgress] = useState('');
  
  // --- PRODUCTION STATE ---
  const [prodData, setProdData] = useState<any[]>([]);
  const [prodFormData, setProdFormData] = useState({
    id: null as number | null,
    tanggal: new Date().toISOString().split('T')[0],
    bulan: '', // Added Bulan
    kode: '',
    sku: '',
    qty: '',
    jumlah_orang: '',
    perusahaan: '',
    bagian: '',
    posisi: ''
  });
  const [prodSearch, setProdSearch] = useState('');
  const [prodStartDate, setProdStartDate] = useState('');
  const [prodEndDate, setProdEndDate] = useState('');
  const [prodFilterBagian, setProdFilterBagian] = useState(''); // NEW: Filter Bagian
  const [uniqueBagian, setUniqueBagian] = useState<string[]>([]); // NEW: Options for Bagian

  // --- MAINTENANCE STATE ---
  const [maintData, setMaintData] = useState<any[]>([]);
  const [maintFormData, setMaintFormData] = useState({
    id: null as number | null,
    tanggal: new Date().toISOString().split('T')[0],
    bulan: '', 
    kode: '',
    sku: '', 
    qty: ''
  });
  const [maintSearch, setMaintSearch] = useState('');
  const [maintStartDate, setMaintStartDate] = useState('');
  const [maintEndDate, setMaintEndDate] = useState('');

  // --- MODALS ---
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ 
    isOpen: boolean; 
    onConfirm: () => void; 
    title?: string; 
    message?: string; 
    confirmLabel?: string; 
    isDangerous?: boolean;
    isLoading?: boolean; // Added isLoading support
  }>({ isOpen: false, onConfirm: () => {} });

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Helper: Fetch with Retry
  const fetchWithRetry = async <T,>(fn: () => Promise<{ data: T | null; error: any; count?: number | null }>, retries = 3, delay = 1000): Promise<{ data: T | null; error: any; count?: number | null }> => {
    for (let i = 0; i < retries; i++) {
      try {
        const result = await fn();
        if (result.error) throw result.error;
        return result;
      } catch (error: any) {
        if (i === retries - 1) return { data: null, error, count: 0 };
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }
    return { data: null, error: new Error('Max retries reached'), count: 0 };
  };

  // --- SQL SETUP CODE ---
  const sqlSetupCode = `
-- 1. Table: input_data_produksi
CREATE TABLE IF NOT EXISTS public.input_data_produksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    bulan TEXT, -- Added Bulan
    kode TEXT,
    sku TEXT,
    qty NUMERIC DEFAULT 0,
    jumlah_orang NUMERIC DEFAULT 0,
    perusahaan TEXT,
    bagian TEXT,
    posisi TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure column exists if table already created
ALTER TABLE public.input_data_produksi ADD COLUMN IF NOT EXISTS bulan TEXT;

-- 2. Table: input_maintenance
CREATE TABLE IF NOT EXISTS public.input_maintenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    sku TEXT,
    bulan TEXT, 
    qty NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_tanggal_kode UNIQUE (tanggal, kode)
);

-- Security
ALTER TABLE public.input_data_produksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.input_maintenance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access Prod" ON public.input_data_produksi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Maint" ON public.input_maintenance FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.input_data_produksi TO anon, authenticated, service_role;
GRANT ALL ON public.input_maintenance TO anon, authenticated, service_role;
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlSetupCode);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
  };

  // --- HELPER: AUTO MONTH ---
  const getMonthFromDate = (dateStr: string) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleString('id-ID', { month: 'long', year: 'numeric' });
  };

  // Auto-fill Bulan when Tanggal changes in Maintenance Form
  useEffect(() => {
    if (maintFormData.tanggal) { 
        setMaintFormData(prev => ({ ...prev, bulan: getMonthFromDate(prev.tanggal) }));
    }
  }, [maintFormData.tanggal]);

  // Auto-fill Bulan when Tanggal changes in Production Form
  useEffect(() => {
    if (prodFormData.tanggal) { 
        setProdFormData(prev => ({ ...prev, bulan: getMonthFromDate(prev.tanggal) }));
    }
  }, [prodFormData.tanggal]);

  // --- FETCH UNIQUE BAGIAN (FIXED: Loop to get ALL data) ---
  useEffect(() => {
    const fetchUniqueBagian = async () => {
        if (!isSupabaseConfigured()) return;
        
        let allBagian: string[] = [];
        let from = 0;
        const step = 1000;
        let hasMore = true;

        try {
            while (hasMore) {
                const { data, error } = await supabase
                    .from('input_data_produksi')
                    .select('bagian')
                    .range(from, from + step - 1);
                
                if (error) throw error;

                if (data && data.length > 0) {
                    // Collect non-null/non-empty values
                    const batchBagian = data.map(item => item.bagian).filter(b => b && b.trim() !== '');
                    allBagian = [...allBagian, ...batchBagian];
                    
                    if (data.length < step) {
                        hasMore = false;
                    } else {
                        from += step;
                    }
                } else {
                    hasMore = false;
                }
            }

            // Deduplicate and sort
            const unique = [...new Set(allBagian)].sort();
            setUniqueBagian(unique);
        } catch (err) {
            console.error("Error fetching bagian options:", err);
        }
    };
    fetchUniqueBagian();
  }, []);

  // --- FETCH DATA ---
  const fetchProductionData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    setSelectedIds([]); // Reset selection
    
    if (!isSupabaseConfigured()) {
      setUseMockData(true);
      setIsLoading(false);
      return;
    }

    try {
      const from = (page - 1) * pageSize;
      const to = from + pageSize - 1;

      const { data, error, count } = await fetchWithRetry(async () => {
        let query = supabase
          .from('input_data_produksi')
          .select('*', { count: 'exact' });

        if (prodSearch) {
          query = query.or(`kode.ilike.%${prodSearch}%,sku.ilike.%${prodSearch}%,perusahaan.ilike.%${prodSearch}%`);
        }
        if (prodStartDate) query = query.gte('tanggal', prodStartDate);
        if (prodEndDate) query = query.lte('tanggal', prodEndDate);
        if (prodFilterBagian) query = query.eq('bagian', prodFilterBagian); // NEW FILTER

        return await query
          .order('tanggal', { ascending: false })
          .order('created_at', { ascending: false })
          .range(from, to);
      });

      if (error) {
        if (error.code === '42P01') setIsTableMissing(true);
        else throw error;
      } else {
        setProdData(data || []);
        setTotalData(count || 0);
      }
    } catch (error: any) {
      console.error("Fetch Prod Error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const fetchMaintenanceData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    setSelectedIds([]); // Reset selection

    if (!isSupabaseConfigured()) return;

    try {
      const from = (page - 1) * pageSize;
      const to = from + pageSize - 1;

      const { data, error, count } = await fetchWithRetry(async () => {
        let query = supabase
          .from('input_maintenance')
          .select('*', { count: 'exact' });

        if (maintSearch) {
          query = query.or(`kode.ilike.%${maintSearch}%,sku.ilike.%${maintSearch}%`);
        }
        if (maintStartDate) query = query.gte('tanggal', maintStartDate);
        if (maintEndDate) query = query.lte('tanggal', maintEndDate);

        return await query
          .order('tanggal', { ascending: false })
          .range(from, to);
      });

      if (error) {
        if (error.code === '42P01') setIsTableMissing(true);
        else throw error;
      } else {
        setMaintData(data || []);
        setTotalData(count || 0);
      }
    } catch (error: any) {
      console.error("Fetch Maint Error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  // --- CALCULATE TOTAL QTY ---
  const calculateTotalQty = async () => {
    if (!isSupabaseConfigured()) return;
    
    const tableName = activeTab === 'produksi' ? 'input_data_produksi' : 'input_maintenance';
    let query = supabase.from(tableName).select('qty');

    // Apply same filters as main fetch
    if (activeTab === 'produksi') {
        if (prodSearch) {
          query = query.or(`kode.ilike.%${prodSearch}%,sku.ilike.%${prodSearch}%,perusahaan.ilike.%${prodSearch}%`);
        }
        if (prodStartDate) query = query.gte('tanggal', prodStartDate);
        if (prodEndDate) query = query.lte('tanggal', prodEndDate);
        if (prodFilterBagian) query = query.eq('bagian', prodFilterBagian); // NEW FILTER
    } else {
        if (maintSearch) {
          query = query.or(`kode.ilike.%${maintSearch}%,sku.ilike.%${maintSearch}%`);
        }
        if (maintStartDate) query = query.gte('tanggal', maintStartDate);
        if (maintEndDate) query = query.lte('tanggal', maintEndDate);
    }

    const { data } = await query;
    if (data) {
        const sum = data.reduce((acc, curr) => acc + (Number(curr.qty) || 0), 0);
        setTotalQty(sum);
    } else {
        setTotalQty(0);
    }
  };

  // Reset page when filters or tab change
  useEffect(() => {
    setPage(1);
  }, [activeTab, prodSearch, prodStartDate, prodEndDate, prodFilterBagian, maintSearch, maintStartDate, maintEndDate]);

  // Fetch when page/size changes
  useEffect(() => {
    if (activeTab === 'produksi') fetchProductionData();
    else fetchMaintenanceData();
  }, [activeTab, page, pageSize, prodSearch, prodStartDate, prodEndDate, prodFilterBagian, maintSearch, maintStartDate, maintEndDate]);

  // Calculate Total Qty when filters change (Debounced implicitly by state updates)
  useEffect(() => {
    calculateTotalQty();
  }, [activeTab, prodSearch, prodStartDate, prodEndDate, prodFilterBagian, maintSearch, maintStartDate, maintEndDate]);


  // --- SELECTION LOGIC ---
  const currentData = activeTab === 'produksi' ? prodData : maintData;
  
  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      setSelectedIds(currentData.map(item => item.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelectOne = (id: number) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(prev => prev.filter(i => i !== id));
    } else {
      setSelectedIds(prev => [...prev, id]);
    }
  };

  const isAllSelected = currentData.length > 0 && selectedIds.length === currentData.length;

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;

    setConfirmModal({
      isOpen: true,
      title: 'Hapus Massal',
      message: `Yakin ingin menghapus ${selectedIds.length} data terpilih?`,
      confirmLabel: 'Hapus Semua',
      isDangerous: true,
      isLoading: false,
      onConfirm: async () => {
        setConfirmModal(prev => ({ ...prev, isLoading: true }));
        try {
          const tableName = activeTab === 'produksi' ? 'input_data_produksi' : 'input_maintenance';
          const { error } = await supabase.from(tableName).delete().in('id', selectedIds);
          
          if (error) throw error;
          
          setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data terpilih telah dihapus.' });
          
          if (activeTab === 'produksi') {
              await fetchProductionData();
          } else {
              await fetchMaintenanceData();
          }
          await calculateTotalQty(); // Refresh total qty
          
        } catch (error: any) {
          setErrorModal({ isOpen: true, title: 'Gagal Hapus', message: error.message });
        } finally {
          setConfirmModal(prev => ({ ...prev, isOpen: false, isLoading: false }));
        }
      }
    });
  };

  // --- HANDLERS: PRODUCTION ---
  const handleProdSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (useMockData) { alert("Mode Preview: Data tidak disimpan."); return; }

    setIsSaving(true);
    try {
      const payload = {
        tanggal: prodFormData.tanggal,
        bulan: prodFormData.bulan, // Save Bulan
        kode: prodFormData.kode,
        sku: prodFormData.sku,
        qty: Number(prodFormData.qty) || 0,
        jumlah_orang: Number(prodFormData.jumlah_orang) || 0,
        perusahaan: prodFormData.perusahaan,
        bagian: prodFormData.bagian,
        posisi: prodFormData.posisi,
        updated_at: new Date().toISOString()
      };

      if (prodFormData.id) {
        const { error } = await supabase.from('input_data_produksi').update(payload).eq('id', prodFormData.id);
        if (error) throw error;
      } else {
        const { error } = await supabase.from('input_data_produksi').insert([payload]);
        if (error) throw error;
      }

      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data produksi disimpan.' });
      setProdFormData({ ...prodFormData, id: null, kode: '', sku: '', qty: '', jumlah_orang: '', perusahaan: '', bagian: '', posisi: '' }); // Keep date/month
      fetchProductionData();
      calculateTotalQty();
    } catch (error: any) {
      setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  const handleProdEdit = (item: any) => {
    setProdFormData({
      id: item.id,
      tanggal: item.tanggal,
      bulan: item.bulan || getMonthFromDate(item.tanggal), // Edit Bulan
      kode: item.kode || '',
      sku: item.sku || '',
      qty: item.qty?.toString() || '',
      jumlah_orang: item.jumlah_orang?.toString() || '',
      perusahaan: item.perusahaan || '',
      bagian: item.bagian || '',
      posisi: item.posisi || ''
    });
    // Scroll to top using ref
    topRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleProdDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Data Produksi',
      message: 'Yakin ingin menghapus data ini?',
      isDangerous: true,
      isLoading: false,
      onConfirm: async () => {
        setConfirmModal(prev => ({ ...prev, isLoading: true }));
        const { error } = await supabase.from('input_data_produksi').delete().eq('id', id);
        if (error) setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
        else {
            await fetchProductionData();
            await calculateTotalQty();
            setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data dihapus.' });
        }
        setConfirmModal(prev => ({ ...prev, isOpen: false, isLoading: false }));
      }
    });
  };

  // --- HANDLERS: MAINTENANCE ---
  const handleMaintSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (useMockData) return;

    setIsSaving(true);
    try {
      const payload = {
        tanggal: maintFormData.tanggal,
        bulan: maintFormData.bulan, // Save Bulan
        kode: maintFormData.kode,
        sku: maintFormData.sku, 
        qty: Number(maintFormData.qty) || 0,
        updated_at: new Date().toISOString()
      };

      if (maintFormData.id) {
        const { error } = await supabase.from('input_maintenance').update(payload).eq('id', maintFormData.id);
        if (error) {
            if (error.code === '23505') throw new Error('Data dengan tanggal dan kode yang sama sudah ada!');
            throw error;
        }
      } else {
        const { error } = await supabase.from('input_maintenance').insert([payload]);
        if (error) {
            if (error.code === '23505') throw new Error('Data dengan tanggal dan kode yang sama sudah ada!');
            throw error;
        }
      }

      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data maintenance disimpan.' });
      setMaintFormData({ ...maintFormData, id: null, kode: '', sku: '', qty: '' }); // Keep date/month
      fetchMaintenanceData();
      calculateTotalQty();
    } catch (error: any) {
      setErrorModal({ isOpen: true, title: 'Gagal Simpan', message: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  const handleMaintEdit = (item: any) => {
    setMaintFormData({
      id: item.id,
      tanggal: item.tanggal,
      bulan: item.bulan || getMonthFromDate(item.tanggal), // Edit Bulan
      kode: item.kode,
      sku: item.sku || '', 
      qty: item.qty.toString()
    });
    // Scroll to top using ref
    topRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleMaintDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Data Maintenance',
      message: 'Yakin ingin menghapus data ini?',
      isDangerous: true,
      isLoading: false,
      onConfirm: async () => {
        setConfirmModal(prev => ({ ...prev, isLoading: true }));
        const { error } = await supabase.from('input_maintenance').delete().eq('id', id);
        if (error) setErrorModal({ isOpen: true, title: 'Gagal', message: error.message });
        else {
            await fetchMaintenanceData();
            await calculateTotalQty();
            setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data dihapus.' });
        }
        setConfirmModal(prev => ({ ...prev, isOpen: false, isLoading: false }));
      }
    });
  };

  // --- TEMPLATE & IMPORT HANDLERS ---
  const handleDownloadTemplate = () => {
    const isProd = activeTab === 'produksi';
    let template = [];
    let fileName = '';

    if (isProd) {
      template = [{
        'Tanggal': new Date().toISOString().split('T')[0],
        'Bulan': 'Oktober 2025', // Add Bulan to Template
        'Kode': 'P001',
        'SKU': 'SKU-A',
        'Qty': 100,
        'Jumlah Orang': 5,
        'Perusahaan': 'CV GARUT',
        'Bagian': 'Sewing',
        'Posisi': 'Operator'
      }];
      fileName = 'Template_Input_Produksi.xlsx';
    } else {
      template = [{
        'Tanggal': new Date().toISOString().split('T')[0],
        'Bulan': 'Oktober 2025', 
        'Kode': 'M-001',
        'SKU': 'PART-X',
        'Qty': 1
      }];
      fileName = 'Template_Input_Maintenance.xlsx';
    }

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(template);
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, fileName);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (evt) => {
      const bstr = evt.target?.result;
      const wb = XLSX.read(bstr, { type: 'array' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const jsonData = XLSX.utils.sheet_to_json(ws);

      if (jsonData.length === 0) {
        setErrorModal({ isOpen: true, title: 'File Kosong', message: 'File Excel tidak memiliki data.' });
        if (fileInputRef.current) fileInputRef.current.value = '';
        return;
      }

      setIsImporting(true);
      try {
        const isProd = activeTab === 'produksi';
        const itemsToInsert: any[] = [];
        const skippedItems: string[] = [];
        
        // Helper date parser
        const parseDate = (val: any) => {
             if (!val) return new Date().toISOString().split('T')[0];
             if (typeof val === 'number') {
                 return new Date(Math.round((val - 25569) * 86400 * 1000)).toISOString().split('T')[0];
             }
             return val; // Assume string YYYY-MM-DD
        };

        // 1. VALIDATION: If Production Import, fetch valid codes from Maintenance
        let validMaintenanceCodes = new Set<string>();
        if (isProd) {
            setImportProgress('Memvalidasi Kode...');
            const { data: maintData, error: maintError } = await supabase
                .from('input_maintenance')
                .select('kode');
            
            if (maintError) throw new Error(`Gagal validasi maintenance: ${maintError.message}`);
            
            if (maintData) {
                maintData.forEach(m => validMaintenanceCodes.add(m.kode.toString().trim().toUpperCase()));
            }
        }

        setImportProgress('Memproses Data...');

        for (const row: any of jsonData) {
            const tanggal = parseDate(row['Tanggal']);
            const kode = (row['Kode'] || '').toString().trim();
            const sku = (row['SKU'] || '').toString().trim();
            const qty = Number(row['Qty'] || 0);
            
            // Logic Bulan: Ambil dari Excel jika ada, jika tidak auto-generate dari Tanggal
            const bulan = row['Bulan'] ? row['Bulan'].toString().trim() : getMonthFromDate(tanggal);

            if (!kode) continue;

            if (isProd) {
                // VALIDATION CHECK: Kode must exist in Maintenance
                if (!validMaintenanceCodes.has(kode.toUpperCase())) {
                    skippedItems.push(kode);
                    continue; // Skip this row
                }

                itemsToInsert.push({
                    tanggal,
                    bulan,
                    kode,
                    sku,
                    qty,
                    jumlah_orang: Number(row['Jumlah Orang'] || row['Orang'] || 0),
                    perusahaan: (row['Perusahaan'] || '').toString(),
                    bagian: (row['Bagian'] || '').toString(),
                    posisi: (row['Posisi'] || '').toString(),
                    updated_at: new Date().toISOString()
                });
            } else {
                // Maintenance Import (No validation against itself)
                itemsToInsert.push({
                    tanggal,
                    bulan, 
                    kode,
                    sku,
                    qty,
                    updated_at: new Date().toISOString()
                });
            }
        }

        if (itemsToInsert.length === 0) {
            if (skippedItems.length > 0) {
                throw new Error(`Semua data (${skippedItems.length}) ditolak karena Kode tidak ditemukan di Input Maintenance.`);
            }
            throw new Error("Tidak ada data valid untuk diimport (Kode wajib diisi).");
        }

        setImportProgress('Menyimpan...');

        const tableName = isProd ? 'input_data_produksi' : 'input_maintenance';
        
        // Use upsert to handle duplicates gracefully (or handle error for maintenance)
        const { error } = await supabase.from(tableName).upsert(itemsToInsert, isProd ? undefined : { onConflict: 'tanggal,kode' });

        if (error) throw error;

        // Success Message with Skipped Info
        let successMsg = `Berhasil mengimport ${itemsToInsert.length} data.`;
        if (skippedItems.length > 0) {
            successMsg += `\n\n⚠️ ${skippedItems.length} data DILEWATI karena Kode tidak ditemukan di Maintenance:\n${skippedItems.slice(0, 5).join(', ')}${skippedItems.length > 5 ? ', ...' : ''}`;
            setSuccessModal({ isOpen: true, title: 'Import Selesai (Sebagian)', message: successMsg });
        } else {
            setSuccessModal({ isOpen: true, title: 'Import Berhasil', message: successMsg });
        }

        if (isProd) fetchProductionData(); else fetchMaintenanceData();
        calculateTotalQty();

      } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Import', message: error.message });
      } finally {
        setIsImporting(false);
        setImportProgress('');
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  // --- EXPORT ---
  const handleExport = async () => {
    setIsLoading(true); // Show loading indicator
    try {
        const isProd = activeTab === 'produksi';
        let allData: any[] = [];
        
        // CASE 1: Export Selected IDs
        if (selectedIds.length > 0) {
            const tableName = isProd ? 'input_data_produksi' : 'input_maintenance';
            const { data, error } = await supabase
                .from(tableName)
                .select('*')
                .in('id', selectedIds)
                .order('tanggal', { ascending: false });
            
            if (error) throw error;
            allData = data || [];
        } 
        // CASE 2: Export All Matching Filters
        else {
            let from = 0;
            const step = 1000;
            let hasMore = true;
            
            while (hasMore) {
                let query = supabase.from(isProd ? 'input_data_produksi' : 'input_maintenance').select('*');
                
                // Apply Filters
                if (isProd) {
                    if (prodSearch) query = query.or(`kode.ilike.%${prodSearch}%,sku.ilike.%${prodSearch}%,perusahaan.ilike.%${prodSearch}%`);
                    if (prodStartDate) query = query.gte('tanggal', prodStartDate);
                    if (prodEndDate) query = query.lte('tanggal', prodEndDate);
                    if (prodFilterBagian) query = query.eq('bagian', prodFilterBagian); // NEW FILTER
                } else {
                    if (maintSearch) query = query.or(`kode.ilike.%${maintSearch}%,sku.ilike.%${maintSearch}%`);
                    if (maintStartDate) query = query.gte('tanggal', maintStartDate);
                    if (maintEndDate) query = query.lte('tanggal', maintEndDate);
                }

                const { data: batch, error } = await query
                    .order('tanggal', { ascending: false })
                    .range(from, from + step - 1);
                
                if (error) throw error;

                if (batch && batch.length > 0) {
                    allData = [...allData, ...batch];
                    from += step;
                    if (batch.length < step) hasMore = false;
                } else {
                    hasMore = false;
                }
            }
        }

        if (allData.length === 0) {
            alert("Tidak ada data untuk diexport.");
            return;
        }

        const exportData = isProd 
            ? allData.map(item => ({
                'Tanggal': item.tanggal, 'Bulan': item.bulan, 'Kode': item.kode, 'SKU': item.sku, 
                'Qty': item.qty, 'Orang': item.jumlah_orang, 
                'Perusahaan': item.perusahaan, 'Bagian': item.bagian, 'Posisi': item.posisi
              }))
            : allData.map(item => ({
                'Tanggal': item.tanggal, 'Bulan': item.bulan, 'Kode': item.kode, 'SKU': item.sku, 'Qty': item.qty
              }));

        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.json_to_sheet(exportData);
        XLSX.utils.book_append_sheet(wb, ws, isProd ? "Produksi" : "Maintenance");
        XLSX.writeFile(wb, `Data_${isProd ? 'Produksi' : 'Maintenance'}_${new Date().toISOString().slice(0,10)}.xlsx`);

    } catch (error: any) {
        setErrorModal({ isOpen: true, title: 'Gagal Export', message: error.message });
    } finally {
        setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6 font-sans" ref={topRef}>
      <input type="file" ref={fileInputRef} onChange={handleImport} className="hidden" accept=".xlsx, .xls" />

      {/* --- TAB NAVIGATION --- */}
      <div className="flex bg-white p-1 rounded-xl shadow-sm border border-gray-200 w-fit">
        <button
          onClick={() => setActiveTab('maintenance')}
          className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-medium transition-all ${
            activeTab === 'maintenance' 
              ? 'bg-erp-pink text-white shadow-sm' 
              : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
          }`}
        >
          <Wrench size={16} /> Input Maintenance
        </button>
        <button
          onClick={() => setActiveTab('produksi')}
          className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-medium transition-all ${
            activeTab === 'produksi' 
              ? 'bg-erp-pink text-white shadow-sm' 
              : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
          }`}
        >
          <PenTool size={16} /> Input Data Produksi
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* --- LEFT COLUMN: FORM --- */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 sticky top-6">
            <div className="flex justify-between items-center mb-5 pb-3 border-b border-gray-100">
              <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                {activeTab === 'produksi' ? <PenTool className="text-erp-pink" size={20}/> : <Wrench className="text-erp-pink" size={20}/>}
                {activeTab === 'produksi' 
                  ? (prodFormData.id ? 'Edit Produksi' : 'Input Produksi') 
                  : (maintFormData.id ? 'Edit Maintenance' : 'Input Maintenance')
                }
              </h2>
              {(activeTab === 'produksi' ? prodFormData.id : maintFormData.id) && (
                  <button 
                    onClick={() => activeTab === 'produksi' 
                        ? setProdFormData({ ...prodFormData, id: null, kode: '', sku: '', qty: '', jumlah_orang: '', perusahaan: '', bagian: '', posisi: '' }) 
                        : setMaintFormData({ ...maintFormData, id: null, kode: '', sku: '', qty: '' })
                    } 
                    className="text-xs text-red-500 hover:text-red-700 flex items-center gap-1 bg-red-50 px-2 py-1 rounded"
                  >
                      <X size={12}/> Batal
                  </button>
              )}
            </div>
            
            {activeTab === 'produksi' ? (
              // --- FORM PRODUKSI ---
              <form onSubmit={handleProdSave} className="space-y-4">
                <div className="grid grid-cols-2 gap-3">
                    <div>
                        <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Tanggal</label>
                        <div className="relative">
                            <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                            <input type="date" name="tanggal" value={prodFormData.tanggal} onChange={e => setProdFormData({...prodFormData, tanggal: e.target.value})} className="w-full pl-9 pr-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none transition-all" required />
                        </div>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Bulan</label>
                        <input type="text" value={prodFormData.bulan} onChange={e => setProdFormData({...prodFormData, bulan: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Contoh: Oktober 2025" />
                    </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Kode</label>
                      <input type="text" value={prodFormData.kode} onChange={e => setProdFormData({...prodFormData, kode: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Kode..." />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">SKU</label>
                      <input type="text" value={prodFormData.sku} onChange={e => setProdFormData({...prodFormData, sku: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="SKU..." />
                    </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Qty Output</label>
                      <input type="number" value={prodFormData.qty} onChange={e => setProdFormData({...prodFormData, qty: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="0" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Jml Orang</label>
                      <input type="number" value={prodFormData.jumlah_orang} onChange={e => setProdFormData({...prodFormData, jumlah_orang: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="0" />
                    </div>
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Perusahaan</label>
                    <div className="relative">
                        <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                        <input type="text" value={prodFormData.perusahaan} onChange={e => setProdFormData({...prodFormData, perusahaan: e.target.value})} className="w-full pl-9 pr-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Nama Perusahaan" />
                    </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Bagian</label>
                      <input type="text" value={prodFormData.bagian} onChange={e => setProdFormData({...prodFormData, bagian: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Contoh: Sewing" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Posisi</label>
                      <input type="text" value={prodFormData.posisi} onChange={e => setProdFormData({...prodFormData, posisi: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Contoh: Operator" />
                    </div>
                </div>
                <div className="pt-4">
                  <button type="submit" disabled={isSaving} className="bg-erp-pink hover:bg-pink-600 text-white w-full py-3 rounded-xl text-sm font-bold flex items-center justify-center gap-2 shadow-md shadow-pink-200 transition-all disabled:opacity-70">
                    {isSaving ? <Loader2 className="animate-spin" size={18}/> : <Save size={18}/>} 
                    {prodFormData.id ? 'Simpan Perubahan' : 'Simpan Data'}
                  </button>
                </div>
              </form>
            ) : (
              // --- FORM MAINTENANCE ---
              <form onSubmit={handleMaintSave} className="space-y-4">
                <div>
                    <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Tanggal</label>
                    <div className="relative">
                        <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                        <input type="date" value={maintFormData.tanggal} onChange={e => setMaintFormData({...maintFormData, tanggal: e.target.value})} className="w-full pl-9 pr-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none transition-all" required />
                    </div>
                </div>
                {/* NEW BULAN FIELD */}
                <div>
                    <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Bulan</label>
                    <input type="text" value={maintFormData.bulan} onChange={e => setMaintFormData({...maintFormData, bulan: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Contoh: November 2025" />
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Kode Item / Mesin</label>
                    <input type="text" value={maintFormData.kode} onChange={e => setMaintFormData({...maintFormData, kode: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Contoh: M-001" required />
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">SKU</label>
                    <input type="text" value={maintFormData.sku} onChange={e => setMaintFormData({...maintFormData, sku: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Contoh: SKU-123" />
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase">Qty Maintenance</label>
                    <input type="number" value={maintFormData.qty} onChange={e => setMaintFormData({...maintFormData, qty: e.target.value})} className="w-full px-3 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="0" required />
                </div>
                <div className="pt-4">
                  <button type="submit" disabled={isSaving} className="bg-erp-pink hover:bg-pink-600 text-white w-full py-3 rounded-xl text-sm font-bold flex items-center justify-center gap-2 shadow-md shadow-pink-200 transition-all disabled:opacity-70">
                    {isSaving ? <Loader2 className="animate-spin" size={18}/> : <Save size={18}/>} 
                    {maintFormData.id ? 'Simpan Perubahan' : 'Simpan Data'}
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>

        {/* --- RIGHT COLUMN: TABLE & FILTER --- */}
        <div className="lg:col-span-8 space-y-6">
          
          {/* Filter & Actions */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-4">
               <div className="flex items-center gap-2 text-gray-800 font-bold text-sm">
                  <Filter size={18} className="text-erp-pink"/> Filter Data {activeTab === 'produksi' ? 'Produksi' : 'Maintenance'}
               </div>
               <div className="flex gap-2">
                  <button onClick={handleDownloadTemplate} className="px-3 py-2 bg-white border border-gray-200 rounded-lg text-xs font-medium hover:bg-gray-50 flex items-center gap-2 transition-colors shadow-sm text-gray-600">
                      <FileSpreadsheet size={14}/> Template
                  </button>
                  <button onClick={() => fileInputRef.current?.click()} className="px-3 py-2 bg-white border border-gray-200 rounded-lg text-xs font-medium hover:bg-gray-50 flex items-center gap-2 transition-colors shadow-sm text-gray-600">
                      {isImporting ? <Loader2 className="animate-spin" size={14}/> : <Upload size={14}/>} {isImporting ? importProgress : 'Import'}
                  </button>
                  <button onClick={handleExport} className="px-3 py-2 bg-green-600 text-white rounded-lg text-xs font-medium hover:bg-green-700 flex items-center gap-2 transition-colors shadow-sm">
                      <Download size={14}/> Export
                  </button>
               </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                  <input 
                    type="text" 
                    value={activeTab === 'produksi' ? prodSearch : maintSearch} 
                    onChange={e => {
                      if (activeTab === 'produksi') setProdSearch(e.target.value);
                      else setMaintSearch(e.target.value);
                      setPage(1); // Reset page on search
                    }} 
                    className="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-erp-pink" 
                    placeholder="Cari kode..." 
                  />
              </div>
              <div className="relative">
                  <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                  <input 
                    type="date" 
                    value={activeTab === 'produksi' ? prodStartDate : maintStartDate} 
                    onChange={e => {
                      if (activeTab === 'produksi') setProdStartDate(e.target.value);
                      else setMaintStartDate(e.target.value);
                      setPage(1); // Reset page on filter
                    }} 
                    className="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-erp-pink" 
                  />
              </div>
              <div className="relative">
                  <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                  <input 
                    type="date" 
                    value={activeTab === 'produksi' ? prodEndDate : maintEndDate} 
                    onChange={e => {
                      if (activeTab === 'produksi') setProdEndDate(e.target.value);
                      else setMaintEndDate(e.target.value);
                      setPage(1); // Reset page on filter
                    }} 
                    className="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-erp-pink" 
                  />
              </div>
              
              {/* NEW FILTER BAGIAN */}
              {activeTab === 'produksi' && (
                   <div className="relative">
                       <Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                       <select
                           value={prodFilterBagian}
                           onChange={e => {
                               setProdFilterBagian(e.target.value);
                               setPage(1);
                           }}
                           className="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-erp-pink appearance-none cursor-pointer"
                       >
                           <option value="">Semua Bagian</option>
                           {uniqueBagian.map(b => (
                               <option key={b} value={b}>{b}</option>
                           ))}
                       </select>
                   </div>
               )}
            </div>
          </div>

          {/* BULK DELETE ACTION */}
          {selectedIds.length > 0 && (
            <div className="bg-red-50 border border-red-100 p-3 rounded-lg flex justify-between items-center animate-fadeIn">
                <div className="flex items-center gap-2 text-red-700 text-sm font-medium">
                    <CheckSquare size={18}/> {selectedIds.length} Data Terpilih
                </div>
                <button 
                    onClick={handleBulkDelete} 
                    disabled={isDeleting}
                    className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-2 shadow-sm transition-colors disabled:opacity-50"
                >
                    {isDeleting ? <Loader2 className="animate-spin" size={14}/> : <Trash2 size={14}/>} Hapus Data
                </button>
            </div>
          )}

          {/* Warning if Mock Data / Table Missing */}
          {(useMockData || isTableMissing) && (
              <div className="bg-yellow-50 border border-yellow-200 text-yellow-800 px-4 py-3 rounded-lg text-sm flex flex-col md:flex-row items-center justify-between gap-3">
                  <div className="flex items-center gap-2">
                      <AlertCircle size={18}/>
                      <span><b>Mode Preview UI:</b> Tabel database belum tersedia. Data di bawah ini adalah contoh (mock data).</span>
                  </div>
                  <button 
                      onClick={() => setShowSqlModal(true)}
                      className="bg-yellow-600 hover:bg-yellow-700 text-white px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-1 shadow-sm transition-colors"
                  >
                      <Database size={14}/> Fix Database
                  </button>
              </div>
          )}

          {/* Table */}
          <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden flex flex-col">
            <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
              <h3 className="font-bold text-gray-700 text-sm">Daftar {activeTab === 'produksi' ? 'Output Produksi' : 'Maintenance'}</h3>
              <div className="text-xs text-gray-500 flex gap-3">
                  <span>Total: <b>{totalData.toLocaleString()}</b> Data</span>
                  <span className="border-l pl-3 border-gray-300">Total Qty: <b>{totalQty.toLocaleString()}</b></span>
              </div>
            </div>
            
            <div className="overflow-auto custom-scrollbar flex-1 max-h-[600px]">
              <table className="w-full text-xs text-left whitespace-nowrap">
                <thead className="bg-white text-gray-600 font-bold border-b border-gray-200 sticky top-0 z-10">
                  <tr>
                    <th className="px-4 py-3 bg-gray-50 w-10 text-center">
                        <input 
                            type="checkbox" 
                            className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                            checked={isAllSelected}
                            onChange={handleSelectAll}
                        />
                    </th>
                    <th className="px-4 py-3 bg-gray-50">Tanggal</th>
                    <th className="px-4 py-3 bg-gray-50">Bulan</th>
                    <th className="px-4 py-3 bg-gray-50">Kode</th>
                    {activeTab === 'produksi' && (
                      <>
                        <th className="px-4 py-3 bg-gray-50">SKU</th>
                        <th className="px-4 py-3 text-right bg-gray-50">Qty</th>
                        <th className="px-4 py-3 text-center bg-gray-50">Orang</th>
                        <th className="px-4 py-3 bg-gray-50">Perusahaan</th>
                        <th className="px-4 py-3 bg-gray-50">Bagian</th>
                        <th className="px-4 py-3 bg-gray-50">Posisi</th>
                      </>
                    )}
                    {activeTab === 'maintenance' && (
                      <>
                        <th className="px-4 py-3 bg-gray-50">SKU</th>
                        <th className="px-4 py-3 text-right bg-gray-50">Qty</th>
                      </>
                    )}
                    <th className="px-4 py-3 text-center bg-gray-50">Aksi</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {isLoading ? (
                    <tr><td colSpan={activeTab === 'maintenance' ? 8 : 12} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink mr-2"/> Memuat...</td></tr>
                  ) : (activeTab === 'produksi' ? prodData : maintData).length > 0 ? (
                    (activeTab === 'produksi' ? prodData : maintData).map((item) => (
                      <tr key={item.id} className={`hover:bg-gray-50 transition-colors ${selectedIds.includes(item.id) ? 'bg-pink-50/30' : ''}`}>
                        <td className="px-4 py-3 text-center">
                            <input 
                                type="checkbox" 
                                className="w-4 h-4 rounded border-gray-300 text-erp-pink focus:ring-erp-pink cursor-pointer"
                                checked={selectedIds.includes(item.id)}
                                onChange={() => handleSelectOne(item.id)}
                            />
                        </td>
                        <td className="px-4 py-3 text-gray-600">{item.tanggal}</td>
                        <td className="px-4 py-3 text-gray-600">{item.bulan || '-'}</td>
                        <td className="px-4 py-3 font-mono text-gray-500 bg-gray-100 rounded px-2 py-0.5 w-fit">{item.kode || '-'}</td>
                        
                        {activeTab === 'produksi' && (
                          <>
                            <td className="px-4 py-3 font-medium text-gray-900">{item.sku}</td>
                            <td className="px-4 py-3 text-right font-bold text-gray-700">{item.qty}</td>
                            <td className="px-4 py-3 text-center">
                              <span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded-full font-bold">{item.jumlah_orang}</span>
                            </td>
                            <td className="px-4 py-3 text-gray-600">{item.perusahaan}</td>
                            <td className="px-4 py-3 text-gray-600">{item.bagian}</td>
                            <td className="px-4 py-3 text-gray-600">{item.posisi}</td>
                          </>
                        )}

                        {activeTab === 'maintenance' && (
                          <>
                            <td className="px-4 py-3 text-gray-600">{item.sku || '-'}</td>
                            <td className="px-4 py-3 text-right font-bold text-gray-700">{item.qty}</td>
                          </>
                        )}

                        <td className="px-4 py-3 text-center">
                          <div className="flex justify-center gap-2">
                            <button onClick={() => activeTab === 'produksi' ? handleProdEdit(item) : handleMaintEdit(item)} className="text-blue-600 hover:bg-blue-50 p-1.5 rounded transition-colors"><Edit2 size={14}/></button>
                            <button onClick={() => activeTab === 'produksi' ? handleProdDelete(item.id) : handleMaintDelete(item.id)} className="text-red-600 hover:bg-red-50 p-1.5 rounded transition-colors"><Trash2 size={14}/></button>
                          </div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr><td colSpan={activeTab === 'maintenance' ? 8 : 12} className="p-16 text-center text-gray-400 italic">Tidak ada data.</td></tr>
                  )}
                </tbody>
              </table>
            </div>
            
            {/* --- PAGINATION CONTROLS --- */}
            <div className="p-4 border-t border-gray-200 bg-gray-50 flex flex-col sm:flex-row justify-between items-center gap-4 text-sm text-gray-600">
              <div className="flex items-center gap-2">
                <span>Menampilkan</span>
                <select
                  value={pageSize}
                  onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}
                  className="border border-gray-300 rounded-lg py-1.5 px-2 bg-white focus:ring-2 focus:ring-erp-pink/50 outline-none cursor-pointer text-xs font-medium"
                >
                  <option value="50">50</option>
                  <option value="100">100</option>
                  <option value="500">500</option>
                  <option value="1000">1000</option>
                </select>
                <span>dari <b>{totalData.toLocaleString()}</b> data</span>
              </div>
              
              <div className="flex items-center gap-2">
                <button 
                  onClick={() => setPage(prev => Math.max(prev - 1, 1))}
                  disabled={page === 1 || isLoading}
                  className="p-2 border border-gray-300 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors bg-white shadow-sm"
                >
                  <ChevronLeft size={16} />
                </button>
                <span className="font-medium px-2">
                  Halaman {page} / {Math.ceil(totalData / pageSize) || 1}
                </span>
                <button 
                  onClick={() => setPage(prev => Math.min(prev + 1, Math.ceil(totalData / pageSize)))}
                  disabled={page >= Math.ceil(totalData / pageSize) || isLoading}
                  className="p-2 border border-gray-300 rounded-lg hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors bg-white shadow-sm"
                >
                  <ChevronRight size={16} />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* SQL FIX MODAL */}
      {showSqlModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-blue-50">
              <h3 className="font-bold text-lg text-blue-800 flex items-center gap-2">
                <Database size={20}/> Setup Database Table
              </h3>
              <button onClick={() => setShowSqlModal(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-gray-600 text-sm mb-4">
                Tabel database belum ditemukan. Salin kode SQL di bawah ini dan jalankan di <b>Supabase SQL Editor</b>.
              </p>
              
              <div className="relative">
                <textarea 
                  className="w-full h-64 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-erp-pink outline-none"
                  readOnly
                  value={sqlSetupCode}
                  onClick={(e) => e.currentTarget.select()}
                />
                <button 
                  onClick={handleCopySQL}
                  className="absolute top-2 right-2 p-2 bg-white rounded-md shadow-sm border border-gray-200 hover:bg-gray-50 text-gray-600"
                  title="Salin Kode"
                >
                  <Copy size={16}/>
                </button>
              </div>

              <div className="mt-4 flex justify-end gap-3">
                <button 
                    onClick={() => setShowSqlModal(false)} 
                    className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm font-medium"
                >
                    Tutup
                </button>
                <button 
                    onClick={() => window.location.reload()} 
                    className="bg-erp-pink text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-pink-600 transition-colors flex items-center gap-2"
                >
                    <RefreshCw size={16}/> Reload Halaman
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal 
        isOpen={confirmModal.isOpen} 
        onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} 
        onConfirm={confirmModal.onConfirm} 
        title={confirmModal.title || "Hapus Data"} 
        message={confirmModal.message || "Yakin ingin menghapus data ini?"} 
        confirmLabel={confirmModal.confirmLabel || "Hapus"} 
        isDangerous={confirmModal.isDangerous !== undefined ? confirmModal.isDangerous : true} 
        isLoading={confirmModal.isLoading} 
      />
    </div>
  );
};
