import React, { useState, useRef, useEffect } from 'react';
import { 
  Plus, Search, Edit2, Trash2, Download, Upload, FileSpreadsheet, 
  Loader2, RefreshCw, Package, Wand2, AlertCircle, Copy, CheckCircle2 
} from 'lucide-react';
import * as XLSX from 'xlsx';
import { SKU } from '../../types';
import { SKUFormModal } from './SKUFormModal';
import { ConfirmationModal } from './ConfirmationModal';
import { SuccessModal } from './SuccessModal';
import { ErrorModal } from './ErrorModal'; // Import ErrorModal
import { supabase, isSupabaseConfigured } from '../../lib/supabase';

export const MasterSKU: React.FC = () => {
  const [skus, setSkus] = useState<SKU[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingSku, setEditingSku] = useState<SKU | undefined>(undefined);

  const [successModal, setSuccessModal] = useState({
    isOpen: false,
    title: '',
    message: ''
  });

  const [errorModal, setErrorModal] = useState({
    isOpen: false,
    title: '',
    message: ''
  });

  const [confirmModal, setConfirmModal] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    confirmLabel?: string;
    isDangerous?: boolean;
    onConfirm: () => void;
  }>({
    isOpen: false,
    title: '',
    message: '',
    confirmLabel: 'Ya, Lanjutkan',
    isDangerous: true,
    onConfirm: () => {}
  });

  // --- SQL FIX CODE ---
  const sqlFixCode = `
CREATE TABLE IF NOT EXISTS public.master_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_sku TEXT NOT NULL UNIQUE,
    nama TEXT NOT NULL,
    deskripsi TEXT,
    kategori TEXT DEFAULT 'Lainnya',
    satuan TEXT DEFAULT 'Pcs',
    min_stock NUMERIC DEFAULT 0,
    hpp NUMERIC DEFAULT 0,
    harga_jual NUMERIC DEFAULT 0,
    hpp_updated_at DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes & Security
CREATE INDEX IF NOT EXISTS idx_master_sku_kode ON public.master_sku(kode_sku);
ALTER TABLE public.master_sku ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access SKU" ON public.master_sku;
CREATE POLICY "Public Access SKU" ON public.master_sku FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.master_sku TO anon, authenticated, service_role;
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlFixCode);
    alert("Kode SQL berhasil disalin! Silakan jalankan di SQL Editor Supabase.");
  };

  // --- FETCH DATA (READ) ---
  const fetchSkus = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    
    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      const { data, error } = await supabase
        .from('master_sku')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        if (error.code === '42P01' || error.message?.includes('does not exist')) {
          setIsTableMissing(true);
          setSkus([]);
        } else {
          throw error;
        }
      } else if (data) {
        const mappedData: SKU[] = data.map((item: any) => {
          let createdDate = '-';
          try {
            if (item.created_at) createdDate = new Date(item.created_at).toLocaleDateString('id-ID');
          } catch (e) {}

          return {
            id: String(item.id),
            code: item.kode_sku || '?',
            name: item.nama || 'Tanpa Nama',
            description: item.deskripsi || '',
            category: item.kategori || 'Lainnya',
            minStock: Number(item.min_stock) || 0,
            unit: item.satuan || 'Pcs',
            hpp: Number(item.hpp) || 0,
            hppUpdatedAt: item.hpp_updated_at || '-', 
            createdAt: createdDate,
            price: Number(item.harga_jual) || 0
          };
        });
        setSkus(mappedData);
      }
    } catch (error: any) {
      console.error('Error fetching SKUs:', error);
      setSkus([]);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchSkus();
  }, []);

  const handleAddClick = () => {
    setEditingSku(undefined);
    setIsModalOpen(true);
  };

  const handleEditClick = (sku: SKU) => {
    setEditingSku(sku);
    setIsModalOpen(true);
  };

  // --- SAVE DATA (CREATE & UPDATE) ---
  const handleSaveSKU = async (formData: Partial<SKU>) => {
    const newCode = formData.code?.trim().toUpperCase();

    if (!newCode) {
      alert("Kode SKU tidak boleh kosong.");
      return;
    }

    try {
      const payload: any = {
        nama: formData.name,
        deskripsi: formData.description,
        kategori: formData.category || 'Lainnya',
        min_stock: formData.minStock || 0,
        satuan: formData.unit || 'Pcs',
        hpp: formData.hpp || 0,
        harga_jual: formData.price || 0,
        updated_at: new Date().toISOString()
      };

      if (editingSku) {
        if (editingSku.hpp !== formData.hpp) {
          payload.hpp_updated_at = new Date().toLocaleDateString('id-ID');
        }

        const { error } = await supabase
          .from('master_sku')
          .update(payload)
          .eq('id', editingSku.id);
        if (error) throw error;
      } else {
        const { data: existing } = await supabase
          .from('master_sku')
          .select('id')
          .eq('kode_sku', newCode)
          .maybeSingle();

        if (existing) {
          alert(`Kode SKU "${newCode}" sudah ada di database.`);
          return;
        }

        payload.kode_sku = newCode;
        payload.created_at = new Date().toISOString();
        payload.hpp_updated_at = new Date().toLocaleDateString('id-ID');

        const { error } = await supabase
          .from('master_sku')
          .insert([payload]);
        if (error) throw error;
      }

      await fetchSkus();
      setIsModalOpen(false);
      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data SKU berhasil disimpan.' });

    } catch (error: any) {
      console.error('Error saving SKU:', error);
      alert(`Gagal menyimpan: ${error.message}`);
    }
  };

  // --- DELETE DATA ---
  const handleDelete = (id: string, name: string) => {
    setConfirmModal({
      isOpen: true,
      title: 'Hapus SKU',
      message: `Apakah Anda yakin ingin menghapus SKU "${name}"?`,
      confirmLabel: 'Ya, Hapus Data',
      isDangerous: true,
      onConfirm: async () => {
        try {
          const { error } = await supabase.from('master_sku').delete().eq('id', id);
          if (error) throw error;
          
          setSkus(prev => prev.filter(s => s.id !== id));
          setSelectedIds(prev => prev.filter(sid => sid !== id));
          setSuccessModal({ isOpen: true, title: 'Terhapus', message: 'Data SKU telah dihapus.' });
        } catch (error: any) {
          alert(`Gagal menghapus: ${error.message}`);
        } finally {
          setConfirmModal(prev => ({ ...prev, isOpen: false }));
        }
      }
    });
  };

  const handleDeleteSelected = () => {
    if (selectedIds.length === 0) return;
    
    setConfirmModal({
      isOpen: true,
      title: 'Hapus Massal SKU',
      message: `Hapus ${selectedIds.length} item terpilih?`,
      confirmLabel: 'Ya, Hapus Semua',
      isDangerous: true,
      onConfirm: async () => {
        try {
          const { error } = await supabase.from('master_sku').delete().in('id', selectedIds);
          if (error) throw error;

          setSkus(prev => prev.filter(s => !selectedIds.includes(s.id)));
          setSelectedIds([]);
          setSuccessModal({ isOpen: true, title: 'Terhapus', message: 'Data SKU terpilih telah dihapus.' });
        } catch (error: any) {
          alert(`Gagal hapus massal: ${error.message}`);
        } finally {
          setConfirmModal(prev => ({ ...prev, isOpen: false }));
        }
      }
    });
  };

  // --- DETEKSI KATEGORI OTOMATIS (HELPER) ---
  const detectCategory = (name: string) => {
    const upperName = name.toUpperCase();
    if (upperName.includes('TAS')) return 'Tas';
    if (upperName.includes('CELANA')) return 'Celana';
    if (upperName.includes('KEMEJA')) return 'Kemeja';
    if (upperName.includes('DOMPET') || upperName.includes('POUCH') || upperName.includes('AKSESORIS')) return 'Aksesoris';
    return 'Lainnya';
  };

  // --- AUTO FIX CATEGORY ---
  const handleAutoCategorize = async () => {
    setConfirmModal({
      isOpen: true,
      title: 'Auto Deteksi Kategori',
      message: 'Sistem akan memindai semua Nama Barang dan memperbarui kategorinya secara otomatis (Tas/Celana/Kemeja). Lanjutkan?',
      confirmLabel: 'Mulai Scan',
      isDangerous: false,
      onConfirm: async () => {
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
        setIsLoading(true);
        try {
          const { data: allSkus } = await supabase.from('master_sku').select('id, nama, kategori');
          
          if (!allSkus) return;

          let updatedCount = 0;
          const updates = [];

          for (const item of allSkus) {
            const detected = detectCategory(item.nama);
            if (detected !== 'Lainnya' && item.kategori !== detected) {
              updates.push(
                supabase.from('master_sku').update({ kategori: detected }).eq('id', item.id)
              );
              updatedCount++;
            }
          }

          if (updates.length > 0) {
            const BATCH_SIZE = 20;
            for (let i = 0; i < updates.length; i += BATCH_SIZE) {
              await Promise.all(updates.slice(i, i + BATCH_SIZE));
            }
            setSuccessModal({
              isOpen: true,
              title: 'Kategori Diperbarui',
              message: `${updatedCount} SKU berhasil diperbarui kategorinya secara otomatis.`
            });
            fetchSkus();
          } else {
            setSuccessModal({
              isOpen: true,
              title: 'Sudah Sesuai',
              message: 'Semua kategori SKU sudah sesuai. Tidak ada perubahan.'
            });
          }
        } catch (error: any) {
          alert(`Gagal: ${error.message}`);
        } finally {
          setIsLoading(false);
        }
      }
    });
  };

  // --- IMPORT EXCEL (FULL LOGIC) ---
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (e) => {
      const data = e.target?.result;
      setIsLoading(true);
      try {
        const workbook = XLSX.read(data, { type: 'array' });
        const sheetName = workbook.SheetNames[0];
        const ws = workbook.Sheets[sheetName];
        const jsonData = XLSX.utils.sheet_to_json(ws);
        
        if (jsonData.length === 0) {
          throw new Error("File Excel kosong atau format tidak terbaca.");
        }

        const formattedData = jsonData.map((row: any) => {
          // Mapping berbagai kemungkinan nama kolom
          const kode = row['Kode SKU'] || row['Kode'] || row['SKU'];
          const nama = row['Nama'] || row['Nama Barang'];
          const hpp = row['HPP'] || row['Harga Pokok'] || 0;
          const harga = row['Harga Jual'] || row['Harga'] || 0;
          const kategori = row['Kategori'] || detectCategory(nama || '');
          const satuan = row['Satuan'] || row['Unit'] || 'Pcs';
          const minStock = row['Min Stock'] || row['Stok Minimal'] || 0;
          const deskripsi = row['Deskripsi'] || row['Keterangan'] || '';

          if (!kode || !nama) return null; // Skip invalid rows

          return {
            kode_sku: String(kode).trim().toUpperCase(),
            nama: String(nama).trim(),
            kategori: kategori,
            satuan: satuan,
            hpp: Number(hpp),
            harga_jual: Number(harga),
            min_stock: Number(minStock),
            deskripsi: deskripsi,
            hpp_updated_at: new Date().toLocaleDateString('id-ID'),
            updated_at: new Date().toISOString()
          };
        }).filter(item => item !== null);

        if (formattedData.length === 0) {
          throw new Error("Tidak ada data valid yang ditemukan. Pastikan kolom 'Kode SKU' dan 'Nama' terisi.");
        }

        // Gunakan UPSERT agar data existing diupdate, data baru diinsert
        const { error } = await supabase
          .from('master_sku')
          .upsert(formattedData, { onConflict: 'kode_sku' });

        if (error) throw error;

        setSuccessModal({
          isOpen: true,
          title: 'Import Berhasil',
          message: `Berhasil memproses ${formattedData.length} data SKU.`
        });
        fetchSkus();

      } catch (error: any) {
        setErrorModal({
          isOpen: true,
          title: 'Gagal Import',
          message: error.message || 'Terjadi kesalahan saat membaca file.'
        });
      } finally {
        setIsLoading(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  const handleExport = () => {
    const dataToExport = skus.map(sku => ({
      'Kode SKU': sku.code,
      'Nama': sku.name,
      'Kategori': sku.category,
      'Deskripsi': sku.description,
      'HPP': sku.hpp,
      'Harga Jual': sku.price,
      'Satuan': sku.unit,
      'Min Stock': sku.minStock
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(dataToExport);
    XLSX.utils.book_append_sheet(wb, ws, "Data SKU");
    XLSX.writeFile(wb, `Master_SKU_${new Date().toISOString().slice(0,10)}.xlsx`);
  };

  const handleDownloadTemplate = () => {
    const templateData = [{
      'Kode SKU': 'CONTOH-001',
      'Nama': 'Tas Wanita Cantik',
      'Kategori': 'Tas Wanita',
      'Satuan': 'Pcs',
      'HPP': 50000,
      'Harga Jual': 75000,
      'Min Stock': 10,
      'Deskripsi': 'Keterangan Barang'
    }];
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(templateData);
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, "Template_SKU.xlsx");
  };

  // --- UI HELPERS ---
  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      setSelectedIds(filteredSkus.map(sku => sku.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelectOne = (id: string) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(selectedIds.filter(selectedId => selectedId !== id));
    } else {
      setSelectedIds([...selectedIds, id]);
    }
  };

  const filteredSkus = skus.filter(sku => 
    sku.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    sku.code.toLowerCase().includes(searchTerm.toLowerCase())
  );
  
  const isAllSelected = filteredSkus.length > 0 && selectedIds.length === filteredSkus.length;
  const isIndeterminate = selectedIds.length > 0 && selectedIds.length < filteredSkus.length;

  return (
    <div className="space-y-6">
      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
        <div>
          <h2 className="text-xl font-bold text-gray-800 dark:text-white flex items-center gap-2">
            Master Data SKU
          </h2>
          <p className="text-sm text-gray-500">Kelola data barang dan HPP.</p>
        </div>
        
        <div className="flex flex-wrap gap-2">
          <input type="file" ref={fileInputRef} onChange={handleFileChange} className="hidden" accept=".xlsx, .xls" />

          {selectedIds.length > 0 && (
            <button onClick={handleDeleteSelected} className="bg-red-100 text-red-700 px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium">
              <Trash2 size={16} /> Hapus ({selectedIds.length})
            </button>
          )}
          
          <div className="flex rounded-lg shadow-sm">
            <button onClick={handleDownloadTemplate} className="bg-white border border-gray-200 px-3 py-2 rounded-l-lg text-sm hover:bg-gray-50" title="Download Template">
              <FileSpreadsheet size={16} />
            </button>
            <button onClick={() => fileInputRef.current?.click()} className="bg-white border-t border-b border-r border-gray-200 px-3 py-2 rounded-r-lg text-sm flex items-center gap-2 hover:bg-gray-50">
              <Upload size={16} /> Import
            </button>
          </div>

          <button onClick={handleAutoCategorize} className="bg-purple-100 text-purple-700 hover:bg-purple-200 px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium transition-colors" title="Perbaiki Kategori Otomatis">
            <Wand2 size={16} /> Auto Kategori
          </button>

          <button onClick={handleExport} className="bg-green-600 hover:bg-green-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium transition-colors">
            <Download size={16} /> Ekspor
          </button>
          
          <button onClick={handleAddClick} className="bg-erp-blue-600 hover:bg-erp-blue-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium transition-colors">
            <Plus size={16} /> Tambah SKU
          </button>
        </div>
      </div>

      {/* ERROR STATE: TABLE MISSING */}
      {isTableMissing && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-6 flex flex-col items-center text-center animate-fadeIn">
          <div className="bg-red-100 p-3 rounded-full mb-4">
            <AlertCircle size={32} className="text-red-600" />
          </div>
          <h3 className="text-lg font-bold text-red-800 mb-2">Database Belum Siap</h3>
          <p className="text-red-600 mb-6 max-w-md">
            Tabel <code>master_sku</code> tidak ditemukan di database Supabase Anda. 
            Jika Anda sudah menjalankan SQL, silakan klik tombol di bawah ini.
          </p>
          <div className="flex gap-3">
            <button 
              onClick={handleCopySQL} 
              className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 shadow-sm transition-colors"
            >
              <Copy size={16} /> Salin Kode SQL Perbaikan
            </button>
            <button 
              onClick={fetchSkus} 
              className="bg-white border border-red-300 text-red-700 hover:bg-red-50 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
            >
              <RefreshCw size={16} /> Coba Lagi (Refresh)
            </button>
          </div>
        </div>
      )}

      {/* Summary Cards - Total SKU */}
      {!isTableMissing && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white dark:bg-dark-800 p-6 rounded-xl shadow-sm border border-gray-100 dark:border-dark-600">
            <div className="flex justify-between items-start mb-4">
              <h3 className="text-gray-900 dark:text-white font-semibold">Total SKU</h3>
              <Package className="text-gray-400" size={24} />
            </div>
            <div>
              <p className="text-4xl font-bold text-gray-900 dark:text-white">{skus.length}</p>
              <p className="text-sm text-gray-500 mt-2">Master data SKU aktif</p>
            </div>
          </div>
        </div>
      )}

      <div className="bg-white dark:bg-dark-800 rounded-xl shadow-sm border border-gray-100 dark:border-dark-600 overflow-hidden">
        <div className="p-4 border-b border-gray-100 dark:border-dark-600 flex gap-4 items-center justify-between flex-wrap">
          <div className="relative flex-1 min-w-[200px] max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
            <input 
              type="text" 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Cari Kode SKU atau Nama Barang..." 
              className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 dark:border-dark-600 bg-gray-50 dark:bg-dark-700 focus:outline-none focus:ring-2 focus:ring-erp-blue-600 text-gray-900 dark:text-white"
            />
          </div>
          <button onClick={fetchSkus} className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg" title="Refresh Data">
            <RefreshCw size={18} />
          </button>
        </div>

        {/* Scrollable Table Container with Sticky Header */}
        <div className="overflow-auto max-h-[600px]">
          <table className="w-full text-left text-sm relative">
            <thead className="bg-gray-50 dark:bg-dark-700 text-gray-600 dark:text-gray-300 font-medium sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-6 py-3 w-10">
                  <input 
                    type="checkbox" 
                    className="w-4 h-4 rounded"
                    checked={isAllSelected}
                    ref={input => { if (input) input.indeterminate = isIndeterminate; }}
                    onChange={handleSelectAll}
                  />
                </th>
                <th className="px-6 py-3">Kode SKU</th>
                <th className="px-6 py-3">Nama</th>
                <th className="px-6 py-3">Kategori</th>
                <th className="px-6 py-3">HPP</th>
                <th className="px-6 py-3">Update Terakhir</th>
                <th className="px-6 py-3 text-right">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-dark-600">
              {isLoading ? (
                <tr><td colSpan={7} className="px-6 py-12 text-center"><Loader2 className="animate-spin inline mr-2" /> Memuat data dari database...</td></tr>
              ) : filteredSkus.length > 0 ? (
                filteredSkus.map((sku) => (
                  <tr key={sku.id} className="hover:bg-gray-50 dark:hover:bg-dark-700 transition-colors">
                    <td className="px-6 py-3">
                      <input 
                        type="checkbox" 
                        className="w-4 h-4 rounded"
                        checked={selectedIds.includes(sku.id)}
                        onChange={() => handleSelectOne(sku.id)}
                      />
                    </td>
                    <td className="px-6 py-3 font-medium text-gray-900 dark:text-white">{sku.code}</td>
                    <td className="px-6 py-3 text-gray-700 dark:text-gray-300">{sku.name}</td>
                    <td className="px-6 py-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${
                        sku.category === 'Tas' ? 'bg-pink-50 text-pink-700' :
                        sku.category === 'Celana' ? 'bg-blue-50 text-blue-700' :
                        sku.category === 'Kemeja' ? 'bg-purple-50 text-purple-700' :
                        'bg-gray-100 text-gray-700'
                      }`}>
                        {sku.category}
                      </span>
                    </td>
                    <td className="px-6 py-3 font-medium text-gray-600">Rp {sku.hpp.toLocaleString()}</td>
                    <td className="px-6 py-3 text-gray-500 text-xs">{sku.hppUpdatedAt}</td>
                    <td className="px-6 py-3 text-right">
                      <div className="flex justify-end gap-2">
                        <button onClick={() => handleEditClick(sku)} className="p-1.5 text-blue-600 hover:bg-blue-50 rounded transition-colors" title="Edit"><Edit2 size={16} /></button>
                        <button onClick={() => handleDelete(sku.id, sku.name)} className="p-1.5 text-red-600 hover:bg-red-50 rounded transition-colors" title="Hapus"><Trash2 size={16} /></button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr><td colSpan={7} className="px-6 py-12 text-center text-gray-400">
                  {isTableMissing ? 'Tabel database hilang.' : 'Tidak ada data SKU. Silakan tambah atau import.'}
                </td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <SKUFormModal 
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSubmit={handleSaveSKU}
        initialData={editingSku}
      />

      <ConfirmationModal
        isOpen={confirmModal.isOpen}
        onClose={() => setConfirmModal(prev => ({ ...prev, isOpen: false }))}
        onConfirm={confirmModal.onConfirm}
        title={confirmModal.title}
        message={confirmModal.message}
        confirmLabel={confirmModal.confirmLabel}
        isDangerous={confirmModal.isDangerous}
      />

      <SuccessModal
        isOpen={successModal.isOpen}
        onClose={() => setSuccessModal({ ...successModal, isOpen: false })}
        title={successModal.title}
        message={successModal.message}
      />

      <ErrorModal
        isOpen={errorModal.isOpen}
        onClose={() => setErrorModal({ ...errorModal, isOpen: false })}
        title={errorModal.title}
        message={errorModal.message}
      />
    </div>
  );
};
