import React, { useEffect, useState, useRef } from 'react';
import { 
  Search, Download, Upload, Trash2, FileSpreadsheet, 
  RefreshCw, Loader2, AlertCircle, CheckCircle2, Copy,
  Archive
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../lib/supabase';
import * as XLSX from 'xlsx';
import { SuccessModal } from './SuccessModal';
import { ConfirmationModal } from './ConfirmationModal';

export const StockOpname: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'gudang' | 'rak'>('gudang');
  const [items, setItems] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  
  // Filter Mode: 'aktif' (Pending/Proses) atau 'arsip' (Selesai/Diterapkan)
  const [viewMode, setViewMode] = useState<'aktif' | 'arsip'>('aktif');
  
  // Selection State
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [isApplying, setIsApplying] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  
  const [confirmModal, setConfirmModal] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    confirmLabel?: string;
    isDangerous?: boolean;
    onConfirm: () => void;
  }>({ 
    isOpen: false, 
    title: '', 
    message: '', 
    confirmLabel: 'Ya, Lanjutkan',
    isDangerous: false,
    onConfirm: () => {} 
  });

  // Tentukan tabel aktif berdasarkan Tab
  const currentTable = activeTab === 'gudang' ? 'stock_opname_gudang' : 'stock_opname_rak';
  const currentLocation = activeTab === 'gudang' ? 'Gudang Utama' : 'Rak Display';

  // SQL Fix Code
  const sqlFixCode = `
/* MANUAL FIX */
CREATE TABLE IF NOT EXISTS ${currentTable} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_opname_id BIGINT REFERENCES stock_opname(id) ON DELETE CASCADE,
  sku_id BIGINT REFERENCES master_sku(id),
  tanggal DATE,
  lokasi TEXT DEFAULT '${currentLocation}',
  no_karung TEXT DEFAULT '-',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending',
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Security Fix
ALTER TABLE ${currentTable} ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access" ON ${currentTable};
CREATE POLICY "Public Access" ON ${currentTable} FOR ALL USING (true) WITH CHECK (true);
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlFixCode);
    alert("Kode SQL berhasil disalin! Silakan paste di Supabase SQL Editor.");
  };

  // --- FETCH DATA ---
  const fetchData = async () => {
    setIsLoading(true);
    setErrorMsg('');
    setSelectedIds([]); 
    
    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      // 1. Ambil ID Header "Aktif" (Sesi Terbaru)
      const { data: activeHeader } = await supabase
        .from('stock_opname')
        .select('id')
        .eq('lokasi', currentLocation)
        .eq('status', 'Aktif')
        .maybeSingle();

      const activeId = activeHeader?.id;

      // 2. Ambil ID Header "Arsip" (Sesi Lama)
      const { data: archiveHeaders } = await supabase
        .from('stock_opname')
        .select('id')
        .eq('lokasi', currentLocation)
        .in('status', ['Arsip', 'Selesai']);
      
      const archiveIds = archiveHeaders?.map(h => h.id) || [];

      // 3. Query Item berdasarkan View Mode
      let query = supabase
        .from(currentTable)
        .select(`
          *,
          stock_opname (
            id,
            tanggal,
            status,
            nomor_so
          ),
          master_sku (
            kode_sku,
            nama,
            kategori,
            satuan
          )
        `);

      if (viewMode === 'aktif') {
        if (!activeId) {
          setItems([]);
          setIsLoading(false);
          return;
        }
        query = query
          .eq('stock_opname_id', activeId)
          .neq('status', 'Diterapkan'); 
      
      } else {
        const conditions = [];
        conditions.push(`status.eq.Diterapkan`);
        if (archiveIds.length > 0) {
          conditions.push(`stock_opname_id.in.(${archiveIds.join(',')})`);
        }
        query = query.or(conditions.join(','));
      }

      const { data, error } = await query.order('id', { ascending: false });

      if (error) throw error;

      if (data) {
        const formattedData = data.map((item: any) => {
          return {
            id: item.id,
            skuId: item.sku_id,
            soId: item.stock_opname?.id,
            soNumber: item.stock_opname?.nomor_so || '-',
            uniqueId: `SO-${(item.id || 0).toString().padStart(4, '0')}`,
            date: item.tanggal || item.stock_opname?.tanggal || '-',
            skuCode: item.master_sku?.kode_sku || '?',
            skuName: item.master_sku?.nama || 'Unknown Item',
            category: item.master_sku?.kategori || '-',
            location: item.lokasi || '-',
            karung: item.no_karung || '-',
            qtySystem: Number(item.qty_sistem ?? 0),
            qtyReal: Number(item.qty_fisik ?? 0),
            diff: Number(item.selisih ?? 0),
            status: item.status || 'Pending',
            unit: item.master_sku?.satuan || 'Pcs'
          };
        });
        setItems(formattedData);
      }
    } catch (error: any) {
      console.error('Error fetching data:', error);
      if (error.code === '42P01' || error.message?.includes('does not exist')) {
        setErrorMsg(`Tabel "${currentTable}" belum dibuat di database.`);
      } else {
        setErrorMsg(`Error: ${error.message}`);
      }
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    setViewMode('aktif');
  }, [activeTab]);

  useEffect(() => {
    fetchData();
  }, [activeTab, viewMode]);

  const filteredItems = items.filter(item => {
    const searchLower = searchTerm.toLowerCase();
    return (
      (item.skuName || '').toLowerCase().includes(searchLower) ||
      (item.skuCode || '').toLowerCase().includes(searchLower) ||
      (item.uniqueId || '').toLowerCase().includes(searchLower) ||
      (item.karung || '').toLowerCase().includes(searchLower)
    );
  });

  const selectableItems = filteredItems.filter(item => item.status !== 'Diterapkan' && viewMode === 'aktif');

  const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      setSelectedIds(selectableItems.map(i => i.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelectOne = (id: string) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(prev => prev.filter(item => item !== id));
    } else {
      setSelectedIds(prev => [...prev, id]);
    }
  };

  const isAllSelected = selectableItems.length > 0 && selectableItems.every(item => selectedIds.includes(item.id));
  const isIndeterminate = selectedIds.length > 0 && selectedIds.length < selectableItems.length;

  // --- APPLY STOCK LOGIC ---
  const handleApplyStock = () => {
    if (selectedIds.length === 0) return;

    setConfirmModal({
      isOpen: true,
      title: `Terapkan Hasil SO ${activeTab === 'gudang' ? 'Gudang' : 'Rak'}?`,
      message: `Anda akan menerapkan ${selectedIds.length} item hasil Stock Opname.\n\n⚠️ PERHATIAN:\n1. Stok di menu '${activeTab === 'gudang' ? 'Stok Gudang' : 'Stok Rak'}' akan DITIMPA dengan angka Qty Real.\n2. Riwayat Mutasi akan dicatat sebagai 'Stock Opname'.\n3. Data ini akan dipindahkan ke Arsip.\n\nLanjutkan?`,
      confirmLabel: 'Ya, Update Stok Sekarang',
      isDangerous: false,
      onConfirm: executeApplyStock
    });
  };

  const executeApplyStock = async () => {
    setIsApplying(true);
    try {
      const itemsToApply = items.filter(i => selectedIds.includes(i.id));
      
      let successCount = 0;
      let deletedCount = 0;

      for (const item of itemsToApply) {
        
        // --- LOGIKA KHUSUS RAK ---
        if (activeTab === 'rak') {
            const { data: existingRak } = await supabase
                .from('stok_rak')
                .select('id')
                .match({ sku_id: item.skuId, kode_rak: item.location })
                .maybeSingle();

            if (item.qtyReal > 0) {
                if (existingRak) {
                    await supabase.from('stok_rak').update({
                        quantity: item.qtyReal,
                        updated_at: new Date().toISOString()
                    }).eq('id', existingRak.id);
                } else {
                    await supabase.from('stok_rak').insert({
                        sku_id: item.skuId,
                        kode_rak: item.location,
                        quantity: item.qtyReal,
                        updated_at: new Date().toISOString()
                    });
                }
                successCount++;
            } else {
                if (existingRak) {
                    await supabase.from('stok_rak').delete().eq('id', existingRak.id);
                    deletedCount++;
                }
            }
        } 
        // --- LOGIKA GUDANG ---
        else {
            const payload: any = {
                sku_id: item.skuId,
                lokasi_gudang: item.location,
                quantity: item.qtyReal,
                updated_at: new Date().toISOString(),
                no_karung: item.karung
            };

            if (item.qtyReal > 0) {
                const { error } = await supabase
                    .from('stok_gudang')
                    .upsert(payload, { onConflict: 'sku_id, lokasi_gudang, no_karung' });
                if (error) throw error;
                successCount++;
            } else {
                const { error } = await supabase
                    .from('stok_gudang')
                    .delete()
                    .match({ 
                        sku_id: item.skuId, 
                        lokasi_gudang: item.location,
                        no_karung: item.karung 
                    });
                if (error) throw error;
                deletedCount++;
            }
        }

        // --- CATAT RIWAYAT MUTASI (LENGKAP DENGAN QTY SISTEM & SELISIH) ---
        await supabase.from('riwayat_mutasi').insert({
          sku_id: item.skuId,
          jenis_mutasi: 'Stock Opname',
          lokasi_asal: 'Sistem',
          lokasi_tujuan: item.location,
          jumlah: item.qtyReal, // Stok Akhir
          qty_sistem: item.qtySystem, // Stok Awal (Sistem)
          qty_real: item.qtyReal,     // Stok Fisik
          selisih: item.diff,         // Selisih
          keterangan: `Hasil Stock Opname (Tgl: ${item.date})`
        });

        // --- UPDATE STATUS SO ---
        await supabase
          .from(currentTable)
          .update({ status: 'Diterapkan' })
          .eq('id', item.id);
      }

      setConfirmModal(prev => ({ ...prev, isOpen: false }));

      setSuccessModal({
        isOpen: true,
        title: 'Stok Berhasil Diperbarui',
        message: `${successCount} SKU stoknya telah diupdate sesuai fisik.\n${deletedCount} SKU dihapus (karena fisik 0).\n\nSilakan cek menu Stok Rak/Gudang untuk melihat hasil.`
      });

      fetchData();

    } catch (error: any) {
      alert(`Gagal menerapkan stok: ${error.message}`);
      setConfirmModal(prev => ({ ...prev, isOpen: false }));
    } finally {
      setIsApplying(false);
    }
  };

  // --- IMPORT EXCEL ---
  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (evt) => {
      const bstr = evt.target?.result;
      const wb = XLSX.read(bstr, { type: 'array' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const jsonData = XLSX.utils.sheet_to_json(ws);

      if (jsonData.length === 0) {
        alert("File Excel kosong!");
        return;
      }

      setIsLoading(true);
      try {
        await supabase
          .from('stock_opname')
          .update({ status: 'Arsip' })
          .eq('lokasi', currentLocation)
          .eq('status', 'Aktif');

        const { data: header, error: headErr } = await supabase
            .from('stock_opname')
            .insert({
                nomor_so: `SO-${activeTab.toUpperCase()}-${Date.now()}`,
                tanggal: new Date().toISOString().split('T')[0],
                status: 'Aktif',
                lokasi: currentLocation
            })
            .select()
            .single();

        if (headErr) throw headErr;

        const itemsToInsert = [];
        const { data: skus } = await supabase.from('master_sku').select('id, kode_sku');
        const skuMap = new Map(skus?.map((s: any) => [s.kode_sku.trim().toUpperCase(), s.id]));

        for (const row: any of jsonData) {
            const skuCodeRaw = row['SKU'] || row['Kode SKU'];
            if (!skuCodeRaw) continue;

            const skuCode = skuCodeRaw.toString().trim().toUpperCase();
            const skuId = skuMap.get(skuCode);
            
            // --- IMPROVED DATE PARSING ---
            let dateStr = new Date().toISOString().split('T')[0];
            const rawDate = row['Tanggal'] || row['Date'];
            
            if (typeof rawDate === 'number') {
               // Excel Serial
               dateStr = new Date(Math.round((rawDate - 25569) * 86400 * 1000)).toISOString().split('T')[0];
            } else if (typeof rawDate === 'string') {
               const cleanDate = rawDate.trim();
               const parts = cleanDate.split(/[\/\-]/);
               
               if (parts.length === 3) {
                   if (parts[0].length === 4) {
                       // YYYY-MM-DD
                       dateStr = `${parts[0]}-${parts[1].padStart(2,'0')}-${parts[2].padStart(2,'0')}`;
                   } else {
                       // DD-MM-YYYY
                       const d = parts[0].padStart(2, '0');
                       const m = parts[1].padStart(2, '0');
                       let y = parts[2];
                       if (y.length === 2) y = '20' + y;
                       dateStr = `${y}-${m}-${d}`;
                   }
               }
            }

            const qtySistem = Number(row['Qty Sistem'] ?? row['Stok Sistem'] ?? 0);
            const qtyReal = Number(row['Qty Real'] ?? row['Stok Fisik'] ?? 0);
            const selisih = qtyReal - qtySistem;
            
            let statusItem = 'Sesuai';
            if (selisih !== 0) statusItem = 'Selisih';

            if (skuId) {
                itemsToInsert.push({
                    stock_opname_id: header.id,
                    sku_id: skuId,
                    tanggal: dateStr,
                    lokasi: row['Lokasi'] || currentLocation,
                    no_karung: row['No. Karung'] || row['Karung'] || '-',
                    qty_sistem: qtySistem,
                    qty_fisik: qtyReal,
                    selisih: selisih,
                    status: statusItem
                });
            }
        }

        if (itemsToInsert.length > 0) {
            const { error: insertError } = await supabase
              .from(currentTable)
              .insert(itemsToInsert);
            
            if (insertError) {
                await supabase.from('stock_opname').delete().eq('id', header.id);
                throw insertError;
            }
            
            setViewMode('aktif');
            
            setSuccessModal({
                isOpen: true,
                title: 'Import Berhasil & Arsip Otomatis',
                message: `Data SO sebelumnya telah diarsipkan.\n\nBerhasil mengimport ${itemsToInsert.length} data baru ke Sesi Aktif.`
            });
        } else {
            await supabase.from('stock_opname').delete().eq('id', header.id);
            alert("Tidak ada data valid atau SKU tidak ditemukan.");
        }
        
        fetchData();
      } catch (error: any) {
        alert(`Gagal Import: ${error.message}`);
      } finally {
        setIsLoading(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsArrayBuffer(file);
  };

  const handleExportCSV = async () => {
    setIsLoading(true);
    try {
        let dataToExport = [];
        const today = new Date().toLocaleDateString('id-ID');
        const tableName = activeTab === 'gudang' ? 'stok_gudang' : 'stok_rak';
        const locCol = activeTab === 'gudang' ? 'lokasi_gudang' : 'kode_rak';

        let selectQuery = `quantity, ${locCol}, master_sku (kode_sku, nama)`;
        if (activeTab === 'gudang') {
            selectQuery += `, no_karung`;
        }

        const { data } = await supabase.from(tableName).select(selectQuery);
        
        if (data) {
            dataToExport = data.map((item: any) => ({
                'Tanggal': today,
                'SKU': item.master_sku?.kode_sku,
                'Nama Barang': item.master_sku?.nama,
                'Lokasi': item[locCol],
                'No. Karung': item.no_karung || '-',
                'Qty Sistem': item.quantity,
                'Qty Real': 0
            }));
        }

        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.json_to_sheet(dataToExport);
        XLSX.utils.book_append_sheet(wb, ws, "Worksheet");
        XLSX.writeFile(wb, `Worksheet_SO_${activeTab}.xlsx`);

    } catch (error: any) {
        alert(`Gagal Export: ${error.message}`);
    } finally {
        setIsLoading(false);
    }
  };

  const handleExportData = () => {
    if (items.length === 0) {
      alert("Tidak ada data untuk diexport.");
      return;
    }

    const dataToExport = items.map(item => ({
      'Tanggal': item.date,
      'SKU': item.skuCode,
      'Nama Barang': item.skuName,
      'Lokasi': item.location,
      'No. Karung': item.karung,
      'Qty Sistem': item.qtySystem,
      'Qty Real': item.qtyReal,
      'Selisih': item.diff,
      'Status': item.status
    }));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(dataToExport);
    const wscols = [{ wch: 12 }, { wch: 15 }, { wch: 30 }, { wch: 15 }, { wch: 10 }, { wch: 10 }, { wch: 10 }, { wch: 10 }, { wch: 10 }];
    ws['!cols'] = wscols;
    XLSX.utils.book_append_sheet(wb, ws, "Data SO");
    XLSX.writeFile(wb, `Data_SO_${activeTab}_${viewMode}_${new Date().toISOString().slice(0,10)}.xlsx`);
  };

  const handleDownloadTemplate = () => {
    const templateData = [{
      'Tanggal': '11/06/2025',
      'SKU': 'CONTOH-01',
      'Nama Barang': 'Contoh Barang',
      'Lokasi': activeTab === 'gudang' ? 'Gudang A' : 'Rak Display',
      'No. Karung': 'K1',
      'Qty Sistem': 100,
      'Qty Real': 98
    }];
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(templateData);
    XLSX.utils.book_append_sheet(wb, ws, "Template");
    XLSX.writeFile(wb, `Template_SO_${activeTab}.xlsx`);
  };

  const handleDeleteAll = () => {
    const label = activeTab === 'gudang' ? 'SO Gudang' : 'SO Rak';
    setConfirmModal({
      isOpen: true,
      title: `Hapus Sesi Aktif ${label}?`,
      message: `Apakah Anda yakin ingin menghapus data Sesi Aktif ini?\n\nData arsip tidak akan terhapus.`,
      confirmLabel: 'Ya, Hapus Sesi Ini',
      isDangerous: true, 
      onConfirm: async () => {
        setConfirmModal(prev => ({ ...prev, isOpen: false }));
        setIsLoading(true);
        try {
          const { error } = await supabase
            .from('stock_opname')
            .delete()
            .eq('lokasi', currentLocation)
            .eq('status', 'Aktif');

          if (error) throw error;

          setSuccessModal({ isOpen: true, title: 'Pembersihan Berhasil', message: `Data sesi aktif ${label} telah dihapus.` });
          fetchData();
        } catch (error: any) { 
          console.error(error); 
          alert(`Gagal menghapus: ${error.message}`);
        } finally { 
          setIsLoading(false); 
        }
      }
    });
  };

  return (
    <div className="p-6 space-y-6 bg-gray-50 dark:bg-dark-900 min-h-screen">
      <input type="file" ref={fileInputRef} onChange={handleImport} className="hidden" accept=".xlsx, .xls, .csv" />

      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Stock Opname</h1>
        <p className="text-gray-500 text-sm mt-1">Import data SO sesuai format Excel Gudang</p>
      </div>

      {errorMsg && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-4 rounded-lg flex flex-col sm:flex-row items-start sm:items-center gap-3 animate-fadeIn shadow-sm">
          <AlertCircle size={24} className="shrink-0 mt-1 sm:mt-0" />
          <div className="flex-1">
            <h3 className="font-bold text-red-800 mb-1">Terjadi Kesalahan Database</h3>
            <p className="text-sm">{errorMsg}</p>
            {errorMsg.includes('belum dibuat') && (
              <p className="text-xs mt-1 text-red-600">Silakan jalankan kode SQL perbaikan di Supabase.</p>
            )}
          </div>
          <div className="flex gap-2 mt-2 sm:mt-0">
            {errorMsg.includes('belum dibuat') && (
              <button onClick={handleCopySQL} className="text-sm bg-red-600 text-white hover:bg-red-700 px-3 py-1.5 rounded-lg font-medium transition-colors flex items-center gap-1 shadow-sm">
                <Copy size={14} /> Copy SQL Fix
              </button>
            )}
            <button onClick={fetchData} className="text-sm bg-white border border-red-200 hover:bg-red-50 px-3 py-1.5 rounded-lg font-medium transition-colors flex items-center gap-1">
              <RefreshCw size={14} /> Coba Lagi
            </button>
          </div>
        </div>
      )}

      <div className="bg-white dark:bg-dark-800 rounded-xl shadow-sm border border-gray-200 dark:border-dark-600 overflow-hidden">
        <div className="flex border-b border-gray-200 dark:border-dark-600 bg-gray-50 dark:bg-dark-700/50">
          <button onClick={() => setActiveTab('gudang')} className={`flex-1 py-3 text-sm font-medium border-b-2 transition-colors ${activeTab === 'gudang' ? 'border-erp-blue-600 text-erp-blue-600 bg-white' : 'border-transparent text-gray-500 hover:bg-gray-100'}`}>SO Gudang</button>
          <button onClick={() => setActiveTab('rak')} className={`flex-1 py-3 text-sm font-medium border-b-2 transition-colors ${activeTab === 'rak' ? 'border-erp-blue-600 text-erp-blue-600 bg-white' : 'border-transparent text-gray-500 hover:bg-gray-100'}`}>SO Rak</button>
        </div>

        <div className="p-4 flex flex-col lg:flex-row justify-between items-center gap-4 bg-white dark:bg-dark-800">
          <div className="flex items-center gap-3 w-full lg:w-auto">
             <div className="relative">
                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <input type="text" placeholder="Cari SKU..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="pl-9 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-erp-blue-500 bg-gray-50" />
             </div>
             
             <div className="flex bg-gray-100 p-1 rounded-lg">
                <button onClick={() => setViewMode('aktif')} className={`px-3 py-1 text-xs font-medium rounded-md transition-all flex items-center gap-1 ${viewMode === 'aktif' ? 'bg-white text-erp-blue-600 shadow-sm' : 'text-gray-500'}`}>
                  <CheckCircle2 size={12} /> Sesi Aktif
                </button>
                <button onClick={() => setViewMode('arsip')} className={`px-3 py-1 text-xs font-medium rounded-md transition-all flex items-center gap-1 ${viewMode === 'arsip' ? 'bg-white text-gray-600 shadow-sm' : 'text-gray-500'}`}>
                  <Archive size={12} /> Arsip
                </button>
             </div>

             {selectedIds.length > 0 && viewMode === 'aktif' && (
               <button onClick={handleApplyStock} className="bg-green-600 hover:bg-green-700 text-white px-4 py-1.5 rounded-lg text-sm font-medium flex items-center gap-2 shadow-sm transition-all animate-fadeIn">
                 {isApplying ? <Loader2 className="animate-spin" size={16}/> : <CheckCircle2 size={16} />}
                 Terapkan ({selectedIds.length})
               </button>
             )}
          </div>

          <div className="flex flex-wrap gap-2 w-full lg:w-auto justify-end">
            {viewMode === 'arsip' && (
              <button onClick={handleExportData} className="px-3 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg text-xs font-medium flex items-center gap-2 shadow-sm">
                <Download size={14} /> Export Data
              </button>
            )}
            {viewMode === 'aktif' && (
              <>
                <button onClick={handleExportCSV} className="px-3 py-2 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 rounded-lg text-xs font-medium flex items-center gap-2 shadow-sm">
                  <FileSpreadsheet size={14} /> Worksheet
                </button>
                <button onClick={handleDownloadTemplate} className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium flex items-center gap-2">
                  <FileSpreadsheet size={14} /> Template
                </button>
                <button onClick={handleDeleteAll} className="px-3 py-2 bg-gray-100 hover:bg-red-50 text-gray-700 hover:text-red-600 rounded-lg text-xs font-medium flex items-center gap-2">
                  <Trash2 size={14} /> Hapus Sesi
                </button>
                <button onClick={() => fileInputRef.current?.click()} className="px-4 py-2 bg-erp-pink hover:bg-pink-600 text-white rounded-lg text-xs font-medium flex items-center gap-2 shadow-sm">
                  <Upload size={14} /> Import Excel
                </button>
              </>
            )}
          </div>
        </div>

        <div className="overflow-auto max-h-[600px] border-t border-gray-200 dark:border-dark-600">
          <table className="w-full text-sm text-left relative border-collapse">
            <thead className="bg-blue-50 dark:bg-dark-700 text-gray-600 dark:text-gray-300 font-medium sticky top-0 z-10 shadow-sm">
              <tr>
                <th className="px-4 py-3 w-10 text-center bg-blue-50 dark:bg-dark-700">
                  <input 
                    type="checkbox" 
                    className={`w-4 h-4 rounded border-gray-300 text-erp-blue-600 focus:ring-erp-blue-500 cursor-pointer ${selectableItems.length === 0 ? 'opacity-50 cursor-not-allowed' : ''}`}
                    checked={isAllSelected}
                    disabled={selectableItems.length === 0}
                    ref={input => { if (input) input.indeterminate = isIndeterminate; }}
                    onChange={handleSelectAll}
                  />
                </th>
                <th className="px-4 py-3 bg-blue-50 dark:bg-dark-700">Tanggal</th>
                <th className="px-4 py-3 bg-blue-50 dark:bg-dark-700">SKU</th>
                <th className="px-4 py-3 bg-blue-50 dark:bg-dark-700">Nama Barang</th>
                <th className="px-4 py-3 bg-blue-50 dark:bg-dark-700">Lokasi</th>
                <th className="px-4 py-3 bg-blue-50 dark:bg-dark-700">No. Karung</th>
                <th className="px-4 py-3 text-center bg-blue-50 dark:bg-dark-700">Qty Sistem</th>
                <th className="px-4 py-3 text-center bg-blue-50 dark:bg-dark-700">Qty Real</th>
                <th className="px-4 py-3 text-center bg-blue-50 dark:bg-dark-700">Selisih</th>
                <th className="px-4 py-3 bg-blue-50 dark:bg-dark-700">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-dark-600 bg-white dark:bg-dark-800">
              {isLoading ? (
                <tr><td colSpan={10} className="p-8 text-center"><Loader2 className="animate-spin inline text-erp-blue-600" /> Memuat data...</td></tr>
              ) : filteredItems.length > 0 ? (
                filteredItems.map((item, idx) => (
                  <tr key={item.id} className={`hover:bg-gray-50 dark:hover:bg-dark-700 transition-colors ${selectedIds.includes(item.id) ? 'bg-blue-50/50' : ''}`}>
                    <td className="px-4 py-3 text-center">
                      {item.status !== 'Diterapkan' && viewMode === 'aktif' ? (
                        <input 
                          type="checkbox" 
                          className="w-4 h-4 rounded border-gray-300 text-erp-blue-600 focus:ring-erp-blue-500 cursor-pointer"
                          checked={selectedIds.includes(item.id)}
                          onChange={() => handleSelectOne(item.id)}
                        />
                      ) : (
                        <div className={`w-4 h-4 rounded border border-gray-200 mx-auto ${item.status === 'Diterapkan' ? 'bg-blue-100' : 'bg-gray-100'}`} />
                      )}
                    </td>
                    <td className="px-4 py-3 text-gray-600">{item.date}</td>
                    <td className="px-4 py-3 font-bold text-gray-800 dark:text-white text-xs">{item.skuCode}</td>
                    <td className="px-4 py-3 text-gray-600 text-xs">{item.skuName}</td>
                    <td className="px-4 py-3 text-gray-700 text-xs">{item.location}</td>
                    <td className="px-4 py-3 text-gray-500 text-xs font-mono">{item.karung}</td>
                    <td className="px-4 py-3 text-center font-medium text-gray-700">{item.qtySystem}</td>
                    <td className="px-4 py-3 text-center font-medium text-blue-700">{item.qtyReal}</td>
                    <td className="px-4 py-3 text-center font-bold">
                      <span className={item.diff === 0 ? 'text-green-600' : 'text-red-600'}>
                        {item.diff > 0 ? '+' : ''}{item.diff}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${
                        item.status === 'Diterapkan' ? 'bg-blue-100 text-blue-600' :
                        item.diff === 0 ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'
                      }`}>
                        {item.status === 'Pending' && item.diff === 0 ? 'Sesuai' : item.status}
                      </span>
                    </td>
                  </tr>
                ))
              ) : (
                <tr><td colSpan={10} className="p-12 text-center text-gray-400 italic">
                  {errorMsg ? 'Tabel belum dibuat atau data kosong.' : viewMode === 'aktif' ? 'Tidak ada sesi aktif. Silakan Import Excel.' : 'Tidak ada data arsip.'}
                </td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ConfirmationModal isOpen={confirmModal.isOpen} onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} onConfirm={confirmModal.onConfirm} title={confirmModal.title} message={confirmModal.message} confirmLabel={confirmModal.confirmLabel || "Ya, Lanjutkan"} isDangerous={confirmModal.isDangerous} isLoading={isApplying} />
    </div>
  );
};
