-- ============================================================================
-- SCRIPT PERBAIKAN TOTAL MODUL PABRIK (ABSENSI & GAJI)
-- Jalankan script ini SEKALI di SQL Editor Supabase untuk memperbaiki semua tabel.
-- ============================================================================

-- 1. TABEL KARYAWAN PABRIK
CREATE TABLE IF NOT EXISTS public.karyawan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT,
    nama TEXT,
    jenis_kelamin TEXT DEFAULT 'L',
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    bulan TEXT,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    kode_karyawan TEXT, -- Legacy support
    jabatan TEXT,       -- Legacy support
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Hapus unique constraint lama jika ada (agar kode sama beda bulan bisa masuk)
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'karyawan_pabrik_kode_karyawan_key') THEN 
        ALTER TABLE public.karyawan_pabrik DROP CONSTRAINT karyawan_pabrik_kode_karyawan_key; 
    END IF; 
END $$;

-- Buat unique index baru (Kode + Bulan harus unik)
CREATE UNIQUE INDEX IF NOT EXISTS idx_karyawan_kode_bulan ON public.karyawan_pabrik(kode, bulan);

-- 2. TABEL PRESENSI HARIAN
CREATE TABLE IF NOT EXISTS public.presensi_harian_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE,
    kode TEXT,
    grade_p1 TEXT,
    grade_p2 TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur TEXT,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL MASTER GAJI
CREATE TABLE IF NOT EXISTS public.master_gaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    grade TEXT,
    gaji_pokok NUMERIC DEFAULT 0,
    gaji_harian NUMERIC DEFAULT 0,
    gaji_setengah_hari NUMERIC DEFAULT 0,
    gaji_per_jam NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_makan_harian NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    uang_kehadiran_harian NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL PENYESUAIAN GAJI
CREATE TABLE IF NOT EXISTS public.penyesuaian_gaji_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    periode TEXT,
    perusahaan TEXT,
    kode TEXT,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL LAPORAN BULANAN
CREATE TABLE IF NOT EXISTS public.laporan_bulanan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    periode TEXT,
    perusahaan TEXT,
    kode TEXT,
    nama TEXT,
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    h NUMERIC DEFAULT 0,
    i_b NUMERIC DEFAULT 0,
    i_tb NUMERIC DEFAULT 0,
    s_b NUMERIC DEFAULT 0,
    s_tb NUMERIC DEFAULT 0,
    t_b NUMERIC DEFAULT 0,
    t_tb NUMERIC DEFAULT 0,
    set_h NUMERIC DEFAULT 0,
    lp NUMERIC DEFAULT 0,
    tm NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    set_h_1_15 NUMERIC DEFAULT 0,
    h_1_31 NUMERIC DEFAULT 0,
    libur_perusahaan NUMERIC DEFAULT 0,
    gapok NUMERIC DEFAULT 0,
    gaji_lembur NUMERIC DEFAULT 0,
    u_k NUMERIC DEFAULT 0,
    u_m NUMERIC DEFAULT 0,
    uang_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    hasil_gaji NUMERIC DEFAULT 0,
    keterangan TEXT,
    keluar_masuk TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PERBAIKAN IZIN AKSES (RLS) - PENTING!
-- Memastikan aplikasi bisa membaca dan menulis data tanpa error "Permission denied"
ALTER TABLE public.karyawan_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_harian_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_gaji ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penyesuaian_gaji_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laporan_bulanan_pabrik ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama agar tidak duplikat
DROP POLICY IF EXISTS "Public Access Karyawan" ON public.karyawan_pabrik;
DROP POLICY IF EXISTS "Public Access Presensi" ON public.presensi_harian_pabrik;
DROP POLICY IF EXISTS "Public Access Gaji" ON public.master_gaji;
DROP POLICY IF EXISTS "Public Access Penyesuaian" ON public.penyesuaian_gaji_pabrik;
DROP POLICY IF EXISTS "Public Access Laporan" ON public.laporan_bulanan_pabrik;

-- Buat policy baru yang terbuka (untuk kemudahan development)
CREATE POLICY "Public Access Karyawan" ON public.karyawan_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Presensi" ON public.presensi_harian_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Gaji" ON public.master_gaji FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Penyesuaian" ON public.penyesuaian_gaji_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Laporan" ON public.laporan_bulanan_pabrik FOR ALL USING (true) WITH CHECK (true);

-- Berikan hak akses ke role anonim dan authenticated
GRANT ALL ON public.karyawan_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.presensi_harian_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.master_gaji TO anon, authenticated, service_role;
GRANT ALL ON public.penyesuaian_gaji_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.laporan_bulanan_pabrik TO anon, authenticated, service_role;
