-- 1. Hapus tabel lama jika ada
DROP TABLE IF EXISTS public.stock_opname_items CASCADE;

-- 2. Buat tabel baru yang sesuai dengan kode frontend
CREATE TABLE IF NOT EXISTS public.stock_opname_gudang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_opname_id BIGINT REFERENCES public.stock_opname(id) ON DELETE CASCADE,
    sku_id BIGINT REFERENCES public.master_sku(id) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    lokasi TEXT DEFAULT 'Gudang Utama',
    no_karung TEXT DEFAULT '-',
    qty_sistem NUMERIC DEFAULT 0,
    qty_fisik NUMERIC DEFAULT 0,
    selisih NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Setup RLS & Policies
ALTER TABLE public.stock_opname_gudang ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access SO Gudang" ON public.stock_opname_gudang;
CREATE POLICY "Public Access SO Gudang" ON public.stock_opname_gudang FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.stock_opname_gudang TO anon, authenticated, service_role;

-- 4. Refresh Cache
NOTIFY pgrst, 'reload config';
