-- 1. Ensure the table exists first (Robust Fix)
CREATE TABLE IF NOT EXISTS public.master_gaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    grade TEXT,
    gaji_pokok NUMERIC DEFAULT 0,
    gaji_harian NUMERIC DEFAULT 0,
    gaji_setengah_hari NUMERIC DEFAULT 0,
    gaji_per_jam NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_makan_harian NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    uang_kehadiran_harian NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure columns exist (Double check for existing tables)
ALTER TABLE public.master_gaji 
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.master_gaji 
ADD COLUMN IF NOT EXISTS bonus NUMERIC DEFAULT 0;

-- 3. Enable RLS and Policies
ALTER TABLE public.master_gaji ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "Public Access Gaji" ON public.master_gaji;
    CREATE POLICY "Public Access Gaji" ON public.master_gaji FOR ALL USING (true) WITH CHECK (true);
END $$;

GRANT ALL ON public.master_gaji TO anon, authenticated, service_role;

-- 4. Refresh the schema cache
NOTIFY pgrst, 'reload config';
