-- Membuat tabel presensi_harian_pabrik
CREATE TABLE IF NOT EXISTS public.presensi_harian_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    grade TEXT,
    bulan TEXT,
    kehadiran TEXT, -- Bisa angka (6) atau status (Hadir), menggunakan TEXT agar fleksibel
    lembur TEXT,    -- Contoh: "0 jam"
    periode TEXT,   -- Contoh: "Periode 1"
    perusahaan TEXT,-- Contoh: "BORONGAN"
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.presensi_harian_pabrik ENABLE ROW LEVEL SECURITY;

-- Membuat Policy agar bisa diakses publik (untuk kemudahan development)
DROP POLICY IF EXISTS "Public Access Presensi Harian" ON public.presensi_harian_pabrik;
CREATE POLICY "Public Access Presensi Harian" ON public.presensi_harian_pabrik FOR ALL USING (true) WITH CHECK (true);

-- Grant permissions
GRANT ALL ON public.presensi_harian_pabrik TO anon;
GRANT ALL ON public.presensi_harian_pabrik TO authenticated;
GRANT ALL ON public.presensi_harian_pabrik TO service_role;
