-- 1. Create the missing table for Admin Daily Attendance
CREATE TABLE IF NOT EXISTS public.presensi_harian_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jabatan TEXT,
    divisi TEXT,
    perusahaan TEXT,
    bulan TEXT,
    kehadiran TEXT,
    jam_lembur NUMERIC DEFAULT 0,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    -- Constraint to prevent duplicate entries for the same person on the same day
    CONSTRAINT unique_presensi_admin_harian UNIQUE (tanggal, kode)
);

-- 2. Enable Row Level Security
ALTER TABLE public.presensi_harian_admin_pabrik ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy to allow access
DROP POLICY IF EXISTS "Public Access Admin Presensi" ON public.presensi_harian_admin_pabrik;
CREATE POLICY "Public Access Admin Presensi" ON public.presensi_harian_admin_pabrik
    FOR ALL USING (true) WITH CHECK (true);

-- 4. Grant permissions
GRANT ALL ON public.presensi_harian_admin_pabrik TO anon, authenticated, service_role;

-- 5. Refresh schema cache
NOTIFY pgrst, 'reload config';
