-- 1. Membuat Tabel Khusus Karyawan Pabrik Garut
CREATE TABLE IF NOT EXISTS public.data_karyawan_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L', -- P/L
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    perusahaan TEXT, -- Kolom Baru
    bagian TEXT,     -- Kolom Baru
    bulan TEXT NOT NULL,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Menambahkan Constraint Unik (Kode + Bulan)
-- Ini mencegah input kode yang sama di bulan yang sama
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_kode_bulan_garut') THEN
        ALTER TABLE public.data_karyawan_pabrik_garut 
        ADD CONSTRAINT unique_kode_bulan_garut UNIQUE (kode, bulan);
    END IF;
END $$;

-- 3. Setup Security (RLS)
ALTER TABLE public.data_karyawan_pabrik_garut ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Garut Employees" ON public.data_karyawan_pabrik_garut;

CREATE POLICY "Public Access Garut Employees" 
ON public.data_karyawan_pabrik_garut 
FOR ALL 
USING (true) 
WITH CHECK (true);

GRANT ALL ON public.data_karyawan_pabrik_garut TO anon, authenticated, service_role;
