-- CREATE TABLE FOR GARUT EMPLOYEES
CREATE TABLE IF NOT EXISTS public.data_karyawan_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L',
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    bagian TEXT,
    perusahaan TEXT,
    bulan TEXT,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_karyawan_garut_kode_bulan UNIQUE (kode, bulan)
);

-- RLS & Security
ALTER TABLE public.data_karyawan_pabrik_garut ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Garut Data" ON public.data_karyawan_pabrik_garut;
CREATE POLICY "Public Access Garut Data" ON public.data_karyawan_pabrik_garut FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.data_karyawan_pabrik_garut TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
