-- 1. Membuat Tabel Master Gaji
CREATE TABLE IF NOT EXISTS master_gaji (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bulan TEXT NOT NULL,
  grade TEXT NOT NULL,
  gaji_pokok NUMERIC DEFAULT 0,
  gaji_harian NUMERIC DEFAULT 0,
  gaji_setengah_hari NUMERIC DEFAULT 0,
  gaji_per_jam NUMERIC DEFAULT 0,
  lembur NUMERIC DEFAULT 0,
  uang_makan NUMERIC DEFAULT 0,
  uang_kehadiran NUMERIC DEFAULT 0,
  bonus NUMERIC DEFAULT 0,
  uang_makan_harian NUMERIC DEFAULT 0,
  uang_kehadiran_harian NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Mengaktifkan Fitur Keamanan
ALTER TABLE master_gaji ENABLE ROW LEVEL SECURITY;

-- 3. Memberikan Izin Akses (Agar aplikasi bisa baca/tulis)
DROP POLICY IF EXISTS "Public Access" ON master_gaji;
CREATE POLICY "Public Access" ON master_gaji 
FOR ALL USING (true) 
WITH CHECK (true);
