-- ==========================================
-- 1. MASTER GAJI ADMIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.master_gaji_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    grade TEXT, -- Jabatan/Posisi
    gaji_pokok NUMERIC DEFAULT 0,
    tunjangan_jabatan NUMERIC DEFAULT 0,
    tunjangan_transport NUMERIC DEFAULT 0,
    tunjangan_makan NUMERIC DEFAULT 0,
    lembur_per_jam NUMERIC DEFAULT 0,
    bonus_target NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.master_gaji_admin ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Master Admin" ON public.master_gaji_admin FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.master_gaji_admin TO anon, authenticated, service_role;

-- ==========================================
-- 2. DATA KARYAWAN ADMIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.data_karyawan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L',
    jabatan TEXT, -- Grade
    divisi TEXT,
    perusahaan TEXT,
    bulan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_kode_bulan_admin UNIQUE (kode, bulan)
);

ALTER TABLE public.data_karyawan_admin_pabrik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Data Admin" ON public.data_karyawan_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.data_karyawan_admin_pabrik TO anon, authenticated, service_role;

-- ==========================================
-- 3. PRESENSI HARIAN ADMIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.presensi_harian_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    jabatan TEXT,
    divisi TEXT,
    bulan TEXT,
    perusahaan TEXT,
    kehadiran TEXT, -- H, I, S, A
    jam_lembur NUMERIC DEFAULT 0,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_presensi_admin_harian UNIQUE (tanggal, kode)
);

ALTER TABLE public.presensi_harian_admin_pabrik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Presensi Admin" ON public.presensi_harian_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.presensi_harian_admin_pabrik TO anon, authenticated, service_role;

-- Trigger Auto-Sync Presensi Admin
CREATE OR REPLACE FUNCTION autofill_admin_to_presensi()
RETURNS TRIGGER AS $$
DECLARE
    v_nama TEXT;
    v_jabatan TEXT;
    v_divisi TEXT;
BEGIN
    SELECT nama, jabatan, divisi INTO v_nama, v_jabatan, v_divisi
    FROM data_karyawan_admin_pabrik
    WHERE kode = NEW.kode AND bulan = NEW.bulan
    LIMIT 1;
    
    IF FOUND THEN
        NEW.nama := v_nama;
        NEW.jabatan := v_jabatan;
        NEW.divisi := v_divisi;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_autofill_admin_presensi ON public.presensi_harian_admin_pabrik;
CREATE TRIGGER trg_autofill_admin_presensi
BEFORE INSERT OR UPDATE ON public.presensi_harian_admin_pabrik
FOR EACH ROW EXECUTE FUNCTION autofill_admin_to_presensi();

-- ==========================================
-- 4. LAPORAN BULANAN ADMIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.laporan_bulanan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    perusahaan TEXT,
    kode TEXT,
    nama TEXT,
    jabatan TEXT,
    divisi TEXT,
    
    -- Statistik Kehadiran
    h INT DEFAULT 0,
    s INT DEFAULT 0,
    i INT DEFAULT 0,
    a INT DEFAULT 0,
    total_lembur NUMERIC DEFAULT 0,
    
    -- Komponen Gaji
    gaji_pokok NUMERIC DEFAULT 0,
    tunjangan_jabatan NUMERIC DEFAULT 0,
    tunjangan_transport NUMERIC DEFAULT 0,
    tunjangan_makan NUMERIC DEFAULT 0,
    uang_lembur NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    potongan NUMERIC DEFAULT 0,
    total_gaji NUMERIC DEFAULT 0,
    
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_laporan_admin_bulan_kode UNIQUE (bulan, kode)
);

ALTER TABLE public.laporan_bulanan_admin_pabrik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Laporan Admin" ON public.laporan_bulanan_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.laporan_bulanan_admin_pabrik TO anon, authenticated, service_role;

-- Function Hitung Gaji Admin
CREATE OR REPLACE FUNCTION calculate_admin_monthly_report(p_bulan TEXT)
RETURNS text AS $$
DECLARE
    emp RECORD;
    master RECORD;
    presensi RECORD;
    
    v_h INT; v_s INT; v_i INT; v_a INT;
    v_lembur NUMERIC;
    
    v_gapok NUMERIC; v_t_jab NUMERIC; v_t_trans NUMERIC; v_t_makan NUMERIC;
    v_u_lembur NUMERIC; v_bonus NUMERIC; v_potongan NUMERIC; v_total NUMERIC;
BEGIN
    -- Loop setiap karyawan di bulan tersebut
    FOR emp IN SELECT * FROM data_karyawan_admin_pabrik WHERE bulan = p_bulan LOOP
        
        -- 1. Hitung Kehadiran
        v_h := 0; v_s := 0; v_i := 0; v_a := 0; v_lembur := 0;
        
        FOR presensi IN SELECT kehadiran, jam_lembur FROM presensi_harian_admin_pabrik WHERE kode = emp.kode AND bulan = p_bulan LOOP
            IF presensi.kehadiran IN ('H', '1', 'Hadir') THEN v_h := v_h + 1;
            ELSIF presensi.kehadiran IN ('S', 'Sakit') THEN v_s := v_s + 1;
            ELSIF presensi.kehadiran IN ('I', 'Izin') THEN v_i := v_i + 1;
            ELSIF presensi.kehadiran IN ('A', 'Alpha') THEN v_a := v_a + 1;
            END IF;
            
            v_lembur := v_lembur + COALESCE(presensi.jam_lembur, 0);
        END LOOP;

        -- 2. Ambil Master Gaji
        SELECT * INTO master FROM master_gaji_admin WHERE grade = emp.jabatan AND bulan = p_bulan LIMIT 1;
        
        -- Default 0 jika master tidak ada
        v_gapok := COALESCE(master.gaji_pokok, 0);
        v_t_jab := COALESCE(master.tunjangan_jabatan, 0);
        v_t_trans := COALESCE(master.tunjangan_transport, 0);
        v_t_makan := COALESCE(master.tunjangan_makan, 0);
        v_u_lembur := v_lembur * COALESCE(master.lembur_per_jam, 0);
        v_bonus := COALESCE(master.bonus_target, 0);
        
        -- Potongan Alpha (Contoh: Potong Transport & Makan Harian jika Alpha/Izin)
        -- Asumsi Tunjangan Transport & Makan adalah bulanan (26 hari), jadi dipotong proporsional
        -- v_potongan := (v_a + v_i) * ((v_t_trans + v_t_makan) / 26);
        v_potongan := 0; -- Simplifikasi dulu

        v_total := v_gapok + v_t_jab + v_t_trans + v_t_makan + v_u_lembur + v_bonus - v_potongan;

        -- 3. Insert/Update Laporan
        INSERT INTO public.laporan_bulanan_admin_pabrik (
            bulan, perusahaan, kode, nama, jabatan, divisi,
            h, s, i, a, total_lembur,
            gaji_pokok, tunjangan_jabatan, tunjangan_transport, tunjangan_makan, uang_lembur, bonus, potongan, total_gaji,
            updated_at
        ) VALUES (
            p_bulan, emp.perusahaan, emp.kode, emp.nama, emp.jabatan, emp.divisi,
            v_h, v_s, v_i, v_a, v_lembur,
            v_gapok, v_t_jab, v_t_trans, v_t_makan, v_u_lembur, v_bonus, v_potongan, v_total,
            NOW()
        )
        ON CONFLICT (bulan, kode) DO UPDATE SET
            h = EXCLUDED.h, s = EXCLUDED.s, i = EXCLUDED.i, a = EXCLUDED.a, total_lembur = EXCLUDED.total_lembur,
            gaji_pokok = EXCLUDED.gaji_pokok, tunjangan_jabatan = EXCLUDED.tunjangan_jabatan,
            tunjangan_transport = EXCLUDED.tunjangan_transport, tunjangan_makan = EXCLUDED.tunjangan_makan,
            uang_lembur = EXCLUDED.uang_lembur, bonus = EXCLUDED.bonus, potongan = EXCLUDED.potongan, total_gaji = EXCLUDED.total_gaji,
            updated_at = NOW();
            
    END LOOP;
    
    RETURN 'Perhitungan Selesai';
END;
$$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload config';
