-- Membuat tabel Penyesuaian Gaji Pabrik
CREATE TABLE IF NOT EXISTS public.penyesuaian_gaji_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    periode TEXT NOT NULL, -- 'Periode 1' atau 'Periode 2'
    perusahaan TEXT NOT NULL, -- 'CV ADNAN' atau 'CV HANAN'
    kode TEXT NOT NULL,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.penyesuaian_gaji_pabrik ENABLE ROW LEVEL SECURITY;

-- Membuat Policy agar tabel bisa diakses (Public Access untuk kemudahan)
DROP POLICY IF EXISTS "Public Access Penyesuaian Gaji" ON public.penyesuaian_gaji_pabrik;

CREATE POLICY "Public Access Penyesuaian Gaji" ON public.penyesuaian_gaji_pabrik
    FOR ALL 
    USING (true) 
    WITH CHECK (true);

-- Memberikan hak akses ke role anon dan authenticated (jika diperlukan)
GRANT ALL ON public.penyesuaian_gaji_pabrik TO anon;
GRANT ALL ON public.penyesuaian_gaji_pabrik TO authenticated;
GRANT ALL ON public.penyesuaian_gaji_pabrik TO service_role;
