-- 1. Pastikan tabel stock_opname_gudang ada
CREATE TABLE IF NOT EXISTS public.stock_opname_gudang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_opname_id BIGINT REFERENCES public.stock_opname(id) ON DELETE CASCADE,
    sku_id BIGINT REFERENCES public.master_sku(id),
    tanggal DATE,
    lokasi TEXT DEFAULT 'Gudang Utama',
    no_karung TEXT DEFAULT '-',
    qty_sistem NUMERIC DEFAULT 0,
    qty_fisik NUMERIC DEFAULT 0,
    selisih NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tambahkan kolom lokasi di tabel header stock_opname (jika belum ada)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='stock_opname' AND column_name='lokasi') THEN
        ALTER TABLE public.stock_opname ADD COLUMN lokasi TEXT DEFAULT 'Gudang Utama';
    END IF;
END $$;

-- 3. Update RLS & Permissions
ALTER TABLE public.stock_opname_gudang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access SO Gudang" ON public.stock_opname_gudang;
CREATE POLICY "Public Access SO Gudang" ON public.stock_opname_gudang FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.stock_opname_gudang TO anon, authenticated, service_role;

-- 4. Hapus tabel lama (opsional, pastikan data sudah aman jika ada)
-- DROP TABLE IF EXISTS public.stock_opname_items;

NOTIFY pgrst, 'reload config';
