-- 1. Buat Tabel stock_opname_rak
CREATE TABLE IF NOT EXISTS public.stock_opname_rak (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_opname_id BIGINT REFERENCES public.stock_opname(id) ON DELETE CASCADE,
    sku_id BIGINT REFERENCES public.master_sku(id) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    lokasi TEXT DEFAULT 'Rak Display',
    no_karung TEXT DEFAULT '-',
    qty_sistem NUMERIC DEFAULT 0,
    qty_fisik NUMERIC DEFAULT 0,
    selisih NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Setup RLS & Policies
ALTER TABLE public.stock_opname_rak ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access SO Rak" ON public.stock_opname_rak;
CREATE POLICY "Public Access SO Rak" ON public.stock_opname_rak FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.stock_opname_rak TO anon, authenticated, service_role;

-- 3. Refresh Cache
NOTIFY pgrst, 'reload config';
