-- SCRIPT PERBAIKAN TOTAL DATABASE PABRIK
-- Jalankan script ini SEKALI untuk memperbaiki semua tabel Gaji & Absensi

-- 1. TABEL MASTER GAJI
CREATE TABLE IF NOT EXISTS public.master_gaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    grade TEXT,
    gaji_pokok NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    gaji_harian NUMERIC DEFAULT 0,
    gaji_setengah_hari NUMERIC DEFAULT 0,
    gaji_per_jam NUMERIC DEFAULT 0,
    uang_makan_harian NUMERIC DEFAULT 0,
    uang_kehadiran_harian NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL PENYESUAIAN GAJI
CREATE TABLE IF NOT EXISTS public.penyesuaian_gaji_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    periode TEXT,
    perusahaan TEXT,
    kode TEXT,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL KARYAWAN PABRIK (Update Kolom)
CREATE TABLE IF NOT EXISTS public.karyawan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT,
    nama TEXT,
    jenis_kelamin TEXT DEFAULT 'L',
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    bulan TEXT,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    kode_karyawan TEXT, -- Legacy support
    jabatan TEXT, -- Legacy support
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Pastikan kolom grade ada jika tabel sudah dibuat sebelumnya
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='grade_p1') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN grade_p1 TEXT;
        ALTER TABLE public.karyawan_pabrik ADD COLUMN grade_p2 TEXT;
    END IF;
END $$;

-- Hapus constraint unik lama jika ada (agar bisa input kode sama beda bulan)
ALTER TABLE public.karyawan_pabrik DROP CONSTRAINT IF EXISTS karyawan_pabrik_kode_karyawan_key;
ALTER TABLE public.karyawan_pabrik DROP CONSTRAINT IF EXISTS karyawan_pabrik_kode_key;

-- 4. TABEL PRESENSI HARIAN (Update Kolom)
CREATE TABLE IF NOT EXISTS public.presensi_harian_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE,
    kode TEXT,
    grade_p1 TEXT,
    grade_p2 TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur TEXT,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='presensi_harian_pabrik' AND column_name='grade_p1') THEN
        ALTER TABLE public.presensi_harian_pabrik ADD COLUMN grade_p1 TEXT;
        ALTER TABLE public.presensi_harian_pabrik ADD COLUMN grade_p2 TEXT;
    END IF;
END $$;

-- 5. TABEL LAPORAN BULANAN
CREATE TABLE IF NOT EXISTS public.laporan_bulanan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    periode TEXT,
    perusahaan TEXT,
    kode TEXT,
    nama TEXT,
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    h NUMERIC DEFAULT 0,
    i_b NUMERIC DEFAULT 0,
    i_tb NUMERIC DEFAULT 0,
    s_b NUMERIC DEFAULT 0,
    s_tb NUMERIC DEFAULT 0,
    t_b NUMERIC DEFAULT 0,
    t_tb NUMERIC DEFAULT 0,
    set_h NUMERIC DEFAULT 0,
    lp NUMERIC DEFAULT 0,
    tm NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    set_h_1_15 NUMERIC DEFAULT 0,
    h_1_31 NUMERIC DEFAULT 0,
    libur_perusahaan NUMERIC DEFAULT 0,
    gapok NUMERIC DEFAULT 0,
    gaji_lembur NUMERIC DEFAULT 0,
    u_k NUMERIC DEFAULT 0,
    u_m NUMERIC DEFAULT 0,
    uang_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    hasil_gaji NUMERIC DEFAULT 0,
    keterangan TEXT,
    keluar_masuk TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. SECURITY POLICIES (Agar tidak error permission denied)
ALTER TABLE public.master_gaji ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penyesuaian_gaji_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.karyawan_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_harian_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laporan_bulanan_pabrik ENABLE ROW LEVEL SECURITY;

-- Policy Drop & Recreate (Safe)
DO $$ 
BEGIN
    -- Master Gaji
    DROP POLICY IF EXISTS "Public Access" ON public.master_gaji;
    CREATE POLICY "Public Access" ON public.master_gaji FOR ALL USING (true) WITH CHECK (true);
    
    -- Penyesuaian
    DROP POLICY IF EXISTS "Public Access" ON public.penyesuaian_gaji_pabrik;
    CREATE POLICY "Public Access" ON public.penyesuaian_gaji_pabrik FOR ALL USING (true) WITH CHECK (true);

    -- Karyawan
    DROP POLICY IF EXISTS "Public Access" ON public.karyawan_pabrik;
    CREATE POLICY "Public Access" ON public.karyawan_pabrik FOR ALL USING (true) WITH CHECK (true);

    -- Presensi
    DROP POLICY IF EXISTS "Public Access" ON public.presensi_harian_pabrik;
    CREATE POLICY "Public Access" ON public.presensi_harian_pabrik FOR ALL USING (true) WITH CHECK (true);

    -- Laporan
    DROP POLICY IF EXISTS "Public Access" ON public.laporan_bulanan_pabrik;
    CREATE POLICY "Public Access" ON public.laporan_bulanan_pabrik FOR ALL USING (true) WITH CHECK (true);
END $$;

-- Grant Access
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
