-- SCRIPT PERBAIKAN MASTER SKU
-- Jalankan script ini di SQL Editor Supabase untuk memperbaiki tabel master_sku

-- 1. Pastikan tabel ada dengan kolom yang benar
CREATE TABLE IF NOT EXISTS public.master_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_sku TEXT NOT NULL UNIQUE,
    nama TEXT NOT NULL,
    deskripsi TEXT,
    kategori TEXT DEFAULT 'Lainnya',
    satuan TEXT DEFAULT 'Pcs',
    min_stock NUMERIC DEFAULT 0,
    hpp NUMERIC DEFAULT 0,
    harga_jual NUMERIC DEFAULT 0,
    hpp_updated_at DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tambahkan kolom jika belum ada (untuk tabel yang sudah ada tapi kurang kolom)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'master_sku' AND column_name = 'harga_jual') THEN
        ALTER TABLE public.master_sku ADD COLUMN harga_jual NUMERIC DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'master_sku' AND column_name = 'hpp_updated_at') THEN
        ALTER TABLE public.master_sku ADD COLUMN hpp_updated_at DATE;
    END IF;
END $$;

-- 3. Perbaiki Index untuk performa pencarian
CREATE INDEX IF NOT EXISTS idx_master_sku_kode ON public.master_sku(kode_sku);
CREATE INDEX IF NOT EXISTS idx_master_sku_nama ON public.master_sku(nama);

-- 4. Perbaiki Security (RLS) agar tidak error permission denied
ALTER TABLE public.master_sku ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama jika ada untuk menghindari duplikat
DROP POLICY IF EXISTS "Public Access SKU" ON public.master_sku;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.master_sku;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.master_sku;
DROP POLICY IF EXISTS "Enable update for all users" ON public.master_sku;
DROP POLICY IF EXISTS "Enable delete for all users" ON public.master_sku;

-- Buat policy baru yang mengizinkan semua akses (untuk internal system)
CREATE POLICY "Public Access SKU" ON public.master_sku FOR ALL USING (true) WITH CHECK (true);

-- Grant akses ke role service
GRANT ALL ON public.master_sku TO anon;
GRANT ALL ON public.master_sku TO authenticated;
GRANT ALL ON public.master_sku TO service_role;
