-- =================================================================
-- SETUP GAJI HARIAN SYNC (MIRROR PRESENSI)
-- =================================================================

-- 1. Pastikan Tabel Target Ada
CREATE TABLE IF NOT EXISTS public.gaji_harian_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    grade TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur TEXT,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    divisi TEXT, -- Hasil Join
    gaji NUMERIC DEFAULT 0, -- Placeholder
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_gaji_harian_garut_entry UNIQUE (tanggal, kode)
);

-- 2. Function Sync (Trigger Logic)
CREATE OR REPLACE FUNCTION sync_presensi_to_gaji_harian()
RETURNS TRIGGER AS $$
DECLARE
    v_divisi TEXT;
    v_grade TEXT;
BEGIN
    -- A. HANDLE DELETE
    IF (TG_OP = 'DELETE') THEN
        DELETE FROM public.gaji_harian_pabrik_garut 
        WHERE tanggal = OLD.tanggal AND kode = OLD.kode;
        RETURN OLD;
    END IF;

    -- B. HANDLE INSERT / UPDATE
    
    -- 1. Ambil Divisi dari Data Karyawan (Join Logic)
    SELECT divisi INTO v_divisi
    FROM public.data_karyawan_pabrik_garut
    WHERE kode = NEW.kode AND bulan = NEW.bulan
    LIMIT 1;

    -- 2. Tentukan Grade berdasarkan Periode
    IF NEW.periode = 'Periode 2' THEN
        v_grade := NEW.grade_p2;
    ELSE
        v_grade := NEW.grade_p1;
    END IF;

    -- 3. Upsert ke Tabel Gaji Harian
    INSERT INTO public.gaji_harian_pabrik_garut (
        tanggal, kode, grade, bulan, kehadiran, lembur, 
        periode, perusahaan, keterangan, divisi, gaji, updated_at
    )
    VALUES (
        NEW.tanggal, NEW.kode, v_grade, NEW.bulan, NEW.kehadiran, NEW.lembur,
        NEW.periode, NEW.perusahaan, NEW.keterangan, v_divisi, 0, NOW()
    )
    ON CONFLICT (tanggal, kode) DO UPDATE SET
        grade = EXCLUDED.grade,
        bulan = EXCLUDED.bulan,
        kehadiran = EXCLUDED.kehadiran,
        lembur = EXCLUDED.lembur,
        periode = EXCLUDED.periode,
        perusahaan = EXCLUDED.perusahaan,
        keterangan = EXCLUDED.keterangan,
        divisi = EXCLUDED.divisi, -- Update divisi jika berubah
        updated_at = NOW();

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Pasang Trigger
DROP TRIGGER IF EXISTS trg_sync_gaji_harian ON public.presensi_harian_pabrik_garut;
CREATE TRIGGER trg_sync_gaji_harian
AFTER INSERT OR UPDATE OR DELETE ON public.presensi_harian_pabrik_garut
FOR EACH ROW EXECUTE FUNCTION sync_presensi_to_gaji_harian();

-- 4. Backfill Data (Isi data yang sudah ada)
INSERT INTO public.gaji_harian_pabrik_garut (
    tanggal, kode, grade, bulan, kehadiran, lembur, 
    periode, perusahaan, keterangan, divisi, gaji, updated_at
)
SELECT 
    p.tanggal, p.kode, 
    CASE WHEN p.periode = 'Periode 2' THEN p.grade_p2 ELSE p.grade_p1 END,
    p.bulan, p.kehadiran, p.lembur,
    p.periode, p.perusahaan, p.keterangan,
    k.divisi,
    0,
    NOW()
FROM public.presensi_harian_pabrik_garut p
LEFT JOIN public.data_karyawan_pabrik_garut k ON p.kode = k.kode AND p.bulan = k.bulan
ON CONFLICT (tanggal, kode) DO UPDATE SET
    grade = EXCLUDED.grade,
    divisi = EXCLUDED.divisi,
    kehadiran = EXCLUDED.kehadiran,
    lembur = EXCLUDED.lembur,
    keterangan = EXCLUDED.keterangan;

-- 5. Security
ALTER TABLE public.gaji_harian_pabrik_garut ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Gaji Harian" ON public.gaji_harian_pabrik_garut;
CREATE POLICY "Public Access Gaji Harian" ON public.gaji_harian_pabrik_garut FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.gaji_harian_pabrik_garut TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
