-- Drop existing table if exists to ensure clean state
DROP TABLE IF EXISTS public.stock_opname_items CASCADE;

-- Create the correct table for Stock Opname Items
CREATE TABLE public.stock_opname_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_opname_id BIGINT REFERENCES public.stock_opname(id) ON DELETE CASCADE,
    sku_id BIGINT REFERENCES public.master_sku(id),
    qty_sistem NUMERIC DEFAULT 0,
    qty_fisik NUMERIC DEFAULT 0,
    selisih NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.stock_opname_items ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Public Access Items" ON public.stock_opname_items FOR ALL USING (true) WITH CHECK (true);

-- Grant Permissions
GRANT ALL ON public.stock_opname_items TO anon, authenticated, service_role;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload config';
