-- Buat Tabel Penyesuaian Gaji
CREATE TABLE IF NOT EXISTS public.penyesuaian_gaji_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    periode TEXT NOT NULL,
    perusahaan TEXT,
    kode TEXT NOT NULL,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_penyesuaian_gaji UNIQUE (bulan, periode, kode)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_penyesuaian_gaji_bulan ON public.penyesuaian_gaji_pabrik(bulan);
CREATE INDEX IF NOT EXISTS idx_penyesuaian_gaji_kode ON public.penyesuaian_gaji_pabrik(kode);

-- RLS & Security
ALTER TABLE public.penyesuaian_gaji_pabrik ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Penyesuaian" ON public.penyesuaian_gaji_pabrik;
CREATE POLICY "Public Access Penyesuaian" ON public.penyesuaian_gaji_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.penyesuaian_gaji_pabrik TO anon, authenticated, service_role;

-- Refresh Cache
NOTIFY pgrst, 'reload config';
