-- =================================================================
-- 1. CREATE TABLE: laporan_bulanan_admin_pabrik
-- =================================================================
CREATE TABLE IF NOT EXISTS public.laporan_bulanan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    jabatan TEXT,
    divisi TEXT,
    perusahaan TEXT,
    
    -- Attendance Stats
    h INT DEFAULT 0,
    i INT DEFAULT 0,
    s INT DEFAULT 0,
    t INT DEFAULT 0,
    lembur_jam NUMERIC DEFAULT 0,
    lembur_tm_jam NUMERIC DEFAULT 0,
    
    -- Salary Components (Source: Master)
    gaji_pokok NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    
    -- Calculated Components
    uang_lembur NUMERIC DEFAULT 0, -- (Lembur Biasa + Lembur TM)
    uang_kehadiran NUMERIC DEFAULT 0, -- After deductions
    insentif NUMERIC DEFAULT 0, -- After deductions
    tunjangan_transportasi NUMERIC DEFAULT 0,
    tunjangan_jabatan NUMERIC DEFAULT 0,
    
    -- Totals
    total_gaji_akhir_bulan NUMERIC DEFAULT 0, -- (Gapok + Lembur + Makan)
    total_gaji_tgl_15 NUMERIC DEFAULT 0,      -- (Kehadiran + Insentif + Transport + Jabatan)
    total_gaji_keseluruhan NUMERIC DEFAULT 0, -- (Total Akhir Bulan + Total Tgl 15)
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_laporan_admin_bulan_kode UNIQUE (bulan, kode)
);

-- Enable RLS
ALTER TABLE public.laporan_bulanan_admin_pabrik ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Admin Report" ON public.laporan_bulanan_admin_pabrik;
CREATE POLICY "Public Access Admin Report" ON public.laporan_bulanan_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.laporan_bulanan_admin_pabrik TO anon, authenticated, service_role;

-- =================================================================
-- 2. CALCULATION LOGIC FUNCTION
-- =================================================================
CREATE OR REPLACE FUNCTION calculate_admin_monthly_report(p_bulan TEXT, p_kode TEXT)
RETURNS VOID AS $$
DECLARE
    emp RECORD;
    master RECORD;
    stats RECORD;
    
    v_lembur_biasa NUMERIC := 0;
    v_lembur_tm NUMERIC := 0;
    v_total_lembur NUMERIC := 0;
    
    v_uang_kehadiran NUMERIC := 0;
    v_insentif NUMERIC := 0;
    
    v_total_15 NUMERIC := 0;
    v_total_akhir NUMERIC := 0;
    v_grand_total NUMERIC := 0;
BEGIN
    -- A. Get Employee Info
    SELECT * INTO emp FROM data_karyawan_admin_pabrik 
    WHERE kode = p_kode AND bulan = p_bulan LIMIT 1;
    
    IF NOT FOUND THEN 
        -- If employee deleted, remove report
        DELETE FROM laporan_bulanan_admin_pabrik WHERE kode = p_kode AND bulan = p_bulan;
        RETURN; 
    END IF;

    -- B. Get Master Salary
    SELECT * INTO master FROM master_gaji_admin_pabrik
    WHERE jabatan = emp.jabatan AND divisi = emp.divisi AND bulan = p_bulan LIMIT 1;
    
    -- C. Get Attendance Stats
    SELECT 
        COUNT(*) FILTER (WHERE kehadiran ILIKE 'Hadir' OR kehadiran = 'H') as h,
        COUNT(*) FILTER (WHERE kehadiran ILIKE 'Izin' OR kehadiran = 'I') as i,
        COUNT(*) FILTER (WHERE kehadiran ILIKE 'Sakit' OR kehadiran = 'S') as s,
        COUNT(*) FILTER (WHERE kehadiran ILIKE 'Alpha' OR kehadiran = 'A' OR kehadiran = 'T') as t,
        COALESCE(SUM(jam_lembur), 0) as lembur_jam,
        COALESCE(SUM(lembur_tm), 0) as lembur_tm_jam
    INTO stats
    FROM presensi_harian_admin_pabrik
    WHERE kode = p_kode AND bulan = p_bulan;

    -- D. Perform Calculations
    
    -- 1. Lembur Calculation
    v_lembur_biasa := stats.lembur_jam * COALESCE(master.lembur_per_jam, 0);
    v_lembur_tm := stats.lembur_tm_jam * COALESCE(master.lembur_tanggal_merah, 0);
    v_total_lembur := v_lembur_biasa + v_lembur_tm;
    
    -- 2. Uang Kehadiran (With Deductions)
    v_uang_kehadiran := COALESCE(master.uang_kehadiran, 0);
    v_uang_kehadiran := v_uang_kehadiran - (stats.s * 25000);
    v_uang_kehadiran := v_uang_kehadiran - (stats.i * 50000);
    v_uang_kehadiran := v_uang_kehadiran - (stats.t * 50000);
    IF v_uang_kehadiran < 0 THEN v_uang_kehadiran := 0; END IF;
    
    -- 3. Insentif (Zero if any absence I/S/T)
    IF (stats.i + stats.s + stats.t > 0) THEN
        v_insentif := 0;
    ELSE
        v_insentif := COALESCE(master.insentif, 0);
    END IF;
    
    -- 4. Group Totals
    -- Gaji Tanggal 15 (Tunjangan)
    v_total_15 := v_uang_kehadiran + v_insentif + COALESCE(master.tunjangan_transportasi, 0) + COALESCE(master.tunjangan_jabatan, 0);
    
    -- Gaji Akhir Bulan (Pokok + Lembur + Makan)
    v_total_akhir := COALESCE(master.gaji_pokok, 0) + v_total_lembur + COALESCE(master.uang_makan, 0);
    
    -- Grand Total
    v_grand_total := v_total_15 + v_total_akhir;

    -- E. Upsert Report
    INSERT INTO public.laporan_bulanan_admin_pabrik (
        bulan, kode, nama, jabatan, divisi, perusahaan,
        h, i, s, t, lembur_jam, lembur_tm_jam,
        gaji_pokok, uang_makan, uang_lembur,
        uang_kehadiran, insentif, tunjangan_transportasi, tunjangan_jabatan,
        total_gaji_akhir_bulan, total_gaji_tgl_15, total_gaji_keseluruhan,
        updated_at
    ) VALUES (
        p_bulan, p_kode, emp.nama, emp.jabatan, emp.divisi, emp.perusahaan,
        stats.h, stats.i, stats.s, stats.t, stats.lembur_jam, stats.lembur_tm_jam,
        COALESCE(master.gaji_pokok, 0), COALESCE(master.uang_makan, 0), v_total_lembur,
        v_uang_kehadiran, v_insentif, COALESCE(master.tunjangan_transportasi, 0), COALESCE(master.tunjangan_jabatan, 0),
        v_total_akhir, v_total_15, v_grand_total,
        NOW()
    )
    ON CONFLICT (bulan, kode) DO UPDATE SET
        nama = EXCLUDED.nama,
        jabatan = EXCLUDED.jabatan,
        divisi = EXCLUDED.divisi,
        perusahaan = EXCLUDED.perusahaan,
        h = EXCLUDED.h, i = EXCLUDED.i, s = EXCLUDED.s, t = EXCLUDED.t,
        lembur_jam = EXCLUDED.lembur_jam, lembur_tm_jam = EXCLUDED.lembur_tm_jam,
        gaji_pokok = EXCLUDED.gaji_pokok, uang_makan = EXCLUDED.uang_makan, uang_lembur = EXCLUDED.uang_lembur,
        uang_kehadiran = EXCLUDED.uang_kehadiran, insentif = EXCLUDED.insentif,
        tunjangan_transportasi = EXCLUDED.tunjangan_transportasi, tunjangan_jabatan = EXCLUDED.tunjangan_jabatan,
        total_gaji_akhir_bulan = EXCLUDED.total_gaji_akhir_bulan,
        total_gaji_tgl_15 = EXCLUDED.total_gaji_tgl_15,
        total_gaji_keseluruhan = EXCLUDED.total_gaji_keseluruhan,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- =================================================================
-- 3. TRIGGERS FOR AUTO-CALCULATION
-- =================================================================

-- Trigger 1: When Presensi Changes
CREATE OR REPLACE FUNCTION trigger_recalc_admin_presensi()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        PERFORM calculate_admin_monthly_report(OLD.bulan, OLD.kode);
    ELSE
        PERFORM calculate_admin_monthly_report(NEW.bulan, NEW.kode);
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_presensi_update ON public.presensi_harian_admin_pabrik;
CREATE TRIGGER trg_admin_presensi_update
AFTER INSERT OR UPDATE OR DELETE ON public.presensi_harian_admin_pabrik
FOR EACH ROW EXECUTE FUNCTION trigger_recalc_admin_presensi();

-- Trigger 2: When Employee Data Changes (Name, Jabatan, Divisi)
CREATE OR REPLACE FUNCTION trigger_recalc_admin_karyawan()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        DELETE FROM laporan_bulanan_admin_pabrik WHERE kode = OLD.kode AND bulan = OLD.bulan;
    ELSE
        PERFORM calculate_admin_monthly_report(NEW.bulan, NEW.kode);
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_karyawan_update ON public.data_karyawan_admin_pabrik;
CREATE TRIGGER trg_admin_karyawan_update
AFTER INSERT OR UPDATE OR DELETE ON public.data_karyawan_admin_pabrik
FOR EACH ROW EXECUTE FUNCTION trigger_recalc_admin_karyawan();

-- Trigger 3: When Master Salary Changes
CREATE OR REPLACE FUNCTION trigger_recalc_admin_master()
RETURNS TRIGGER AS $$
DECLARE
    r_emp RECORD;
BEGIN
    -- Find all employees affected by this master salary change
    FOR r_emp IN 
        SELECT kode, bulan FROM data_karyawan_admin_pabrik
        WHERE jabatan = NEW.jabatan AND divisi = NEW.divisi AND bulan = NEW.bulan
    LOOP
        PERFORM calculate_admin_monthly_report(r_emp.bulan, r_emp.kode);
    END LOOP;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_master_update ON public.master_gaji_admin_pabrik;
CREATE TRIGGER trg_admin_master_update
AFTER INSERT OR UPDATE ON public.master_gaji_admin_pabrik
FOR EACH ROW EXECUTE FUNCTION trigger_recalc_admin_master();

-- =================================================================
-- 4. MANUAL SYNC FUNCTION (RPC)
-- =================================================================
CREATE OR REPLACE FUNCTION sync_admin_monthly_report(p_bulan TEXT)
RETURNS text AS $$
DECLARE
    rec RECORD;
    counter INT := 0;
BEGIN
    -- Loop through all employees in that month
    FOR rec IN SELECT kode FROM data_karyawan_admin_pabrik WHERE bulan = p_bulan LOOP
        PERFORM calculate_admin_monthly_report(p_bulan, rec.kode);
        counter := counter + 1;
    END LOOP;
    
    RETURN 'Berhasil menghitung ulang ' || counter || ' data karyawan.';
END;
$$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload config';
