-- Buat Tabel Karyawan Pabrik
CREATE TABLE IF NOT EXISTS public.data_karyawan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L',
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    bulan TEXT NOT NULL,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Hapus constraint lama jika ada
ALTER TABLE public.data_karyawan_pabrik DROP CONSTRAINT IF EXISTS data_karyawan_pabrik_kode_key;
ALTER TABLE public.data_karyawan_pabrik DROP CONSTRAINT IF EXISTS unique_kode_bulan;

-- Buat constraint unik kombinasi kode dan bulan
ALTER TABLE public.data_karyawan_pabrik ADD CONSTRAINT unique_kode_bulan UNIQUE (kode, bulan);

-- Buat Index untuk performa
CREATE INDEX IF NOT EXISTS idx_karyawan_pabrik_bulan ON public.data_karyawan_pabrik(bulan);
CREATE INDEX IF NOT EXISTS idx_karyawan_pabrik_kode ON public.data_karyawan_pabrik(kode);

-- Setup RLS
ALTER TABLE public.data_karyawan_pabrik ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Karyawan" ON public.data_karyawan_pabrik;
CREATE POLICY "Public Access Karyawan" ON public.data_karyawan_pabrik FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.data_karyawan_pabrik TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
