-- Migration: Create Data Penyesuaian Borongan Pabrik Garut
-- Description: Tabel untuk menyimpan data kasbon/penyesuaian gaji borongan

CREATE TABLE IF NOT EXISTS public.data_penyesuaian_borongan_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    periode TEXT NOT NULL,
    perusahaan TEXT,
    kode TEXT NOT NULL,
    kasbon NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Constraint: Mencegah duplikasi data untuk karyawan yang sama di periode bulan yang sama
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_penyesuaian_borongan_garut') THEN
        ALTER TABLE public.data_penyesuaian_borongan_pabrik_garut 
        ADD CONSTRAINT unique_penyesuaian_borongan_garut UNIQUE (bulan, periode, kode);
    END IF;
END $$;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_penyesuaian_borongan_garut_bulan ON public.data_penyesuaian_borongan_pabrik_garut(bulan);
CREATE INDEX IF NOT EXISTS idx_penyesuaian_borongan_garut_kode ON public.data_penyesuaian_borongan_pabrik_garut(kode);

-- Enable Row Level Security (RLS)
ALTER TABLE public.data_penyesuaian_borongan_pabrik_garut ENABLE ROW LEVEL SECURITY;

-- Policies (Public Access for simplicity in this module, matching existing patterns)
DROP POLICY IF EXISTS "Public Access Penyesuaian Borongan Garut" ON public.data_penyesuaian_borongan_pabrik_garut;

CREATE POLICY "Public Access Penyesuaian Borongan Garut" 
ON public.data_penyesuaian_borongan_pabrik_garut 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- Grant Permissions
GRANT ALL ON public.data_penyesuaian_borongan_pabrik_garut TO anon, authenticated, service_role;

-- Refresh Schema Cache (Supabase PostgREST)
NOTIFY pgrst, 'reload config';
