-- 1. Tabel Data Karyawan Admin
CREATE TABLE IF NOT EXISTS public.data_karyawan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L',
    jabatan TEXT, -- Link ke Master Gaji (Grade/Jabatan)
    divisi TEXT,
    perusahaan TEXT DEFAULT 'CV GARUT',
    bulan TEXT,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_kode_bulan_admin UNIQUE (kode, bulan)
);

-- 2. Tabel Presensi Harian Admin
CREATE TABLE IF NOT EXISTS public.presensi_harian_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    nama TEXT,
    jabatan TEXT,
    divisi TEXT,
    perusahaan TEXT,
    bulan TEXT,
    kehadiran TEXT, -- Hadir, Sakit, Izin, Alpha
    jam_lembur NUMERIC DEFAULT 0,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_presensi_admin_harian UNIQUE (tanggal, kode)
);

-- 3. Tabel Laporan Bulanan Admin (Rekap Gaji)
CREATE TABLE IF NOT EXISTS public.laporan_bulanan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT,
    kode TEXT,
    nama TEXT,
    jabatan TEXT,
    divisi TEXT,
    perusahaan TEXT,
    
    -- Statistik Kehadiran
    hadir INT DEFAULT 0,
    sakit INT DEFAULT 0,
    izin INT DEFAULT 0,
    alpha INT DEFAULT 0,
    total_jam_lembur NUMERIC DEFAULT 0,
    total_lembur_tm NUMERIC DEFAULT 0, -- Lembur Tanggal Merah (Jam/Hari)

    -- Komponen Gaji (Snapshot dari Master saat generate)
    gaji_pokok NUMERIC DEFAULT 0,
    tunjangan_jabatan NUMERIC DEFAULT 0,
    tunjangan_transportasi NUMERIC DEFAULT 0,
    tunjangan_makan NUMERIC DEFAULT 0,
    uang_lembur NUMERIC DEFAULT 0,
    insentif NUMERIC DEFAULT 0,
    potongan NUMERIC DEFAULT 0,
    total_gaji NUMERIC DEFAULT 0,
    
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_laporan_admin_bulan UNIQUE (bulan, kode)
);

-- Enable RLS
ALTER TABLE public.data_karyawan_admin_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_harian_admin_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laporan_bulanan_admin_pabrik ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public Access Karyawan Admin" ON public.data_karyawan_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Presensi Admin" ON public.presensi_harian_admin_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Laporan Admin" ON public.laporan_bulanan_admin_pabrik FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.data_karyawan_admin_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.presensi_harian_admin_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.laporan_bulanan_admin_pabrik TO anon, authenticated, service_role;

-- TRIGGER: Auto-Fill Nama/Jabatan di Presensi saat Insert
CREATE OR REPLACE FUNCTION autofill_admin_presensi()
RETURNS TRIGGER AS $$
DECLARE
    v_nama TEXT;
    v_jabatan TEXT;
    v_divisi TEXT;
    v_perusahaan TEXT;
BEGIN
    SELECT nama, jabatan, divisi, perusahaan 
    INTO v_nama, v_jabatan, v_divisi, v_perusahaan
    FROM data_karyawan_admin_pabrik
    WHERE kode = NEW.kode AND bulan = NEW.bulan
    LIMIT 1;
    
    IF FOUND THEN
        NEW.nama := v_nama;
        NEW.jabatan := v_jabatan;
        NEW.divisi := v_divisi;
        NEW.perusahaan := v_perusahaan;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_autofill_admin_presensi
BEFORE INSERT OR UPDATE ON public.presensi_harian_admin_pabrik
FOR EACH ROW EXECUTE FUNCTION autofill_admin_presensi();
