-- [FIX] Ensure 'data_karyawan_admin_pabrik' has all required columns
-- This script is safe to run even if the table already exists.

-- 1. Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.data_karyawan_admin_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add columns if they are missing (Safe ALTER)
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS jenis_kelamin TEXT DEFAULT 'L';
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS jabatan TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS divisi TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS perusahaan TEXT DEFAULT 'CV GARUT';
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS bulan TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS keterangan TEXT;
ALTER TABLE public.data_karyawan_admin_pabrik ADD COLUMN IF NOT EXISTS status_aktif BOOLEAN DEFAULT true;

-- 3. Ensure Unique Constraint for (kode, bulan) to prevent duplicates
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_kode_bulan_admin') THEN
        ALTER TABLE public.data_karyawan_admin_pabrik 
        ADD CONSTRAINT unique_kode_bulan_admin UNIQUE (kode, bulan);
    END IF;
END $$;

-- 4. Refresh Schema Cache (Important for PostgREST to see new columns)
NOTIFY pgrst, 'reload config';
