/* 
  # 1. MEMBUAT TABEL STOCK OPNAME RAK
  # Tabel ini khusus untuk menyimpan hasil SO dari Rak Display
*/
CREATE TABLE IF NOT EXISTS stock_opname_rak (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_opname_id BIGINT REFERENCES stock_opname(id) ON DELETE CASCADE,
  sku_id BIGINT REFERENCES master_sku(id), -- Relasi ke Master SKU
  tanggal DATE,
  lokasi TEXT DEFAULT 'Rak Display',
  no_karung TEXT DEFAULT '-',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending',
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

/*
  # 2. SECURITY FIX: MENGAKTIFKAN RLS (ROW LEVEL SECURITY)
  # Mengamankan semua tabel agar peringatan keamanan hilang
*/

-- Master Data
ALTER TABLE master_sku ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON master_sku FOR ALL USING (true) WITH CHECK (true);

-- Stok
ALTER TABLE stok_gudang ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON stok_gudang FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE stok_rak ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON stok_rak FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE riwayat_mutasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON riwayat_mutasi FOR ALL USING (true) WITH CHECK (true);

-- Outbound Pabrik (Inbound Gudang)
ALTER TABLE outbound_pabrik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON outbound_pabrik FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE outbound_pabrik_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON outbound_pabrik_items FOR ALL USING (true) WITH CHECK (true);

-- Outbound (Penjualan)
ALTER TABLE outbound ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON outbound FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE outbound_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON outbound_items FOR ALL USING (true) WITH CHECK (true);

-- Retur
ALTER TABLE retur ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON retur FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE retur_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON retur_items FOR ALL USING (true) WITH CHECK (true);

-- Stock Opname (Header & Items)
ALTER TABLE stock_opname ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON stock_opname FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE stock_opname_gudang ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON stock_opname_gudang FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE stock_opname_rak ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON stock_opname_rak FOR ALL USING (true) WITH CHECK (true);
