-- 1. Buat Tabel master_gaji
CREATE TABLE IF NOT EXISTS public.master_gaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    grade TEXT NOT NULL,
    gaji_pokok NUMERIC DEFAULT 0,
    gaji_harian NUMERIC DEFAULT 0,
    gaji_setengah_hari NUMERIC DEFAULT 0,
    gaji_per_jam NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    uang_makan NUMERIC DEFAULT 0,
    uang_makan_harian NUMERIC DEFAULT 0,
    uang_kehadiran NUMERIC DEFAULT 0,
    uang_kehadiran_harian NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Setup RLS & Policies
ALTER TABLE public.master_gaji ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Master Gaji" ON public.master_gaji;
CREATE POLICY "Public Access Master Gaji" ON public.master_gaji FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.master_gaji TO anon, authenticated, service_role;

-- 3. Refresh Cache
NOTIFY pgrst, 'reload config';
