-- 1. Buat Tabel Karyawan Pabrik
CREATE TABLE IF NOT EXISTS public.karyawan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L', -- P/L
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    bulan TEXT NOT NULL, -- Format: "Oktober 2025"
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tambahkan Constraint UNIK (PENTING)
-- Aturan: Kombinasi (Kode + Bulan) harus unik.
-- Artinya: 
--   - Kode 'K001' di Bulan 'Oktober 2025' -> OK
--   - Kode 'K001' di Bulan 'November 2025' -> OK (Beda Bulan)
--   - Kode 'K001' di Bulan 'Oktober 2025' lagi -> GAGAL (Duplikat)

DO $$
BEGIN
    -- Hapus constraint lama jika ada (untuk reset)
    ALTER TABLE public.karyawan_pabrik DROP CONSTRAINT IF EXISTS unique_kode_bulan;
    
    -- Tambahkan constraint baru
    ALTER TABLE public.karyawan_pabrik ADD CONSTRAINT unique_kode_bulan UNIQUE (kode, bulan);
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Constraint unique_kode_bulan mungkin sudah ada.';
END $$;

-- 3. Indexing untuk pencarian cepat
CREATE INDEX IF NOT EXISTS idx_karyawan_kode ON public.karyawan_pabrik(kode);
CREATE INDEX IF NOT EXISTS idx_karyawan_bulan ON public.karyawan_pabrik(bulan);

-- 4. Security Policy (RLS) agar bisa diakses aplikasi
ALTER TABLE public.karyawan_pabrik ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Karyawan" ON public.karyawan_pabrik;
CREATE POLICY "Public Access Karyawan" ON public.karyawan_pabrik FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.karyawan_pabrik TO anon, authenticated, service_role;
