-- MIGRATION: Fix Struktur Tabel Karyawan Pabrik
-- Tujuannya: Menyesuaikan kolom dan menambahkan validasi anti-duplikat (Kode + Bulan)

-- 1. Pastikan Tabel Ada
CREATE TABLE IF NOT EXISTS public.karyawan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Perbaiki / Tambah Kolom (Agar data lama aman, kita gunakan IF NOT EXISTS atau RENAME)
DO $$
BEGIN
    -- Kolom: kode
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='kode') THEN
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='kode_karyawan') THEN
            ALTER TABLE public.karyawan_pabrik RENAME COLUMN kode_karyawan TO kode;
        ELSE
            ALTER TABLE public.karyawan_pabrik ADD COLUMN kode TEXT;
        END IF;
    END IF;

    -- Kolom: nama
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='nama') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN nama TEXT;
    END IF;

    -- Kolom: jenis_kelamin (P/L)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='jenis_kelamin') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN jenis_kelamin TEXT DEFAULT 'L';
    END IF;

    -- Kolom: grade_p1
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='grade_p1') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN grade_p1 TEXT;
    END IF;

    -- Kolom: grade_p2
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='grade_p2') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN grade_p2 TEXT;
    END IF;

    -- Kolom: divisi
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='divisi') THEN
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='jabatan') THEN
            ALTER TABLE public.karyawan_pabrik RENAME COLUMN jabatan TO divisi;
        ELSE
            ALTER TABLE public.karyawan_pabrik ADD COLUMN divisi TEXT;
        END IF;
    END IF;

    -- Kolom: bulan
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='bulan') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN bulan TEXT;
    END IF;

    -- Kolom: keterangan
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='keterangan') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN keterangan TEXT;
    END IF;
    
    -- Kolom: status_aktif (Optional, default true)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='karyawan_pabrik' AND column_name='status_aktif') THEN
        ALTER TABLE public.karyawan_pabrik ADD COLUMN status_aktif BOOLEAN DEFAULT true;
    END IF;
END $$;

-- 3. BERSIHKAN CONSTRAINT LAMA (Jika Ada)
-- Kita hapus constraint unik pada 'kode' saja (jika ada), karena kita mau uniknya 'kode + bulan'
ALTER TABLE public.karyawan_pabrik DROP CONSTRAINT IF EXISTS karyawan_pabrik_kode_key;
ALTER TABLE public.karyawan_pabrik DROP CONSTRAINT IF EXISTS unique_kode_bulan;

-- 4. TAMBAHKAN CONSTRAINT BARU (UNIQUE KODE + BULAN)
-- Note: Jika ada data duplikat saat ini, perintah ini akan gagal. 
-- User harus menghapus duplikat manual atau truncate tabel dulu jika masih development.
DO $$
BEGIN
    BEGIN
        ALTER TABLE public.karyawan_pabrik ADD CONSTRAINT unique_kode_bulan UNIQUE (kode, bulan);
    EXCEPTION WHEN unique_violation THEN
        RAISE NOTICE 'Ada data duplikat (kode+bulan) di database. Constraint tidak bisa dibuat sebelum data dibersihkan.';
    END;
END $$;

-- 5. SECURITY POLICY (RLS)
ALTER TABLE public.karyawan_pabrik ENABLE ROW LEVEL SECURITY;

-- Hapus policy lama biar bersih
DROP POLICY IF EXISTS "Public Access Karyawan" ON public.karyawan_pabrik;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.karyawan_pabrik;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.karyawan_pabrik;
DROP POLICY IF EXISTS "Enable update for all users" ON public.karyawan_pabrik;
DROP POLICY IF EXISTS "Enable delete for all users" ON public.karyawan_pabrik;

-- Buat policy baru yang full access (untuk kemudahan penggunaan internal)
CREATE POLICY "Public Access Karyawan" ON public.karyawan_pabrik FOR ALL USING (true) WITH CHECK (true);

-- Grant akses
GRANT ALL ON public.karyawan_pabrik TO anon;
GRANT ALL ON public.karyawan_pabrik TO authenticated;
GRANT ALL ON public.karyawan_pabrik TO service_role;
