/* 
  PERBAIKAN ERROR 42804: TIPE DATA TIDAK COCOK
  Mengubah sku_id menjadi BIGINT agar sesuai dengan tabel master_sku
*/

-- 1. Hapus tabel yang bermasalah (jika ada)
DROP TABLE IF EXISTS stock_opname_gudang;

-- 2. Buat tabel baru dengan tipe data yang BENAR (BIGINT)
CREATE TABLE stock_opname_gudang (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_opname_id BIGINT REFERENCES stock_opname(id) ON DELETE CASCADE,
  sku_id BIGINT REFERENCES master_sku(id), -- PERBAIKAN DISINI: UUID DIUBAH JADI BIGINT
  tanggal DATE,
  lokasi TEXT DEFAULT 'Gudang Utama',
  no_karung TEXT DEFAULT '-',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending',
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Aktifkan Izin Akses (RLS)
ALTER TABLE stock_opname_gudang ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access" ON stock_opname_gudang
FOR ALL USING (true)
WITH CHECK (true);
