-- Create table for Gaji Harian Pabrik Garut (CV Adnan & Hanan)
CREATE TABLE IF NOT EXISTS public.gaji_harian_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    grade TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur TEXT,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    divisi TEXT,
    gaji NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add unique constraint to prevent duplicate entries for the same employee on the same day
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_gaji_harian_garut_entry') THEN
        ALTER TABLE public.gaji_harian_pabrik_garut 
        ADD CONSTRAINT unique_gaji_harian_garut_entry UNIQUE (tanggal, kode);
    END IF;
END $$;

-- Enable Row Level Security
ALTER TABLE public.gaji_harian_pabrik_garut ENABLE ROW LEVEL SECURITY;

-- Create Policy for Public Access (assuming internal tool usage)
DROP POLICY IF EXISTS "Public Access Gaji Harian Garut" ON public.gaji_harian_pabrik_garut;
CREATE POLICY "Public Access Gaji Harian Garut" ON public.gaji_harian_pabrik_garut FOR ALL USING (true) WITH CHECK (true);

-- Grant permissions
GRANT ALL ON public.gaji_harian_pabrik_garut TO anon, authenticated, service_role;

-- Refresh schema cache
NOTIFY pgrst, 'reload config';
