-- Create table for Input Data Produksi
CREATE TABLE IF NOT EXISTS public.input_data_produksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT,
    sku TEXT,
    qty NUMERIC DEFAULT 0,
    jumlah_orang NUMERIC DEFAULT 0,
    perusahaan TEXT,
    bagian TEXT,
    posisi TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.input_data_produksi ENABLE ROW LEVEL SECURITY;

-- Create Policy
DROP POLICY IF EXISTS "Public Access Production Input" ON public.input_data_produksi;
CREATE POLICY "Public Access Production Input" ON public.input_data_produksi FOR ALL USING (true) WITH CHECK (true);

-- Grant Permissions
GRANT ALL ON public.input_data_produksi TO anon, authenticated, service_role;
