-- 1. Buat Tabel Presensi Harian Pabrik
CREATE TABLE IF NOT EXISTS public.presensi_harian_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    grade_p1 TEXT,
    grade_p2 TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur TEXT,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_presensi_harian UNIQUE (tanggal, kode)
);

-- 2. Enable RLS
ALTER TABLE public.presensi_harian_pabrik ENABLE ROW LEVEL SECURITY;

-- 3. Buat Policy
DROP POLICY IF EXISTS "Public Access Presensi Harian" ON public.presensi_harian_pabrik;
CREATE POLICY "Public Access Presensi Harian" ON public.presensi_harian_pabrik FOR ALL USING (true) WITH CHECK (true);

-- 4. Grant Permissions
GRANT ALL ON public.presensi_harian_pabrik TO anon, authenticated, service_role;

-- 5. Trigger untuk update otomatis grade_p1 dan grade_p2 dari data_karyawan_pabrik
CREATE OR REPLACE FUNCTION update_presensi_grade()
RETURNS TRIGGER AS $$
BEGIN
    SELECT grade_p1, grade_p2 INTO NEW.grade_p1, NEW.grade_p2
    FROM public.karyawan_pabrik
    WHERE kode = NEW.kode AND bulan = NEW.bulan
    LIMIT 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_presensi_grade ON public.presensi_harian_pabrik;
CREATE TRIGGER trigger_update_presensi_grade
BEFORE INSERT OR UPDATE ON public.presensi_harian_pabrik
FOR EACH ROW EXECUTE FUNCTION update_presensi_grade();

-- 6. Refresh Cache
NOTIFY pgrst, 'reload config';
