/* 
  # PERBAIKAN DATABASE STOCK OPNAME
  # Silakan RUN kode ini di Supabase SQL Editor
*/

-- 1. Hapus tabel lama jika ada (agar bersih dari error)
DROP TABLE IF EXISTS stock_opname_gudang;

-- 2. Buat tabel baru dengan struktur LENGKAP
CREATE TABLE stock_opname_gudang (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_opname_id BIGINT REFERENCES stock_opname(id) ON DELETE CASCADE,
  sku_id UUID REFERENCES master_sku(id),
  tanggal DATE,
  lokasi TEXT DEFAULT 'Gudang Utama',
  no_karung TEXT DEFAULT '-',
  qty_sistem NUMERIC DEFAULT 0,
  qty_fisik NUMERIC DEFAULT 0,
  selisih NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending',
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Aktifkan fitur keamanan (RLS)
ALTER TABLE stock_opname_gudang ENABLE ROW LEVEL SECURITY;

-- 4. Beri izin akses penuh ke aplikasi (Public Access)
CREATE POLICY "Public Access" ON stock_opname_gudang
FOR ALL USING (true)
WITH CHECK (true);

-- 5. (Opsional) Tambahkan index agar pencarian cepat
CREATE INDEX IF NOT EXISTS idx_so_gudang_sku ON stock_opname_gudang(sku_id);
CREATE INDEX IF NOT EXISTS idx_so_gudang_so_id ON stock_opname_gudang(stock_opname_id);
