-- 1. Tabel Data Karyawan Pabrik
CREATE TABLE IF NOT EXISTS public.karyawan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode TEXT NOT NULL,
    nama TEXT NOT NULL,
    jenis_kelamin TEXT DEFAULT 'L',
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    bulan TEXT,
    keterangan TEXT,
    status_aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_karyawan_kode_bulan UNIQUE (kode, bulan)
);

-- 2. Tabel Presensi Harian Pabrik
CREATE TABLE IF NOT EXISTS public.presensi_harian_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    kode TEXT NOT NULL,
    grade_p1 TEXT,
    grade_p2 TEXT,
    bulan TEXT,
    kehadiran TEXT,
    lembur TEXT,
    periode TEXT,
    perusahaan TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_presensi_harian UNIQUE (tanggal, kode)
);

-- 3. Tabel Laporan Bulanan Pabrik (Hasil Kalkulasi)
CREATE TABLE IF NOT EXISTS public.laporan_bulanan_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    periode TEXT NOT NULL,
    perusahaan TEXT,
    kode TEXT NOT NULL,
    nama TEXT,
    grade_p1 TEXT,
    grade_p2 TEXT,
    divisi TEXT,
    
    -- Kehadiran
    h INT DEFAULT 0,
    i_b INT DEFAULT 0,
    i_tb INT DEFAULT 0,
    s_b INT DEFAULT 0,
    s_tb INT DEFAULT 0,
    t_b INT DEFAULT 0,
    t_tb INT DEFAULT 0,
    set_h INT DEFAULT 0,
    lp INT DEFAULT 0,
    tm INT DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    
    -- Gaji
    gapok NUMERIC DEFAULT 0,
    gaji_lembur NUMERIC DEFAULT 0,
    u_m NUMERIC DEFAULT 0,
    u_k NUMERIC DEFAULT 0,
    uang_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    hasil_gaji NUMERIC DEFAULT 0,
    
    keterangan TEXT,
    keluar_masuk TEXT,
    libur_perusahaan INT DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_laporan_bulanan UNIQUE (bulan, periode, kode)
);

-- SECURITY & RLS
ALTER TABLE public.karyawan_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_harian_pabrik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laporan_bulanan_pabrik ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access Karyawan" ON public.karyawan_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Presensi" ON public.presensi_harian_pabrik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Laporan" ON public.laporan_bulanan_pabrik FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.karyawan_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.presensi_harian_pabrik TO anon, authenticated, service_role;
GRANT ALL ON public.laporan_bulanan_pabrik TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
