-- 1. Buat Tabel Penyesuaian Gaji
CREATE TABLE IF NOT EXISTS public.penyesuaian_gaji_pabrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    periode TEXT NOT NULL,
    perusahaan TEXT NOT NULL,
    kode TEXT NOT NULL,
    penyesuaian_bonus NUMERIC DEFAULT 0,
    kasbon NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tambahkan Constraint Unik (Bulan + Periode + Kode) agar tidak duplikat
ALTER TABLE public.penyesuaian_gaji_pabrik ADD CONSTRAINT unique_penyesuaian_gaji UNIQUE (bulan, periode, kode);

-- 3. Setup RLS & Policies
ALTER TABLE public.penyesuaian_gaji_pabrik ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Penyesuaian Gaji" ON public.penyesuaian_gaji_pabrik;
CREATE POLICY "Public Access Penyesuaian Gaji" ON public.penyesuaian_gaji_pabrik FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.penyesuaian_gaji_pabrik TO anon, authenticated, service_role;

-- 4. Refresh Cache
NOTIFY pgrst, 'reload config';
