import React, { useState, useEffect } from 'react';
import { 
  Users, Shield, Plus, Search, Edit2, Trash2, RefreshCw,
  CheckCircle2, XCircle, Save, X, Copy, Database, Loader2, Lock,
  ChevronDown, ChevronRight, CheckSquare, Square
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../lib/supabase';
import { SuccessModal } from '../Warehouse/SuccessModal';
import { ErrorModal } from '../Warehouse/ErrorModal';
import { ConfirmationModal } from '../Warehouse/ConfirmationModal';

export const UserManagement: React.FC = () => {
  const [users, setUsers] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  
  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [selectedUser, setSelectedUser] = useState<any>(null);

  // Expanded State untuk Accordion Permission
  const [expandedModules, setExpandedModules] = useState<string[]>(['gudang', 'pabrik-garut']);

  // Feedback Modals
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });
  const [confirmModal, setConfirmModal] = useState<{ isOpen: boolean; onConfirm: () => void }>({ isOpen: false, onConfirm: () => {} });

  // Form Data
  const [formData, setFormData] = useState({
    email: '',
    full_name: '',
    role: 'Staff',
    status: 'active',
    permissions: [] as string[]
  });

  // --- KONFIGURASI MODUL & SUB-MODUL ---
  const MODULE_HIERARCHY = [
    { 
      id: 'dashboard', 
      label: 'Dashboard Utama',
      children: [] 
    },
    { 
      id: 'gudang', 
      label: 'Gudang & Stok',
      children: [
        { id: 'gudang-dashboard', label: 'Dashboard Gudang' },
        { id: 'gudang-outbound-pabrik', label: 'Terima Dari Pabrik (Outbound Pabrik)' },
        { id: 'gudang-inbound', label: 'Inbound Gudang (Cek Fisik)' },
        { id: 'gudang-stok', label: 'Stok Gudang Utama' },
        { id: 'gudang-rak', label: 'Stok Rak Display' },
        { id: 'gudang-outbound', label: 'Outbound (Penjualan)' },
        { id: 'gudang-retur', label: 'Retur Barang' },
        { id: 'gudang-rekap', label: 'Rekap Inventory' },
        { id: 'gudang-opname', label: 'Stock Opname' },
        { id: 'gudang-laporan', label: 'Laporan' },
        { id: 'gudang-master', label: 'Master SKU' },
      ]
    },
    { 
      id: 'gudang-garut', 
      label: 'Gudang Garut',
      children: [
        { id: 'garut-dashboard', label: 'Dashboard Garut' },
        { id: 'garut-stok', label: 'Stok Garut' },
        { id: 'garut-inbound', label: 'Barang Masuk' },
        { id: 'garut-outbound', label: 'Barang Keluar' },
      ] 
    },
    { 
      id: 'pabrik-garut', 
      label: 'Pabrik Garut (NEW)',
      children: [
        { id: 'pabrik-garut-absensi', label: 'Absensi Garut' },
        { id: 'pabrik-garut-gaji', label: 'Gaji Garut (Master)' },
        { id: 'pabrik-garut-gaji-borongan', label: 'Gaji Borongan Garut' },
        { id: 'pabrik-garut-gaji-admin', label: 'Gaji Admin Garut' },
        { id: 'pabrik-garut-gaji-staff', label: 'Gaji Staff Garut' },
        { id: 'pabrik-garut-gaji-harian', label: 'Gaji Harian Garut' },
        { id: 'pabrik-garut-output', label: 'Output Garut' },
        { id: 'pabrik-garut-hpp', label: 'HPP Garut' },
        { id: 'pabrik-garut-hpp-harian', label: 'HPP Harian Garut' },
        { id: 'pabrik-garut-stok-aksesoris', label: 'Stok Aksesoris Garut' },
        { id: 'pabrik-garut-stok-keperluan', label: 'Stok Keperluan Garut' },
      ]
    },
    { 
      id: 'finance', 
      label: 'Keuangan & Belanja',
      children: [
        { id: 'pembelanjaan', label: 'Pembelanjaan' },
      ]
    },
    { 
      id: 'marketing', 
      label: 'Marketing',
      children: [] 
    },
    { 
      id: 'system', 
      label: 'System Admin',
      children: [
        { id: 'settings', label: 'Pengaturan Sistem' },
        { id: 'users', label: 'Manajemen Pengguna' },
      ] 
    },
  ];

  const sqlFixCode = `
-- Tabel Manajemen Pengguna & Hak Akses
CREATE TABLE IF NOT EXISTS public.user_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'Staff', -- Admin, Manager, Staff
    status TEXT DEFAULT 'active', -- active, inactive
    permissions JSONB DEFAULT '[]', -- Menyimpan array ID modul yang diizinkan
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Security
ALTER TABLE public.user_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Users" ON public.user_access;
CREATE POLICY "Public Access Users" ON public.user_access FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.user_access TO anon, authenticated, service_role;

-- Insert Default Admin (Jika Kosong)
INSERT INTO public.user_access (email, full_name, role, permissions)
SELECT 'admin@system.com', 'Super Admin', 'Admin', '["dashboard", "gudang", "gudang-dashboard", "gudang-stok", "gudang-rak", "gudang-inbound", "gudang-outbound", "gudang-retur", "gudang-rekap", "gudang-laporan", "gudang-opname", "gudang-master", "pabrik-garut", "pabrik-garut-absensi", "pabrik-garut-gaji", "pabrik-garut-gaji-borongan", "pabrik-garut-gaji-staff", "pabrik-garut-output", "pabrik-garut-hpp", "settings", "users"]'
WHERE NOT EXISTS (SELECT 1 FROM public.user_access);
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlFixCode);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase untuk membuat tabel pengguna.' });
  };

  const fetchUsers = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    
    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      const { data, error } = await supabase
        .from('user_access')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        if (error.code === '42P01' || error.code === 'PGRST205') {
          setIsTableMissing(true);
        } else {
          throw error;
        }
      } else {
        setUsers(data || []);
      }
    } catch (error: any) {
      console.error("Error fetching users:", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  // --- HANDLERS ---

  const handleOpenModal = (user?: any) => {
    if (user) {
      setSelectedUser(user);
      setFormData({
        email: user.email,
        full_name: user.full_name,
        role: user.role,
        status: user.status,
        permissions: Array.isArray(user.permissions) ? user.permissions : []
      });
    } else {
      setSelectedUser(null);
      setFormData({
        email: '',
        full_name: '',
        role: 'Staff',
        status: 'active',
        permissions: []
      });
    }
    setIsModalOpen(true);
  };

  const toggleExpand = (moduleId: string) => {
    setExpandedModules(prev => 
      prev.includes(moduleId) ? prev.filter(id => id !== moduleId) : [...prev, moduleId]
    );
  };

  // LOGIKA CENTANG PARENT & CHILD
  const handlePermissionToggle = (id: string, isParent: boolean, children?: any[]) => {
    setFormData(prev => {
      let newPerms = [...prev.permissions];
      const isChecked = newPerms.includes(id);

      if (isParent) {
        // Jika Parent diklik
        if (isChecked) {
          // Uncheck Parent -> Uncheck semua anak
          newPerms = newPerms.filter(p => p !== id && !children?.some(c => c.id === p));
        } else {
          // Check Parent -> Check semua anak
          newPerms.push(id);
          children?.forEach(c => {
            if (!newPerms.includes(c.id)) newPerms.push(c.id);
          });
        }
      } else {
        // Jika Child diklik
        if (isChecked) {
          // Uncheck Child
          newPerms = newPerms.filter(p => p !== id);
        } else {
          // Check Child
          newPerms.push(id);
          // Auto Check Parent jika belum
          // Cari parent ID (agak manual disini karena struktur flat di state)
          const parent = MODULE_HIERARCHY.find(m => m.children.some(c => c.id === id));
          if (parent && !newPerms.includes(parent.id)) {
            newPerms.push(parent.id);
          }
        }
      }
      return { ...prev, permissions: newPerms };
    });
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);

    try {
      const payload = {
        email: formData.email,
        full_name: formData.full_name,
        role: formData.role,
        status: formData.status,
        permissions: formData.permissions,
        updated_at: new Date().toISOString()
      };

      if (selectedUser) {
        const { error } = await supabase.from('user_access').update(payload).eq('id', selectedUser.id);
        if (error) throw error;
      } else {
        const { error } = await supabase.from('user_access').insert([payload]);
        if (error) throw error;
      }

      setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data pengguna berhasil disimpan.' });
      setIsModalOpen(false);
      fetchUsers();
    } catch (error: any) {
      setErrorModal({ isOpen: true, title: 'Gagal Menyimpan', message: error.message });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = (id: number) => {
    setConfirmModal({
      isOpen: true,
      onConfirm: async () => {
        const { error } = await supabase.from('user_access').delete().eq('id', id);
        if (error) {
          setErrorModal({ isOpen: true, title: 'Gagal Hapus', message: error.message });
        } else {
          fetchUsers();
        }
        setConfirmModal({ isOpen: false, onConfirm: () => {} });
      }
    });
  };

  const filteredUsers = users.filter(u => 
    u.full_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    u.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-6 space-y-6 bg-erp-bg min-h-full">
      
      {/* HEADER */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <Users className="text-erp-pink" /> Manajemen Pengguna
          </h1>
          <p className="text-gray-600 text-sm mt-1">Kelola akses dan peran pengguna aplikasi</p>
        </div>
        <div className="flex gap-2">
          <button onClick={fetchUsers} className="p-2 bg-white border rounded-lg hover:bg-gray-50 text-gray-600 shadow-sm" title="Refresh">
            <RefreshCw size={18}/>
          </button>
          <button onClick={() => handleOpenModal()} className="bg-erp-pink text-white px-5 py-2.5 rounded-xl flex items-center gap-2 text-sm font-medium hover:bg-pink-600 shadow-md transition-all">
            <Plus size={18}/> Tambah Pengguna
          </button>
        </div>
      </div>

      {/* SEARCH */}
      <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
          <input 
            type="text" 
            placeholder="Cari Nama atau Email..." 
            value={searchTerm} 
            onChange={e => setSearchTerm(e.target.value)} 
            className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-erp-pink/50" 
          />
        </div>
      </div>

      {/* TABLE MISSING */}
      {isTableMissing ? (
        <div className="bg-white border border-red-200 rounded-xl p-8 text-center shadow-sm">
          <div className="bg-red-50 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
            <Database className="text-red-500" size={32} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 mb-2">Database Belum Siap</h3>
          <p className="text-gray-500 mb-6">Tabel <code>user_access</code> belum ditemukan.</p>
          <button onClick={handleCopySQL} className="bg-red-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 mx-auto hover:bg-red-700 shadow-lg transition-colors">
            <Copy size={18}/> Salin Kode SQL
          </button>
        </div>
      ) : (
        /* TABLE USERS */
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm">
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="bg-gray-50 text-gray-600 font-bold border-b border-gray-200">
                <tr>
                  <th className="px-6 py-4">Nama Lengkap</th>
                  <th className="px-6 py-4">Email</th>
                  <th className="px-6 py-4">Role</th>
                  <th className="px-6 py-4">Akses Modul</th>
                  <th className="px-6 py-4 text-center">Status</th>
                  <th className="px-6 py-4 text-center">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {isLoading ? (
                  <tr><td colSpan={6} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink"/> Memuat data...</td></tr>
                ) : filteredUsers.length > 0 ? (
                  filteredUsers.map((user) => (
                    <tr key={user.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-4 font-medium text-gray-900">{user.full_name}</td>
                      <td className="px-6 py-4 text-gray-600">{user.email}</td>
                      <td className="px-6 py-4">
                        <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                          user.role === 'Admin' ? 'bg-purple-100 text-purple-700' : 
                          user.role === 'Manager' ? 'bg-blue-100 text-blue-700' : 
                          'bg-gray-100 text-gray-700'
                        }`}>
                          {user.role}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex flex-wrap gap-1 max-w-xs">
                          {Array.isArray(user.permissions) && user.permissions.length > 0 ? (
                             <span className="text-xs text-gray-600">
                               {user.permissions.length} modul diizinkan
                             </span>
                          ) : (
                             <span className="text-gray-400 italic text-xs">Tidak ada akses</span>
                          )}
                        </div>
                      </td>
                      <td className="px-6 py-4 text-center">
                        {user.status === 'active' ? (
                          <span className="inline-flex items-center gap-1 text-green-600 text-xs font-bold bg-green-50 px-2 py-1 rounded-full">
                            <CheckCircle2 size={12}/> Aktif
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 text-red-600 text-xs font-bold bg-red-50 px-2 py-1 rounded-full">
                            <XCircle size={12}/> Non-Aktif
                          </span>
                        )}
                      </td>
                      <td className="px-6 py-4 text-center">
                        <div className="flex justify-center gap-2">
                          <button onClick={() => handleOpenModal(user)} className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Edit Akses">
                            <Edit2 size={16}/>
                          </button>
                          <button onClick={() => handleDelete(user.id)} className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors" title="Hapus User">
                            <Trash2 size={16}/>
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr><td colSpan={6} className="p-16 text-center text-gray-400 italic">Belum ada data pengguna.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* MODAL FORM */}
      {isModalOpen && (
        <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-white sticky top-0 z-10">
              <h3 className="font-bold text-xl text-gray-900 flex items-center gap-2">
                <Shield className="text-erp-pink"/> {selectedUser ? 'Edit Akses Pengguna' : 'Tambah Pengguna Baru'}
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-gray-600 transition-colors">
                <X size={24}/>
              </button>
            </div>
            
            <form onSubmit={handleSave} className="p-6 overflow-y-auto custom-scrollbar space-y-6">
              {/* INFO DASAR */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="md:col-span-2">
                  <label className="block text-sm font-semibold text-gray-700 mb-1.5">Nama Lengkap</label>
                  <input required value={formData.full_name} onChange={e => setFormData({...formData, full_name: e.target.value})} className="w-full border border-gray-300 p-2.5 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="Nama Karyawan" />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-1.5">Email</label>
                  <input required type="email" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} className="w-full border border-gray-300 p-2.5 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none" placeholder="email@perusahaan.com" />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-1.5">Role / Jabatan</label>
                  <select value={formData.role} onChange={e => setFormData({...formData, role: e.target.value})} className="w-full border border-gray-300 p-2.5 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none bg-white">
                    <option value="Staff">Staff</option>
                    <option value="Manager">Manager</option>
                    <option value="Admin">Admin</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-1.5">Status Akun</label>
                  <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})} className="w-full border border-gray-300 p-2.5 rounded-lg text-sm focus:ring-2 focus:ring-erp-pink outline-none bg-white">
                    <option value="active">Aktif</option>
                    <option value="inactive">Non-Aktif (Blokir)</option>
                  </select>
                </div>
              </div>

              {/* PERMISSIONS (HIERARCHICAL) */}
              <div className="border-t border-gray-100 pt-4">
                <div className="flex justify-between items-center mb-3">
                  <label className="block text-sm font-bold text-gray-800 flex items-center gap-2">
                    <Lock size={16} className="text-erp-pink"/> Hak Akses Modul
                  </label>
                  <button 
                    type="button" 
                    onClick={() => setFormData(prev => ({ ...prev, permissions: [] }))} 
                    className="text-xs text-red-600 hover:underline font-medium"
                  >
                    Reset Semua Akses
                  </button>
                </div>
                
                <div className="space-y-3">
                  {MODULE_HIERARCHY.map((module) => {
                    const isParentChecked = formData.permissions.includes(module.id);
                    const isExpanded = expandedModules.includes(module.id);
                    const hasChildren = module.children.length > 0;

                    return (
                      <div key={module.id} className="border border-gray-200 rounded-xl overflow-hidden">
                        {/* Parent Header */}
                        <div className={`p-3 flex items-center justify-between ${isParentChecked ? 'bg-green-50' : 'bg-gray-50'}`}>
                          <div className="flex items-center gap-3">
                            <button 
                              type="button"
                              onClick={() => toggleExpand(module.id)}
                              className={`p-1 rounded hover:bg-gray-200 transition-colors ${!hasChildren ? 'invisible' : ''}`}
                            >
                              {isExpanded ? <ChevronDown size={16}/> : <ChevronRight size={16}/>}
                            </button>
                            <div 
                              className="flex items-center gap-2 cursor-pointer select-none"
                              onClick={() => handlePermissionToggle(module.id, true, module.children)}
                            >
                              {isParentChecked ? (
                                <CheckSquare size={20} className="text-green-600" />
                              ) : (
                                <Square size={20} className="text-gray-400" />
                              )}
                              <span className={`font-bold text-sm ${isParentChecked ? 'text-green-800' : 'text-gray-700'}`}>
                                {module.label}
                              </span>
                            </div>
                          </div>
                        </div>

                        {/* Children */}
                        {hasChildren && isExpanded && (
                          <div className="p-3 pl-12 grid grid-cols-1 md:grid-cols-2 gap-3 bg-white border-t border-gray-100">
                            {module.children.map((child) => {
                              const isChildChecked = formData.permissions.includes(child.id);
                              return (
                                <div 
                                  key={child.id} 
                                  onClick={() => handlePermissionToggle(child.id, false)}
                                  className={`flex items-center gap-2 cursor-pointer select-none p-2 rounded hover:bg-gray-50 transition-colors border ${isChildChecked ? 'border-green-200 bg-green-50/50' : 'border-transparent'}`}
                                >
                                  {isChildChecked ? (
                                    <CheckSquare size={16} className="text-green-600" />
                                  ) : (
                                    <Square size={16} className="text-gray-300" />
                                  )}
                                  <span className={`text-sm ${isChildChecked ? 'text-green-700 font-medium' : 'text-gray-600'}`}>
                                    {child.label}
                                  </span>
                                </div>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-gray-100">
                <button type="button" onClick={() => setIsModalOpen(false)} className="px-6 py-2.5 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors">Batal</button>
                <button type="submit" disabled={isSaving} className="px-6 py-2.5 bg-erp-pink text-white rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-pink-600 shadow-sm transition-colors disabled:opacity-70">
                  {isSaving ? <Loader2 className="animate-spin" size={18}/> : <Save size={18}/>} Simpan Akses
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
      <ConfirmationModal isOpen={confirmModal.isOpen} onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })} onConfirm={confirmModal.onConfirm} title="Hapus Pengguna" message="Yakin ingin menghapus data pengguna ini?" confirmLabel="Hapus" isDangerous={true} />
    </div>
  );
};
