import React, { useState, useEffect, useMemo } from 'react';
import { 
  Search, RefreshCw, Loader2, Filter, Download, 
  Calculator, Database, Copy, AlertCircle, CheckCircle2, X,
  TrendingUp, Layers
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../../../lib/supabase';
import * as XLSX from 'xlsx';
import { SuccessModal } from '../../Warehouse/SuccessModal';
import { ErrorModal } from '../../Warehouse/ErrorModal';

export const BiayaNonJahit: React.FC = () => {
  const [data, setData] = useState<any[]>([]);
  const [outputData, setOutputData] = useState<any[]>([]); // Raw Output Data
  const [isLoading, setIsLoading] = useState(true);
  const [loadingOutput, setLoadingOutput] = useState(false);
  const [isRecalculating, setIsRecalculating] = useState(false);
  const [isTableMissing, setIsTableMissing] = useState(false);
  const [showSqlModal, setShowSqlModal] = useState(false);

  // Filters
  const [selectedMonth, setSelectedMonth] = useState('');
  const [availableMonths, setAvailableMonths] = useState<string[]>([]);
  const [searchTerm, setSearchTerm] = useState('');

  // Modals
  const [successModal, setSuccessModal] = useState({ isOpen: false, title: '', message: '' });
  const [errorModal, setErrorModal] = useState({ isOpen: false, title: '', message: '' });

  const formatRupiah = (value: number) => new Intl.NumberFormat('id-ID', { 
    style: 'currency', 
    currency: 'IDR', 
    minimumFractionDigits: 0,
    maximumFractionDigits: 0 
  }).format(value);

  // SQL Setup Code
  const sqlSetupCode = `
-- 1. Buat Tabel Biaya Operasional
CREATE TABLE IF NOT EXISTS public.biaya_operasional_pabrik_garut (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan TEXT NOT NULL,
    jenis_beban TEXT NOT NULL,
    kategori TEXT,
    nominal NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_biaya_ops_bulan_beban UNIQUE (bulan, jenis_beban)
);

-- Security
ALTER TABLE public.biaya_operasional_pabrik_garut ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access Biaya Ops" ON public.biaya_operasional_pabrik_garut;
CREATE POLICY "Public Access Biaya Ops" ON public.biaya_operasional_pabrik_garut FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.biaya_operasional_pabrik_garut TO anon, authenticated, service_role;

-- 2. Fungsi Generate Data (Hitung Ulang)
CREATE OR REPLACE FUNCTION generate_biaya_operasional_garut(p_bulan TEXT)
RETURNS text AS $$
DECLARE
    v_count INT := 0;
BEGIN
    -- Hapus data lama bulan ini
    DELETE FROM biaya_operasional_pabrik_garut WHERE bulan = p_bulan;

    -- A. Insert dari Laporan Pabrik Garut (Non Jahit)
    -- Filter: ADMIN, AKSESORIS, DRIVER, LUBANG KANCING, MEKANIK, OB
    INSERT INTO biaya_operasional_pabrik_garut (bulan, jenis_beban, kategori, nominal)
    SELECT
        bulan,
        divisi,
        CASE 
            WHEN divisi = 'ADMIN' THEN 'ADMIN PABRIK'
            ELSE 'NON JAHIT'
        END,
        SUM(COALESCE(gapok,0) + COALESCE(gaji_lembur,0) + COALESCE(u_k,0) + COALESCE(u_m,0) + COALESCE(uang_bonus,0))
    FROM laporan_bulanan_pabrik_garut
    WHERE bulan = p_bulan
      AND divisi IN ('ADMIN', 'AKSESORIS', 'DRIVER', 'LUBANG KANCING', 'MEKANIK', 'OB')
    GROUP BY bulan, divisi
    ON CONFLICT (bulan, jenis_beban) DO UPDATE 
    SET nominal = biaya_operasional_pabrik_garut.nominal + EXCLUDED.nominal;

    -- B. Insert dari Laporan Admin Pabrik (Semua Divisi)
    -- Kategori: ADMIN PABRIK
    INSERT INTO biaya_operasional_pabrik_garut (bulan, jenis_beban, kategori, nominal)
    SELECT
        bulan,
        divisi,
        'ADMIN PABRIK',
        SUM(COALESCE(total_gaji_keseluruhan,0))
    FROM laporan_bulanan_admin_pabrik
    WHERE bulan = p_bulan
    GROUP BY bulan, divisi
    ON CONFLICT (bulan, jenis_beban) DO UPDATE 
    SET nominal = biaya_operasional_pabrik_garut.nominal + EXCLUDED.nominal;

    -- C. Insert dari Laporan Staff Pabrik (Divisi STAFF)
    -- Kategori: STAFF PABRIK
    INSERT INTO biaya_operasional_pabrik_garut (bulan, jenis_beban, kategori, nominal)
    SELECT
        bulan,
        divisi,
        'STAFF PABRIK',
        SUM(COALESCE(gapok,0) + COALESCE(gaji_lembur,0) + COALESCE(u_m,0) + COALESCE(u_k,0) + COALESCE(uang_bonus,0))
    FROM laporan_bulanan_staff_pabrik
    WHERE bulan = p_bulan
      AND divisi = 'STAFF'
    GROUP BY bulan, divisi
    ON CONFLICT (bulan, jenis_beban) DO UPDATE 
    SET nominal = biaya_operasional_pabrik_garut.nominal + EXCLUDED.nominal;

    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN 'Berhasil generate data biaya operasional.';
END;
$$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload config';
  `;

  const handleCopySQL = () => {
    navigator.clipboard.writeText(sqlSetupCode);
    setSuccessModal({ isOpen: true, title: 'SQL Disalin', message: 'Silakan jalankan kode di SQL Editor Supabase.' });
  };

  // 1. Fetch Available Months
  useEffect(() => {
    const fetchMonths = async () => {
      if (!isSupabaseConfigured()) return;
      
      const { data: opsMonths } = await supabase
        .from('biaya_operasional_pabrik_garut')
        .select('bulan');
        
      const { data: reportMonths } = await supabase
        .from('laporan_bulanan_pabrik_garut')
        .select('bulan');

      const allMonths = new Set([
          ...(opsMonths?.map(d => d.bulan) || []),
          ...(reportMonths?.map(d => d.bulan) || [])
      ]);

      const months = Array.from(allMonths).filter(Boolean);
      
      const monthMap: Record<string, number> = {
        'januari': 1, 'februari': 2, 'maret': 3, 'april': 4, 'mei': 5, 'juni': 6,
        'juli': 7, 'agustus': 8, 'september': 9, 'oktober': 10, 'november': 11, 'desember': 12
      };
      
      const sortedMonths = months.sort((a, b) => {
        const partsA = a.split(' ');
        const partsB = b.split(' ');
        const yearA = parseInt(partsA[1]) || 0;
        const yearB = parseInt(partsB[1]) || 0;
        if (yearA !== yearB) return yearB - yearA;
        return (monthMap[partsB[0]?.toLowerCase()] || 0) - (monthMap[partsA[0]?.toLowerCase()] || 0);
      });

      setAvailableMonths(sortedMonths);
      if (sortedMonths.length > 0 && !selectedMonth) setSelectedMonth(sortedMonths[0]);
    };
    fetchMonths();
  }, []);

  // 2. Fetch Data (Biaya Non Jahit)
  const fetchData = async () => {
    setIsLoading(true);
    setIsTableMissing(false);
    
    if (!isSupabaseConfigured()) {
      setIsLoading(false);
      return;
    }

    try {
      let query = supabase
        .from('biaya_operasional_pabrik_garut')
        .select('*');

      if (selectedMonth) {
        query = query.eq('bulan', selectedMonth);
      }

      if (searchTerm) {
        query = query.ilike('jenis_beban', `%${searchTerm}%`);
      }

      const { data: result, error } = await query.order('kategori', { ascending: true }).order('jenis_beban', { ascending: true });

      if (error) {
        if (error.code === '42P01' || error.code === 'PGRST205' || error.message.includes('does not exist')) {
            setIsTableMissing(true);
        } else {
            throw error;
        }
      } else {
        setData(result || []);
      }
    } catch (error: any) {
      console.error("Fetch error:", error);
      if (!error.message?.includes('does not exist') && error.code !== 'PGRST205') {
          setErrorModal({ isOpen: true, title: 'Gagal Memuat Data', message: error.message });
      }
    } finally {
      setIsLoading(false);
    }
  };

  // 3. Fetch Output Line Data
  const fetchOutputData = async () => {
    if (!selectedMonth) return;
    setLoadingOutput(true);
    try {
        const { data, error } = await supabase
            .from('view_biaya_output_pabrik_garut')
            .select('bulan, perusahaan, bagian, sku, qty')
            .eq('bulan', selectedMonth)
            .in('bagian', ['LINE 1', 'LINE 2', 'LINE 3', 'LINE 4', 'LINE 5'])
            .order('bagian', { ascending: true });
        
        if (error) {
            console.warn("Output Line View Error:", error.message);
        } else {
            setOutputData(data || []);
        }
    } catch (err) {
        console.error("Error fetching output lines:", err);
    } finally {
        setLoadingOutput(false);
    }
  };

  useEffect(() => {
    fetchData();
    fetchOutputData();
  }, [selectedMonth, searchTerm]);

  // --- AGGREGATE OUTPUT DATA (Group by Bagian) ---
  const aggregatedOutput = useMemo(() => {
    const map = new Map();
    outputData.forEach(item => {
        const key = item.bagian; // Group by Line
        if (!map.has(key)) {
            map.set(key, {
                bulan: item.bulan,
                bagian: item.bagian,
                qty: 0
            });
        }
        const entry = map.get(key);
        entry.qty += Number(item.qty || 0);
    });
    return Array.from(map.values()).sort((a, b) => a.bagian.localeCompare(b.bagian));
  }, [outputData]);

  const totalOutputQty = aggregatedOutput.reduce((sum, item) => sum + item.qty, 0);

  // 4. Recalculate Handler
  const handleRecalculate = async () => {
    if (!selectedMonth) {
        alert("Pilih bulan terlebih dahulu.");
        return;
    }
    
    setIsRecalculating(true);
    try {
        const { error } = await supabase.rpc('generate_biaya_operasional_garut', { p_bulan: selectedMonth });
        
        if (error) {
            if (error.code === 'PGRST205' || error.message.includes('function') || error.message.includes('does not exist')) {
                setShowSqlModal(true);
                throw new Error("Fungsi database belum tersedia. Silakan setup database.");
            }
            throw error;
        }

        setSuccessModal({ isOpen: true, title: 'Berhasil', message: 'Data biaya operasional berhasil dihitung ulang.' });
        fetchData();
    } catch (error: any) {
        if (!showSqlModal) {
            setErrorModal({ isOpen: true, title: 'Gagal Hitung Ulang', message: error.message });
        }
    } finally {
        setIsRecalculating(false);
    }
  };

  const handleExport = () => {
    if (data.length === 0) return;
    const exportData = data.map((item, idx) => ({
        'No': idx + 1,
        'Bulan': item.bulan,
        'Jenis Beban': item.jenis_beban,
        'Kategori': item.kategori,
        'Nominal': item.nominal
    }));
    
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(exportData);
    XLSX.utils.book_append_sheet(wb, ws, "Biaya Non Jahit");
    XLSX.writeFile(wb, `Biaya_Non_Jahit_${selectedMonth}.xlsx`);
  };

  // Calculate Total
  const totalNominal = data.reduce((sum, item) => sum + Number(item.nominal || 0), 0);

  return (
    <div className="space-y-6">
      {/* Toolbar */}
      <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex flex-col md:flex-row justify-between items-center gap-4">
        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                <input 
                    type="text" 
                    placeholder="Cari Jenis Beban..." 
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="pl-9 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-erp-pink w-64"
                />
            </div>
            
            <div className="relative">
                <Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
                <select 
                    value={selectedMonth}
                    onChange={(e) => setSelectedMonth(e.target.value)}
                    className="pl-9 pr-8 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-erp-pink bg-white cursor-pointer appearance-none min-w-[180px]"
                >
                    <option value="" disabled>Pilih Bulan</option>
                    {availableMonths.map(m => (
                        <option key={m} value={m}>{m}</option>
                    ))}
                </select>
            </div>
        </div>

        <div className="flex gap-2">
            <button 
                onClick={handleRecalculate} 
                disabled={isRecalculating || !selectedMonth}
                className="bg-orange-50 text-orange-600 border border-orange-200 px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-orange-100 transition-colors disabled:opacity-50"
            >
                {isRecalculating ? <Loader2 className="animate-spin" size={16}/> : <Calculator size={16}/>} 
                Hitung Ulang
            </button>
            <button onClick={() => { fetchData(); fetchOutputData(); }} className="bg-white border border-gray-200 text-gray-600 px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-gray-50 transition-colors">
                <RefreshCw size={16}/> Refresh
            </button>
            <button onClick={handleExport} className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:bg-green-700 transition-colors shadow-sm">
                <Download size={16}/> Export
            </button>
        </div>
      </div>

      {/* Grid Layout: Summary Card + Output Line Table */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Left: Summary Card (Total Biaya) */}
          <div className="lg:col-span-1 bg-white p-6 rounded-xl border border-blue-100 shadow-sm flex flex-col justify-center bg-gradient-to-r from-blue-50 to-white h-full min-h-[200px]">
             <div className="mb-4">
                <h3 className="text-blue-800 font-bold text-lg">Total Biaya Operasional</h3>
                <p className="text-blue-600 text-sm mt-1">Non Jahit (Admin, Staff, Lainnya)</p>
             </div>
             <div className="text-4xl font-bold text-blue-700 tracking-tight">
                {formatRupiah(totalNominal)}
             </div>
          </div>

          {/* Right: Output Line Table (Read Only) */}
          <div className="lg:col-span-2 bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col h-full min-h-[200px]">
             <div className="p-4 border-b border-gray-100 bg-gray-50 flex justify-between items-center">
                 <h3 className="font-bold text-gray-700 flex items-center gap-2">
                     <Layers size={16} className="text-erp-pink"/> Output Line (Produksi)
                 </h3>
                 <span className="text-xs text-gray-500 bg-white px-2 py-1 rounded border border-gray-200">
                     {selectedMonth || 'Pilih Bulan'}
                 </span>
             </div>
             
             <div className="overflow-auto custom-scrollbar flex-1 max-h-[300px]">
                 <table className="w-full text-xs text-left">
                     <thead className="bg-white text-gray-600 font-bold border-b border-gray-100 sticky top-0 z-10">
                         <tr>
                             <th className="px-4 py-3">Bulan</th>
                             <th className="px-4 py-3">Bagian</th>
                             <th className="px-4 py-3 text-right">Qty Output</th>
                         </tr>
                     </thead>
                     <tbody className="divide-y divide-gray-50">
                         {loadingOutput ? (
                             <tr><td colSpan={3} className="p-8 text-center"><Loader2 className="animate-spin inline text-erp-pink"/></td></tr>
                         ) : aggregatedOutput.length > 0 ? (
                             <>
                                {aggregatedOutput.map((item, idx) => (
                                    <tr key={idx} className="hover:bg-gray-50">
                                        <td className="px-4 py-2 text-gray-600">{item.bulan}</td>
                                        <td className="px-4 py-2 font-bold text-blue-600">{item.bagian}</td>
                                        <td className="px-4 py-2 text-right font-bold text-gray-800">{Number(item.qty).toLocaleString()}</td>
                                    </tr>
                                ))}
                                {/* Footer Total */}
                                <tr className="bg-gray-100 font-bold border-t border-gray-200">
                                    <td className="px-4 py-3 text-right" colSpan={2}>TOTAL QTY</td>
                                    <td className="px-4 py-3 text-right text-green-700">{totalOutputQty.toLocaleString()}</td>
                                </tr>
                             </>
                         ) : (
                             <tr><td colSpan={3} className="p-8 text-center text-gray-400 italic">Tidak ada data output Line 1-5 untuk bulan ini.</td></tr>
                         )}
                     </tbody>
                 </table>
             </div>
          </div>
      </div>

      {/* Main Table: Biaya Non Jahit */}
      {isTableMissing ? (
        <div className="bg-red-50 border border-red-200 rounded-xl p-8 text-center">
            <Database className="mx-auto text-red-400 mb-2" size={32}/>
            <h3 className="text-lg font-bold text-red-800">Tabel Biaya Belum Siap</h3>
            <p className="text-red-600 text-sm mb-4">Silakan jalankan script SQL untuk membuat tabel dan fungsi perhitungan.</p>
            <button onClick={() => setShowSqlModal(true)} className="bg-red-600 text-white px-6 py-2 rounded-lg font-medium shadow-md hover:bg-red-700 transition-colors">
                Setup Database
            </button>
        </div>
      ) : (
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm">
            <div className="p-4 border-b border-gray-100 bg-gray-50">
                <h3 className="font-bold text-gray-700 flex items-center gap-2">
                    <TrendingUp size={16} className="text-erp-pink"/> Rincian Biaya Non Jahit
                </h3>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                    <thead className="bg-white text-gray-600 font-bold border-b border-gray-200">
                        <tr>
                            <th className="px-6 py-4 w-16 text-center">No</th>
                            <th className="px-6 py-4">Bulan</th>
                            <th className="px-6 py-4">Jenis Beban</th>
                            <th className="px-6 py-4">Kategori</th>
                            <th className="px-6 py-4 text-right">Nominal</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {isLoading ? (
                            <tr><td colSpan={5} className="p-12 text-center"><Loader2 className="animate-spin inline text-erp-pink"/> Memuat data...</td></tr>
                        ) : data.length > 0 ? (
                            data.map((item, idx) => (
                                <tr key={idx} className="hover:bg-gray-50 transition-colors">
                                    <td className="px-6 py-4 text-center text-gray-500">{idx + 1}</td>
                                    <td className="px-6 py-4 text-gray-700">{item.bulan}</td>
                                    <td className="px-6 py-4 font-medium text-gray-900">{item.jenis_beban}</td>
                                    <td className="px-6 py-4">
                                        <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                                            item.kategori === 'NON JAHIT' ? 'bg-orange-100 text-orange-700' :
                                            item.kategori === 'ADMIN PABRIK' ? 'bg-purple-100 text-purple-700' :
                                            'bg-blue-100 text-blue-700'
                                        }`}>
                                            {item.kategori}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 text-right font-bold text-gray-800">{formatRupiah(item.nominal)}</td>
                                </tr>
                            ))
                        ) : (
                            <tr><td colSpan={5} className="p-16 text-center text-gray-400 italic">Belum ada data biaya operasional. Klik "Hitung Ulang" untuk generate.</td></tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>
      )}

      {/* SQL Modal */}
      {showSqlModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4 animate-fadeIn">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden">
            <div className="p-5 border-b border-gray-100 flex justify-between items-center bg-blue-50">
              <h3 className="font-bold text-lg text-blue-800 flex items-center gap-2">
                <Database size={20}/> Setup Database Biaya Operasional
              </h3>
              <button onClick={() => setShowSqlModal(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            <div className="p-6">
              <p className="text-gray-600 text-sm mb-4">
                Salin kode SQL di bawah ini dan jalankan di <b>Supabase SQL Editor</b> untuk membuat tabel dan fungsi perhitungan otomatis.
              </p>
              
              <div className="relative">
                <textarea 
                  className="w-full h-64 p-4 text-xs font-mono bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-erp-pink outline-none"
                  readOnly
                  value={sqlSetupCode}
                  onClick={(e) => e.currentTarget.select()}
                />
                <button 
                  onClick={handleCopySQL}
                  className="absolute top-2 right-2 p-2 bg-white rounded-md shadow-sm border border-gray-200 hover:bg-gray-50 text-gray-600"
                  title="Salin Kode"
                >
                  <Copy size={16}/>
                </button>
              </div>

              <div className="mt-4 flex justify-end gap-3">
                <button 
                    onClick={() => setShowSqlModal(false)} 
                    className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm font-medium"
                >
                    Tutup
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      <SuccessModal isOpen={successModal.isOpen} onClose={() => setSuccessModal({ ...successModal, isOpen: false })} title={successModal.title} message={successModal.message} />
      <ErrorModal isOpen={errorModal.isOpen} onClose={() => setErrorModal({ ...errorModal, isOpen: false })} title={errorModal.title} message={errorModal.message} />
    </div>
  );
};
